<div class="container">
    <div id="declarers-list" data-entrypoint="<?= $this->url('person/declarers') ?>"></div>
    <?= $this->Vite()->addJs('src/DeclarersList.js'); ?>
    <?php
    /****

    <h1><i class="icon-group"></i> Déclarants</h1>
    <div id="declarers"></div>
    <script>
        require(['vue', 'vue-resource', 'Declarers'], function(Vue, VueResource, Declarers){
            Vue.use(VueResource);
            new Vue({
                el: '#declarers',
                render(h){
                    return h(Declarers.default, { props: {urlRecallDeclarer: '<?= $this->url('timesheet/recall-declarer') ?>'}});
                }
            })
        })
    </script>
     ****/ ?>
</div>