<?php
/**
 * @author Stéphane Bouvry<stephane.bouvry@unicaen.fr>
 * @date: 28/09/15 15:47
 * @copyright Certic (c) 2015
 */

/** @var \Oscar\Entity\Person $entity */
?>

<section class="container">
    <div class="row">
        <h1 class="">
            <?= $entity->getFirstname() ?>
            <strong class="lastname"><?= $entity->getLastname() ?></strong>
            <?php if($entity->getLdapAffectation() ):?>
            <span><?= $entity->getLdapAffectation() ?></span>
            <?php endif; ?>
        </h1>
        <p>
            <i class="icon-mail"></i> <?= $entity->getEmail() ?>
            <?php if($this->grant()->privilege(\Oscar\Provider\Privileges::DROIT_PRIVILEGE_VISUALISATION)): ?>
                <a href="<?= $this->url('person/access', ['id' => $entity->getId()]) ?>" class="btn btn-default btn-xs">
                    <i class="icon-lock"></i>
                    Voir les privilèges
                </a>
            <?php endif; ?>

            <?php if($this->grant()->privilege(\Oscar\Provider\Privileges::PERSON_EDIT)): ?>
            <form action="<?= $this->url('person/delete', ['id' => $entity->getId()]) ?>" method="post">
                <button type="submit" class="btn btn-default btn-xs">
                    <i class="icon-lock"></i>
                    Supprimer
                </button>
            </form>
            <?php endif; ?>

            <?php if( $allowTimesheet ): ?>
                <a href="<?= $this->url('timesheet/declarant') ?>?person=<?= $entity->getId() ?>" class="btn btn-default btn-xs">
                    <i class="icon-calendar"></i>
                    Compléter la feuille de temps
                </a>
            <?php endif; ?>
        </p>


        <div class="cols two">
            <section class="col">
                <h2>
                    <span><i class="icon-help-circled"></i> Informations générales</span>
                </h2>
                <div class="cols">
                    <div class="col col-1">
                        <img src="//www.gravatar.com/avatar/<?= md5($entity->getEmail()) ?>?s=250"
                             style="border-radius: 20px; width: 100%"
                             alt="" />
                    </div>
                    <div class="col col-2">
                        <div class="data-list">
                            <div class="data-row">
                                <div class="data-label">Nom affiché</div>
                                <div class="data-value"><?= $entity->getDisplayName() ?></div>
                            </div>
                            <div class="data-row">
                                <div class="data-label">Prénom</div>
                                <div class="data-value"><?= $entity->getFirstname() ?></div>
                            </div>
                            <div class="data-row">
                                <div class="data-label">Nom</div>
                                <div class="data-value"><?= $entity->getLastname() ?></div>
                            </div>
                            <div class="data-row">
                                <div class="data-label">Courriel</div>
                                <div class="data-value"><i class="icon-mail"></i><?= $entity->getEmail() ?></div>
                            </div>
                            <div class="data-row">
                                <div class="data-label">Téléphone</div>
                                <div class="data-value"><i class="icon-phone-outline"></i><?= $entity->getPhone() ?></div>
                            </div>
                            <div class="data-row">
                                <div class="data-label">LDAP (Localisation)</div>
                                <div class="data-value"><?= $entity->getLdapSiteLocation() ?></div>
                            </div>
                            <div class="data-row">
                                <div class="data-label">LDAP (Affectation)</div>
                                <div class="data-value"><?= $entity->getLdapAffectation() ?></div>
                            </div>
                            <div class="data-row">
                                <div class="data-label">LDAP (Statut)</div>
                                <div class="data-value"><?= $entity->getLdapStatus() ?></div>
                            </div>
                            <div class="data-row">
                                <div class="data-label">Projets</div>
                                <div class="data-value"><i class="icon-cubes"></i>
                                    Impliqué dans <a href="#projects"><?= count($projects) ?> projet(s)</a>
                                </div>
                            </div>
                            <?php if( $this->grant(\Oscar\Provider\Privileges::PERSON_VIEW_TIMESHEET) ): ?>
                                <div class="data-row">
                                    <div class="data-label">Feuille de temps</div>
                                    <div class="data-value">
                                        <?php if( count($entity->getWorkPackages()) ): ?>
                                            <a href="<?= $this->url('timesheet/resume') ?>?person_id=<?= $entity->getId() ?>" >
                                                <i class="icon-calendar"></i>
                                                Voir les feuilles de temps
                                            </a>
                                        <?php else: ?>
                                            Cette personne n'a pas été identifiée comme déclarant sur un lot de travail
                                        <?php endif; ?>
                                    </div>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
                <nav class="admin-bar text-center">
                    <div class="btn-group">

                        <?php if( $this->grant()->privilege(\Oscar\Provider\Privileges::PERSON_EDIT) ): ?>
                        <a class="btn btn-default btn-xs" href="<?= $this->url('person/edit', ['id'=>$entity->getId()]) ?>">
                            <i class="icon-pencil"></i>
                            Éditer les informations
                        </a>
                        <?php endif; ?>

                        <?php if( $this->grant()->privilege(\Oscar\Provider\Privileges::MAINTENANCE_NOTIFICATION_PERSON) ): ?>
                            <a class="btn btn-default btn-xs" href="<?= $this->url('person/notification', ['id'=>$entity->getId()]) ?>">
                                <i class="icon-bell"></i>
                                Voir les notifications
                            </a>
                        <?php endif; ?>


                    </div>
                </nav>
            </section>

            <section class="col">
                <h2><i class="icon-sitemap"></i> Hiérarchie</h2>
                <p>Les informations hiérarchiques sont utilisées par Oscar pour déterminer les personnes en charge lors de la procédure de <strong>validation des feuilles de temps</strong>.</p>
                <?php /* <hr>
                <div class="row">
                    <div class="col-md-12">
                        <ul>
                        <?php
                        foreach ($validations as $validationPeriod): ?>
                            <li><?= $validationPeriod ?>
                                <?php if($validationPeriod->getObjectGroup() == \Oscar\Entity\ValidationPeriod::GROUP_WORKPACKAGE): ?>
                                    <?php if(count($validationPeriod->getValidatorsSci()) == 0): ?>
                                        <span class="cartouche danger">
                                            <i class="icon-beaker"></i> Aucun validateur scientifique
                                        </span>
                                    <?php endif; ?>
                                    <?php if(count($validationPeriod->getValidatorsPrj()) == 0): ?>
                                        <span class="cartouche danger">
                                            <i class="icon-cubes"></i> Aucun validateur projet
                                        </span>
                                    <?php endif; ?>
                                <?php endif; ?>
                                <?php if(count($validationPeriod->getValidatorsAdm()) == 0): ?>
                                <i class="icon-attention-1"></i> Aucun validateur administratif !
                                <?php endif; ?>
                            </li>
                        <?php endforeach; ?>
                        </ul>
                    </div>
                </div>
                /****/ ?>
                <div class="row">
                    <div class="col-md-4">
                        <h4><i class="icon-group"></i>Est validé par (N+1)</h4>
                        <?php if( count($referents) ): ?>
                            <?php foreach ($referents as $referent): ?>
                                <article class="card card-xs">
                                    <i class="icon-user"></i>
                                    <a href="<?= $this->url('person/show', ['id' => $referent->getReferent()->getId() ]); ?>"><?= $referent->getReferent() ?></a>
                                    <?php if( $manageHierarchie ): ?>
                                    <form action="" method="post" class="form-inline">
                                        <input type="hidden" name="action" value="removereferent" />
                                        <input type="hidden" name="referent_id" value="<?= $referent->getId() ?>" />
                                        <button type="submit" class="btn btn-danger btn-xs" title="supprimer"><i class="icon-trash"></i></button>
                                    </form>
                                    <?php endif; ?>
                                </article>
                            <?php endforeach; ?>
                        <?php else: ?>
                            <?php if(count($entity->getWorkPackages())): ?>
                                <p class="alert alert-danger">
                                    <i class="icon-attention"></i> <strong><?= $entity ?></strong> a été identifié comme déclarant, mais personne n'a été identifié pour assurer la validation administrative.
                                </p>
                            <?php endif; ?>
                        <?php endif; ?>

                        <?php if( $manageHierarchie ): ?>
                        <button id="editReferent" onclick="$('#referentEditor').show(); $('#editReferent').hide();">
                            <i class="icon-pencil"></i> Ajouter un référent</button>

                        <form id="referentEditor" action="" method="POST" style="display: none">
                            Selectionner un référent :
                            <input type="hidden" value="<?= $entity->getId() ?>" name="person_id">
                            <input type="hidden" value="referent" name="action">
                            <select name="referent_id" class="selectPerson"></select>
                            <button type="submit">Enregistrer</button>
                            <button type="button" onclick="$('#referentEditor').hide(); $('#editReferent').show();">Annuler</button>
                        </form>

                        <script>
                            var formatRepo = function (repo) {
                                if (repo.loading) return repo.text;

                                var markup = '<div class="clearfix">';
                                markup += repo.label || repo.text;
                                markup += '</div>';

                                return markup;
                            };

                            var formatRepoSelection = function (repo) {
                                return repo.label || repo.text;
                            };

                            require(['jquery', 'select2'], function($, select2){
                                $(".selectPerson").select2({
                                        placeholder: 'Rechercher une personne...',
                                        width: '100%',
                                        allowClear: true,
                                        ajax: {
                                            url: '<?= $this->url('person/search') ?>',
                                            dataType: 'json',
                                            delay: 250,
                                            data: function (params) {
                                                return {
                                                    q: params.term, // search term
                                                    page: params.page
                                                };
                                            },
                                            processResults: function (data, page) {
                                                return {results: data.datas};
                                            },
                                            cache: true
                                        },
                                        escapeMarkup: function (markup) {
                                            return markup;
                                        },
                                        minimumInputLength: 3,
                                        id: function (dt) {
                                            return dt.uid;
                                        },
                                        templateResult: formatRepo, // omitted for brevity, see the source of this page
                                        templateSelection: formatRepoSelection // omitted for brevity, see the source of this page
                                    }
                                );
                            })
                        </script>
                        <?php endif; ?>
                    </div>
                    <div class="col-md-4">
                        <h4><i class="icon-group"></i>Valide les déclarations pour (N-1)</h4>
                        <p><strong><?= $entity ?></strong> a la charge de valider les déclarations Hors-Lot pour les personnes suivantes : </p>
                        <?php if( $subordinates ): ?>
                            <?php foreach ($subordinates as $subordinate) :?>
                                <article class="card card-xs">
                                    <i class="icon-user"></i>
                                    <a href="<?= $this->url('person/show', ['id' => $subordinate->getPerson()->getId() ]); ?>"><?= $subordinate->getPerson() ?></a>
                                    <?php if( $manageHierarchie ): ?>
                                    <form action="" method="post" class="form-inline">
                                        <input type="hidden" name="action" value="removereferent" />
                                        <input type="hidden" name="referent_id" value="<?= $subordinate->getId() ?>" />
                                        <button type="submit" class="btn btn-danger btn-xs" title="supprimer"><i class="icon-trash"></i></button>
                                    </form>
                                    <?php endif; ?>
                                </article>
                            <?php endforeach; ?>

                            <?php if( $manageHierarchie ): ?>
                            <div id="managereferents"></div>
                            <script>
                                require(['vue', 'vue-resource', 'Referent'], function(Vue, VueResource, Referent){
                                    Vue.use(VueResource);
                                    new Vue({
                                        el: '#managereferents',
                                        render(h){
                                            return h(Referent.default, {props:{
                                                referentId: <?= $entity->getId() ?>,
                                                declarationsToDo: <?= json_encode($declarationsToDo) ?>,
                                                declarationsFor: <?= json_encode(array_map(function($p){return $p->getPerson()->getDisplayName(); }, $subordinates)) ?>,
                                                displayName: "<?= $entity->getDisplayName() ?>"}});
                                        }
                                    })
                                })
                            </script>
                            <?php endif; ?>

                        <?php else: ?>
                            Personne
                        <?php endif; ?>
                    </div>

                    <div class="col-md-4">
                        <h4><i class="icon-calendar"></i>Délégation</h4>
                        <p class="oscar-help"><small>
                                <i class="icon-help-circled"></i>
                                Les personnes listées ici sont authorisées à remplir les feuilles de temps de <strong><?= $entity ?></strong>
                            </small></p>

                            <?php foreach ($entity->getTimesheetsBy() as $p) :?>
                                <article class="card card-xs">
                                    <i class="icon-user"></i>
                                    <a href="<?= $this->url('person/show', ['id' => $p->getId() ]); ?>"><?= $p ?></a>
                                    <?php if( $manageUsurpation ): ?>
                                        <form action="" method="post" class="form-inline">
                                            <input type="hidden" name="action" value="removeusurpation" />
                                            <input type="hidden" name="person_id" value="<?= $p->getId() ?>" />
                                            <button type="submit" class="btn btn-danger btn-xs" title="supprimer"><i class="icon-trash"></i></button>
                                        </form>
                                    <?php endif; ?>
                                </article>
                            <?php endforeach; ?>

                        <?php if($manageUsurpation): ?>
                            <button id="editUsurpation" class="btn btn-xs btn-primary" onclick="$('#usurpationEditor').show(); $('#editUsurpation').hide();">
                                <i class="icon-plus-circled"></i> Ajouter</button>

                            <form id="usurpationEditor" action="" method="POST" style="display: none">
                                Ajouter un délégué pour les feuilles de temps :
                                <input type="hidden" value="addusurpation" name="action">
                                <select name="person_id" class="selectPerson"></select>
                                <button type="submit" class="btn btn-xs btn-primary">Enregistrer</button>
                                <button type="button" class="btn btn-xs btn-default" onclick="$('#usurpationEditor').hide(); $('#editUsurpation').show();">Annuler</button>
                            </form>

                            <script>
                                var formatRepo = function (repo) {
                                    if (repo.loading) return repo.text;

                                    var markup = '<div class="clearfix">';
                                    markup += repo.label || repo.text;
                                    markup += '</div>';

                                    return markup;
                                };

                                var formatRepoSelection = function (repo) {
                                    return repo.label || repo.text;
                                };

                                require(['jquery', 'select2'], function($, select2){
                                    $(".selectPerson").select2({
                                            placeholder: 'Rechercher une personne...',
                                            width: '100%',
                                            allowClear: true,
                                            ajax: {
                                                url: '<?= $this->url('person/search') ?>',
                                                dataType: 'json',
                                                delay: 250,
                                                data: function (params) {
                                                    return {
                                                        q: params.term, // search term
                                                        page: params.page
                                                    };
                                                },
                                                processResults: function (data, page) {
                                                    return {results: data.datas};
                                                },
                                                cache: true
                                            },
                                            escapeMarkup: function (markup) {
                                                return markup;
                                            },
                                            minimumInputLength: 3,
                                            id: function (dt) {
                                                return dt.uid;
                                            },
                                            templateResult: formatRepo, // omitted for brevity, see the source of this page
                                            templateSelection: formatRepoSelection // omitted for brevity, see the source of this page
                                        }
                                    );
                                })
                            </script>
                        <?php endif; ?>
                    </div>
                </div>
            </section>
        </div>
        <div class="cols two">

            <section class="col">

                <?php if($this->grant()->privilege(\Oscar\Provider\Privileges::PERSON_MANAGE_SCHEDULE)): ?>
                <h2><i class="icon-clock"></i> Horaires</h2>
                <div id="manage-schedule"></div>
                <script>
                    require(['vue', 'vue-resource', 'mm', 'PersonSchedule'], function(Vue, VueResource, moment, PersonSchedule){
                        Vue.use(VueResource);
                        Vue.filter('heures', function(v){
                            var heure = Math.floor(v);
                            var minutes = Math.round((v-heure)*60);
                            return heure +':' +minutes;
                        });
                       new Vue({
                           'el': '#manage-schedule',
                           render: function(h){
                               return h(PersonSchedule.default, { props: {urlapi:'?a=schedule', editable: <?= $scheduleEditable ? 'true' : 'false' ?>}})
                           }
                       })
                    });
                </script>
                <?php endif; ?>


                <h2><i class="icon-building-filled"></i> Structures</h2>

                <?php if( count($entity->getOrganizations()) ): ?>
                <?php
                /** @var \Oscar\Entity\OrganizationPerson $organizationPerson */
                foreach( $entity->getOrganizations() as $organizationPerson ): ?>
                    <article class="card">
                        <p class="text-highlight">
                            <strong><?= $organizationPerson->getRole() ? $organizationPerson->getRole() : '<em>impliqué</em>' ?></strong>
                            dans
                            <?= $this->link()->organization($organizationPerson->getOrganization()); ?>
                            <?php if( $organizationPerson->getRoleObj()->isPrincipal() ): ?>
                                <br><small>Ce rôle accorde des droits à <strong><?= $entity ?></strong> sur <strong><?= $organizationPerson->getOrganization() ?></strong></small>
                            <?php endif; ?>
                        </p>
                    </article>
                <?php endforeach; ?>
                <?php else: ?>
                <div class="alert alert-info">
                    Cette personne n'est associée à aucune structure
                </div>
                <?php endif; ?>
            </section>

            <section class="col">
                <?php if($this->grant()->privilege(\Oscar\Provider\Privileges::PERSON_SYNC_LDAP)): ?>
                <h2><i class="icon-cog"></i> Donnèes techniques</h2>
                <p class="text-highlight text-small">
                    Dernière mise à jour :
                    <?php if($entity->getDateSyncLdap()): ?>
                        <strong class="text-success">
                            <i class="icon-ok-circled"></i>
                            <?= $this->moment($entity->getDateSyncLdap()) ?>
                            <span class="text-light">(<?= $this->moment($entity->getDateSyncLdap())->since() ?>)</span>
                        </strong>
                    <?php else: ?>
                        <i class="icon-cancel-circled-outline"></i>
                        <em>Jamais</em>
                    <?php endif; ?>
                    <br/>
                    Créé le <time><?= $this->moment($entity->getDateCreated())->full() ?></time>
                </p>

                <?php if($auth): ?>
                    <div class="alert alert-info">
                        <p><?= $entity ?> est actif sur Oscar (Dernière connexion <strong><?= $this->moment($auth->getDateLogin())->full() ?></strong>).</p>
                    </div>
                <?php endif; ?>
                <div class="data-list card">
                    <div class="data-row">
                        <div class="data-label">#ID (Oscar)</div>
                        <div class="data-value"><?= $entity->getId() ?></div>
                    </div>
                    <div class="data-row">
                        <div class="data-label">LDAP > Identifiant</div>
                        <div class="data-value"><?= $entity->getLadapLogin() ?></div>
                    </div>

                    <div class="data-row">
                        <div class="data-label">Authentification</div>
                        <div class="data-value"><?= $entity->getLadapLogin() ?></div>
                    </div>

                    <div class="data-row">
                        <div class="data-label">Modèle horaire</div>
                        <div class="data-value"><?= $entity->getScheduleKey() ?></div>
                    </div>

                    <div class="data-row">
                        <div class="data-label">LDAP > Activité</div>
                        <div class="data-value"><?= $entity->getLdapDisabled() ? "Inactif" : "Actif" ?></div>
                    </div>
                    <div class="data-row">
                        <div class="data-label">LDAP > Fin</div>
                        <div class="data-value"><?= $entity->getLdapFinInscription() ?></div>
                    </div>
                    <div class="data-row">
                        <div class="data-label">Droits spécifiques</div>
                        <div class="data-value">
                            <?php if( $authentification == null ): ?>
                            <em>Pas d'authentification</em>
                            <?php elseif ($authentification->getRoles() ): ?>
                                <?php foreach( $authentification->getRoles() as $role) : ?>
                                    <span class="cartouche <?= $role->isPrincipal() ? 'primary' : '' ?>"><?= $role ?></span>
                                <?php endforeach; ?>
                            <?php endif; ?>
                        </div>
                    </div>



                    <div class="data-row">
                        <div class="data-label">Connecteur(s)</div>
                        <div class="data-value"><ul>
                                <?php foreach( $connectors as $connector ): ?>
                                    <li>
                                        <?= $connector ?> :
                                        <?php if( $entity->getConnectorID($connector) ): ?>
                                            <strong><?= $entity->getConnectorID($connector) ?></strong>
                                            <?php if( $this->grant()->privilege(\Oscar\Provider\Privileges::MAINTENANCE_CONNECTOR_ACCESS) ): ?>
                                                <a  href="<?= $this->url('connector/person') ?>?c=<?= $connector ?>&v=<?= $entity->getConnectorID($connector) ?>"
                                                    class="btn btn-xs btn-primary">
                                                    synchroniser</a>
                                            <?php endif; ?>
                                        <?php else: ?>
                                            <em>Non connecté</em>
                                        <?php endif; ?>
                                    </li>
                                <?php endforeach; ?>
                            </ul></div>
                    </div>

                    <div class="data-row">
                        <div class="data-label">Groupes LDAP</div>

                        <div class="data-value">
                            <?php if( $entity->getLdapMemberOf() ): ?>
                                <nav class="options-menu right">
                                    <a href="#" id="toogleButton">
                                        <i class="icon-eye"></i> Groupes sans effets</a>
                                </nav>
                                <ul class="ldap-groups">
                                    <?php foreach( $entity->getLdapMemberOf() as $memberOf ): ?>
                                        <?php if( array_key_exists($memberOf, $ldapRoles) ):?>
                                            <li>
                                                <i class="icon-group"></i><code><?= $memberOf ?></code>
                                                <span class="cartouche <?= $ldapRoles[$memberOf]['principal'] ? 'primary' : '' ?>"><?= $ldapRoles[$memberOf]['roleId'] ?></span>
                                            </li>
                                        <?php else: ?>
                                            <li class="no-role"><i class="icon-group"></i><code><?= $memberOf ?></code></li>
                                        <?php endif; ?>
                                    <?php endforeach; ?>
                                </ul>
                                <script>
                                    (function(){
                                        document.querySelector('#toogleButton').addEventListener('click', function(evt){
                                            evt.preventDefault();
                                            document.querySelector('.ldap-groups').classList.toggle('show-off');
                                        })
                                    })();
                                </script>
                            <?php else: ?>
                                <div class="alert alert-info">
                                    Aucun groupe LDAP
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>

                </div>
                <?php endif ?>
            </section>
        </div>

        <section id="projects">
            <h2><i class="icon-cubes"></i> Projets</h2>
            <?php foreach( $projects as $project ): ?>
                <?= $this->partial('/oscar/project/project-item-openable.phtml', ['project'    => $project]); ?>
            <?php endforeach; ?>
            <?= $this->pager($projects, preg_replace("/\\??&page=[0-9]*/", '', $_SERVER['REQUEST_URI']) . '?&page=%s') ?>
        </section>


            <?php if( count($activities) ): ?>
                <section id="activites" class="card">
                    <h2>Activités de recherche (Sans projet)</h2>
                    <?php
                    $year = null;
                    $discipline = null;
                    foreach( $activities as $activity ):
                        if( $activity->getProject() !== null ) continue;
                        $activityYear = $activity->getDateCreated()->format('Y');
                        if( $activityYear != $year ){
                            echo "<div class='list-separator'><h3 class='list-separator-label'>$activityYear</h3></div>";
                            $year = $activityYear;
                        }
                        ?>
                        <?= $this->partial('/oscar/project-grant/item-list.phtml', [
                        'activity'    => $activity,
                    ]); ?>
                    <?php endforeach; ?>
                </section>
            <?php endif; ?>

            <?php if($this->grant()->privilege(\Oscar\Provider\Privileges::DROIT_PRIVILEGE_EDITION)): ?>
                <section class="card">
                    <h2>Activités récentes</h2>
                    <?= $this->partial('oscar/activity-log/frag-list.phtml',
                        ['entities' => $traces]) ?>
                </section>
            <?php endif; ?>
        </div>
    </div>
</section>


