<div class="container">
    <div id="app"></div>
</div>
<script>
    require(['vue', 'vue-resource', 'moment', '<?= $composant ?>'], function(Vue, VueResource, moment, Composant){
        Vue.use(VueResource);

        Vue.filter('dateFull', function(date) {
            var m = moment(date);
            return "le " + m.format('dddd D MMMM YYYY') + ', ' + moment(date).fromNow();
        });

        Vue.filter('dateFullSort', function(date) {
            var m = moment(date);
            return m.format('D MMMM YYYY') + ', ' + moment(date).fromNow();
        });

        Vue.filter('filesize', function(octets) {
            var sizes = ['Octets', 'KB', 'MB', 'GB', 'TB'];
            if (octets == 0) return '0 Octet';
            var i = parseInt(Math.floor(Math.log(octets) / Math.log(1024)));
            return Math.round(octets / Math.pow(1024, i), 2) + ' ' + sizes[i];
        });

        new Vue({
            render: function(h){
                return h(Composant);
            }
        }).$mount('#app')
    })
</script>
<?php
