stages:
  - test

variables:
  # Cette variable permet de spécifier que Composer installera uniquement les dépendances nécessaires
  COMPOSER_ALLOW_SUPERUSER: 1
  APP_ENV: test

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - vendor/

test:
  stage: test
  image: php:8.2
  before_script:
    # Met à jour Composer et installe les dépendances
    - apt-get update -yqq
    - apt-get install git unzip -yqq
    - curl -sS https://getcomposer.org/installer | php
    - php composer.phar install --prefer-dist --no-progress --no-interaction
  script:
    # Exécute les tests PHPUnit
    - mkdir -p tests/_output
    - ./vendor/bin/phpunit --colors=always  --log-junit tests/_output/junit.xml
  artifacts:
    when: always
    expire_in: 1 week
    reports:
      junit: tests/_output/junit.xml