image: localhost:5000/unicaen-dev-php7.3-apache
before_script:
  - export http_proxy=http://10.14.128.99:3128
  - export https_proxy=http://10.14.128.99:3128
  - apt-get -qq update && apt-get -qq install -y curl wget gnupg2 build-essential libssl-dev git
  - wget https://getcomposer.org/download/latest-stable/composer.phar
  - php composer.phar --ignore-platform-reqs
#  - curl -sL https://deb.nodesource.com/setup_6.x | bash
#  - apt-get -qq install -y nodejs
#  - npm install --silent

test:
  script:
  - php vendor/bin/phpunit --bootstrap vendor/autoload.php tests/
