stages:
  - test

variables:
  # Cette variable permet de spécifier que Composer installera uniquement les dépendances nécessaires
  COMPOSER_ALLOW_SUPERUSER: 1
  APP_ENV: test

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - vendor/

before_script:
  # Met à jour Composer et installe les dépendances
  - docker logout

test:
  stage: test
  image: debian:bookworm

  before_script:
    # Met à jour Composer et installe les dépendances
    - apt-get update -yqq
    - apt-get install git unzip curl -yqq
    - apt-get install -y wget php8.2-cli php8.2-bcmath php8.2-bz2 php8.2-curl php8.2-dom php8.2-gd php8.2-intl php8.2-ldap php8.2-mbstring php8.2-pgsql php8.2-xml php8.2-zip
    - wget https://getcomposer.org/download/2.2.22/composer.phar
    - php composer.phar install --prefer-dist --no-progress --no-interaction

  script:
    # Exécute les tests PHPUnit
    - mkdir -p tests/_output
    - ./vendor/bin/phpunit --colors=always  --log-junit tests/_output/junit.xml

  artifacts:
    when: always
    expire_in: 1 week
    reports:
      junit: tests/_output/junit.xml