image: localhost:5000/unicaen-dev-php7.0-apache
before_script:
  - export http_proxy=http://10.14.128.99:3128
  - export https_proxy=http://10.14.128.99:3128
  - apt-get -qq update && apt-get -qq install -y curl wget gnupg2 build-essential libssl-dev git subversion php7.2 php7.2-cli php7.2-gd php7.2-curl php7.2-intl php7.2-xml php7.2-ldap php7.2-mbstring php7.0-mcrypt php7.2-zip
  - wget https://getcomposer.org/composer.phar
  - php composer.phar install
  - curl -sL https://deb.nodesource.com/setup_6.x | bash
  - apt-get -qq install -y nodejs
  - npm install --silent


test:
  script:
  - php vendor/bin/phpunit --bootstrap vendor/autoload.php tests/