#
# DOCKER (Développement)
networks:
  oscar-dev-network:
    driver: bridge

services:
  # Postgresql (Base de données)
  oscar-dev-postgres:
    container_name: oscar-dev-postgres
    restart: always
    environment:
      # Accès BDD
      POSTGRES_USER: oscar_dev_user
      POSTGRES_PASSWORD: oscar_dev_pass
      POSTGRES_DB: oscar_dev_db

    networks:
      - oscar-dev-network
#    env_file: # TODO
#      - .env.docker.dev
    ports:
      - 6543:5432
    volumes:
      - ./docker/dev/volumes/databases/oscar_dev_data:/var/lib/postgresql/data
      - ./docker/dev/postgresql/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d
    build:
      context: ./docker/dev/postgresql
      dockerfile: Dockerfile

  oscar-dev-apache:
    container_name: oscar-dev-apache
    restart: unless-stopped
    volumes:
      - ./:/var/application
    depends_on:
      - oscar-dev-gearman
    networks:
      - oscar-dev-network
#    env_file: # TODO
#      - .env.docker.dev
    build:
      context: ./docker/dev/apache/
      dockerfile: Dockerfile
    ports:
      - 8888:80

  oscar-dev-gearman:
    container_name: oscar-dev-gearman
    image: artefactual/gearmand:1.1.21.2-alpine
    networks:
      - oscar-dev-network
    tty: true
    restart: "unless-stopped"

  oscar-dev-elasticsearch:
    container_name: oscar-dev-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.1
    environment:
      - discovery.type=single-node
#      - node.name=oscar01
#      - cluster.name=es-oscar-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./docker/dev/volumes/elasticsearch:/usr/share/elasticsearch/data
#    ports:
#      - 9200:9200

    networks:
      - oscar-dev-network
    tty: true
    restart: "always"

  oscar-dev-worker:
    container_name: oscar-dev-worker
    restart: unless-stopped
    volumes:
      - ./:/var/application
    depends_on:
      - oscar-dev-apache
    networks:
      - oscar-dev-network
#    env_file: # TODO
#      - .env.docker.dev
    build:
      context: ./docker/dev/worker
      dockerfile: Dockerfile