########################################################################
# OSCAR DOCKER (Prod)
########################################################################
networks:
  app-dev-network:
    driver: bridge

volumes:
  # Les nodes de elastic sont gérés par Docker en local
  elastic_data:
    driver: local

services:
  ######################################################################
  # POSTGRESQL
  app-dev-postgres:
    container_name: app-dev-postgres
    restart: always
    environment:
      # Accès BDD
      POSTGRES_USER: ${POSGRESQL_USER}
      POSTGRES_PASSWORD: ${POSGRESQL_PASS}
      POSTGRES_DB: ${POSGRESQL_BASE}
    networks:
      - app-dev-network
    env_file:
      - .env
    volumes:
      - ${VOLUMES_POSTGRESQL_DATAS}:/var/lib/postgresql/data
      - ./docker/postgres_initdb.d/:/docker-entrypoint-initdb.d

    build:
      context: ./docker
      dockerfile: postgres_Dockerfile
      args:
        - HTTP_PROXY


  ######################################################################
  ### APACHE
  app-dev-apache:
    container_name: app-dev-apache
    restart: unless-stopped
    volumes:
      - ./:/var/application
    depends_on:
      - app-dev-php
    networks:
      - app-dev-network
    build:
      context: ./docker/
      dockerfile: apache_Dockerfile
      args:
        - HTTP_PROXY
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - "8888:80"


  ######################################################################
  ### GEARMAN
  app-dev-gearman:
    container_name: app-dev-gearman
    image: artefactual/gearmand:1.1.21.2-alpine
    depends_on:
      - app-dev-postgres
    networks:
      - app-dev-network
    tty: true
    restart: "unless-stopped"


  ######################################################################
  ### ELASTICSEARCH
  app-dev-elasticsearch:
    container_name: app-dev-elasticsearch
    image: elasticsearch:7.17.28
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    depends_on:
      - app-dev-postgres
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./docker/es_elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./docker/es_log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties
      - elastic_data:/usr/share/elasticsearch/data
    user: "1000:1000"
    networks:
      - app-dev-network
    tty: true
    restart: "always"

  ######################################################################
  ### WORKER
  app-dev-php:
    container_name: app-dev-php
    restart: unless-stopped
    depends_on:
      - app-dev-worker
    volumes:
      - ./:/var/application
      - ${VOLUMES_DOCUMENTS_ACTIVITY}:/var/documents/activity
      - ${VOLUMES_DOCUMENTS_PUBLIC}:/var/documents/public
      - ${VOLUMES_DOCUMENTS_REQUEST}:/var/documents/request
      - ${VOLUMES_DOCUMENTS_PCRU}:/var/documents/pcru
    networks:
      - app-dev-network
    build:
      context: ./docker/
      dockerfile: app_Dockerfile
      args:
        - HTTP_PROXY


  ######################################################################
  ### WORKER
  app-dev-worker:
    container_name: app-dev-worker
    restart: unless-stopped
    depends_on:
      - app-dev-elasticsearch
    volumes:
      - ./:/var/application
    networks:
      - app-dev-network
    build:
      context: ./docker/
      dockerfile: app_Dockerfile
      args:
        - HTTP_PROXY
    command: ["/bin/bash", "/entrypoint.sh"]

  ######################################################################
  ### VITE
  app-dev-vite:
    container_name: app-dev-vite
    volumes:
      - ./:/var/application
    networks:
      - app-dev-network
    build:
      context: ./docker/dev/vite
      dockerfile: Dockerfile
    ports:
      - "5173:5173"


  ######################################################################
  # KIBANA
  kibana:
    image: docker.elastic.co/kibana/kibana:7.16.1
    container_name: app-dev-kibana
    depends_on:
      - app-dev-elasticsearch
    networks:
      - app-dev-network
    environment:
      - ELASTICSEARCH_HOSTS=http://app-dev-elasticsearch:9200  # Connexion à Elasticsearch
      - LOGGING_ROOT_LEVEL=error
    ports:
      - "5601:5601"


  ######################################################################
  # MAILHOG (capture les mails envoyés depuis Oscar)
  mailhog:
    image: mailhog/mailhog
    container_name: app-dev-mailhog
    networks:
      - app-dev-network
    entrypoint: ["/bin/sh", "-c", "MailHog | grep -v KEEPALIVE"]
    ports:
      - "8025:8025" # Interface web MailHog
      - "1025:1025" # Port SMTP pour envoyer les mails