########################################################################
# OSCAR DOCKER (Développement)
########################################################################
networks:
  oscar-dev-network:
    driver: bridge

services:
  ######################################################################
  # POSTGRESQL
  oscar-dev-postgres:
    container_name: oscar-dev-postgres
    restart: always
    environment:
      # Accès BDD
      POSTGRES_USER: oscar_dev_user
      POSTGRES_PASSWORD: oscar_dev_pass
      POSTGRES_DB: oscar_dev_db

    networks:
      - oscar-dev-network
#    env_file: # TODO
#      - .env.docker.dev
    ports:
      - "6543:5432"
    volumes:
      - ./docker/dev/volumes/databases/oscar_dev_data:/var/lib/postgresql/data
      - ./docker/dev/postgresql/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d
    build:
      context: ./docker/dev/postgresql
      dockerfile: Dockerfile


  ######################################################################
  ### APACHE
  oscar-dev-apache:
    container_name: oscar-dev-apache
    restart: unless-stopped
    volumes:
      - ./:/var/application
    depends_on:
      - oscar-dev-php
    networks:
      - oscar-dev-network
#    env_file: # TODO
#      - .env.docker.dev
    build:
      context: ./docker/dev/apache/
      dockerfile: Dockerfile
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - "8888:80"
#      - "9003:9003"


  ######################################################################
  ### GEARMAN
  oscar-dev-gearman:
    container_name: oscar-dev-gearman
    image: artefactual/gearmand:1.1.21.2-alpine
    depends_on:
      - oscar-dev-postgres
    networks:
      - oscar-dev-network
    tty: true
    restart: "unless-stopped"


  ######################################################################
  ### ELASTICSEARCH
  oscar-dev-elasticsearch:
    container_name: oscar-dev-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.1
    environment:
      - discovery.type=single-node
#      - node.name=oscar01
#      - cluster.name=es-oscar-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    depends_on:
      - oscar-dev-postgres
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./docker/dev/volumes/elasticsearch:/usr/share/elasticsearch/data
    networks:
      - oscar-dev-network
    tty: true
    restart: "always"

  ######################################################################
  ### WORKER
  oscar-dev-php:
    container_name: oscar-dev-php
    restart: unless-stopped
    depends_on:
      - oscar-dev-gearman
    volumes:
      - ./:/var/application
    networks:
      - oscar-dev-network
    build:
      context: ./docker/dev/worker
      dockerfile: Dockerfile


  ######################################################################
  ### WORKER
  oscar-dev-worker:
    container_name: oscar-dev-worker
    restart: unless-stopped
    depends_on:
      - oscar-dev-gearman
    volumes:
      - ./:/var/application
    networks:
      - oscar-dev-network
#    env_file: # TODO
#      - .env.docker.dev
    build:
      context: ./docker/dev/worker
      dockerfile: Dockerfile
    command: ["php", "/var/application/bin/oscar-worker.php"]

  ######################################################################
  ### VITE
  oscar-dev-vite:
    container_name: oscar-dev-vite
    volumes:
      - ./:/var/application
    networks:
      - oscar-dev-network
    build:
      context: ./docker/dev/vite
      dockerfile: Dockerfile
    ports:
      - "5173:5173"


#  ######################################################################
#  # KIBANA
#  kibana:
#    image: docker.elastic.co/kibana/kibana:7.16.1
#    container_name: oscar-dev-kibana
#    depends_on:
#      - oscar-dev-elasticsearch
#    networks:
#      - oscar-dev-network
#    environment:
#      - ELASTICSEARCH_HOSTS=http://oscar-dev-elasticsearch:9200  # Connexion à Elasticsearch
#    ports:
#      - "5601:5601"
#
#
#  ######################################################################
#  # MAILHOG (capture les mails envoyés depuis Oscar)
#  mailhog:
#    image: mailhog/mailhog
#    container_name: oscar-dev-mailhog
#    networks:
#      - oscar-dev-network
#    ports:
#      - "8025:8025" # Interface web MailHog
#      - "1025:1025" # Port SMTP pour envoyer les mails