<?php
$showDelete = isset($showDelete) && $showDelete === true ? true : false;

/** @var \Oscar\Entity\ContractDocument $document */ ?>
<article class="card xs <?= $document->isPrivate() ? 'private-document' : '' ?>" data-openable>
    <div class="card-title">
        <div>
            <?php if( $document->islink() ): ?>
            <i class="picto icon-link-ext"></i>
            <?php else: ?>
            <i class="picto icon-doc doc-<?= $document->getExtension() ?>"></i>
            <?php endif; ?>

            <small class="text-light"><?= $document->getTypeDocument() ?> ~ </small> <br>
            <strong><?= $document->getFileName() ?></strong>
        </div>
        <?php if( !$document->islink() ): ?>
        <small class="text-light">&nbsp;(<?= $this->fileSize($document->getFileSize()) ?>)</small>
        <?php endif; ?>

    </div>
    <div class="card-content">
        <?php if( $document->getProcess() ): ?>
        <div class="cartouche primary">
            <i class="icon-edit"></i>
            Signature : <strong class="addon"><?php echo $document->getProcess()->getStatusText() ?></strong>
        </div>
        <?php endif; ?>
        <p class="text-highlight" style="display: none">
            Fichier <strong><?= $document->getExtension() ?></strong> version <?= $document->getVersion()?>, téléversé le <time><?= $this->moment($document->getDateUpdoad())->full() ?></time>
            par <?= $this->link()->person($document->getPerson()) ?>
        </p>
        <?php if( $document->getGrant() && (isset($showActivity) && $showActivity == true) ): ?>
        <p class="text-highlight">
            Pour l'activité <?= $this->link()->activity($document->getGrant()) ?>
        </p>
        <?php endif; ?>
        <nav class="text-right show-over">
            <?php if( $document->islink() ): ?>
                <a class="btn btn-default btn-xs" href="<?= $document->getPath() ?>" target="_blank">
                    <i class="icon-link-ext"></i>
                    Ouvrir le lien
                </a>
            <?php else: ?>
                <a class="btn btn-default btn-xs" href="<?= $this->url('contractdocument/download',['id' => $document->getId()]) ?>">
                    <i class="icon-download-outline"></i>
                    Télécharger le fichier
                </a>
            <?php endif; ?>

            <?php if($showDelete): ?>
            <a class="btn btn-default btn-xs" data-confirm="Êtes-vous sûr de vouloir supprimer ce document ?" data-href="<?= $this->url('contractdocument/delete',
                ['id' => $document->getId()]) ?>">
                <i class="icon-trash"></i>
                supprimer le fichier
            </a>
            <?php endif; ?>
        </nav>
    </div>
</article>