<div class="container">
    <h1>
        <i class="icon-euro"></i>
        Comptes utilisés
    </h1>
    <div id="ui"></div>
</div>

<div id="ui"></div>
</div>
<script>
    require(['vue', 'vue-resource', 'AccountList'], function(Vue, VueResource, AccountList){
        Vue.use(VueResource);

        Vue.http.options.emulateJSON = true;
        Vue.http.options.emulateHTTP = true;

        new Vue({
            el: "#ui",
            render(h){

                return h(AccountList, {
                    props: {
                        url: '<?= $this->url('administration/accounts') ?>',
                        manage: '<?= $this->url('depense/manage') ?>'
                    }
                });
            }
        })
    })
</script>