<?php
/**
 * Created by PhpStorm.
 * User: bouvry
 * Date: 12/12/18
 * Time: 11:02
 */
?>
<div class="container">
    <header>
        <h1>
            <i class="icon-cog"></i>
            Administration et configuration Oscar
        </h1>
        <div class="infos text-right">
            <strong>Oscar</strong>
            <small><?= \Oscar\OscarVersion::getBuild() ?></small>
        </div>
    </header>

    <section>
        <h2>
            <i class="icon-sliders"></i>
            Paramètres
        </h2>

        <article class="card">
            <h3 class="card-title">
                <strong>
                    <i class="icon-cog"></i>
                    Options
                </strong>
                <?php if( $this->grant()->privilege(\Oscar\Provider\Privileges::MAINTENANCE_PARAMETERS_MANAGE) ): ?>
                    <a href="<?= $this->url('administration/parameters') ?>" class="right"><i class="icon-cog"></i><?= _("Configurer") ?></a>
                <?php else: ?>
                    <em><i class="icon-lock"></i> Privilège insuffisant</em>
                <?php endif; ?>

            </h3>
            <p>Options générales de l'application</p>
        </article>

        <article class="card">
            <h3 class="card-title">
                <strong>
                    <i class="icon-calendar"></i>
                    Feuille de temps
                </strong>
            </h3>
            <ul>
                <li>
                    <strong>Messages de relance</strong>
                    <?php if( $this->grant()->privilege(\Oscar\Provider\Privileges::MAINTENANCE_PARAMETERS_MANAGE) ): ?>
                        <a href="<?= $this->url('administration/messages') ?>" class="right"><i class="icon-cog"></i><?= _("Configurer") ?></a>
                    <?php else: ?>
                        <em><i class="icon-lock"></i> Privilège insuffisant</em>
                    <?php endif; ?>
                </li>
                <li>
                    <strong>Régles de relance</strong>
                    <small>Liste blanche et liste noire</small>
                    <?php if( $this->grant()->privilege(\Oscar\Provider\Privileges::MAINTENANCE_PARAMETERS_MANAGE) ): ?>
                        <a href="<?= $this->url('administration/listdeclarers') ?>" class="right"><i class="icon-cog"></i><?= _("Configurer") ?></a>
                    <?php else: ?>
                        <em><i class="icon-lock"></i> Privilège insuffisant</em>
                    <?php endif; ?>
                </li>
            </ul>
            <p>Messages et formules</p>
        </article>

        <article class="card">
            <h3 class="card-title">
                <strong>
                    <i class="icon-docs"></i>
                    Sections des documents publiques
                </strong>
                <?php if( $this->grant()->privilege(\Oscar\Provider\Privileges::MAINTENANCE_DOCPUBSEC_MANAGE) ): ?>
                    <a href="<?= $this->url('administration/documents-sections') ?>" class="right"><i class="icon-cog"></i><?= _("Configurer") ?></a>
                <?php else: ?>
                    <em><i class="icon-lock"></i> Privilège insuffisant</em>
                <?php endif; ?>
            </h3>
            <p>Configuration des sections de document (documents publiques)</p>
        </article>

        <!--
        <article class="card">
            <h3 class="card-title">
                <strong>
                    <i class="icon-calendar"></i> Feuille de temps
                </strong>
            </h3>
            <p>Configuration des sections de document (documents publiques)</p>
            <ul>
                <li>Configurer les messages de relance</li>
                <li>Configurer la tolérance horaire</li>
                <li>Configurer le mode de déclaration</li>
            </ul>
        </article>
        -->

        <h2>
            <i class="icon-tags"></i>
            Nomenclatures
        </h2>
        <article class="card">
            <h3 class="card-title">
                <strong>
                    <i class="icon-cube"></i>
                    Type d'activité
                </strong>
                <?php if( $this->grant()->privilege(\Oscar\Provider\Privileges::MAINTENANCE_ACTIVITYTYPE_MANAGE) ): ?>
                    <a href="<?= $this->url('activitytype') ?>" class="right"><i class="icon-cog"></i><?= _("Configurer") ?></a>
                <?php else: ?>
                    <em><i class="icon-lock"></i> Privilège insuffisant</em>
                <?php endif; ?>
            </h3>
            <p>Correpond (généralement) au <strong>type de contrat/convention</strong></p>
        </article>

        <article class="card">
            <h3 class="card-title">
                <strong>
                    <i class="icon-calendar"></i>
                    Type de jalon
                </strong>
                <?php if( $this->grant()->privilege(\Oscar\Provider\Privileges::MAINTENANCE_MILESTONETYPE_MANAGE) ): ?>
                    <a href="<?= $this->url('datetype') ?>" class="right"><i class="icon-cog"></i><?= _("Configurer") ?></a>
                <?php else: ?>
                    <em><i class="icon-lock"></i> Privilège insuffisant</em>
                <?php endif; ?>
            </h3>
            <p>Permet de gérer les jalons disponibles dans les activités de recherche ainsi que leur comportement : système de validation, fréquence des rappels</p>
        </article>

        <article class="card">
            <h3 class="card-title">
                <strong>
                    <i class="icon-euro"></i>
                    TVA
                </strong>
                <?php if( $this->grant()->privilege(\Oscar\Provider\Privileges::MAINTENANCE_TVA_MANAGE) ): ?>
                    <a href="<?= $this->url('administration/tva') ?>" class="right"><i class="icon-cog"></i><?= _("Configurer") ?></a>
                <?php else: ?>
                    <em><i class="icon-lock"></i> Privilège insuffisant</em>
                <?php endif; ?>
            </h3>
            <p>Permet de configurer les TVAs disponibles.</p>
        </article>

        <article class="card">
            <h3 class="card-title">
                <strong>
                    <i class="icon-docs"></i>
                    Type de document
                </strong>
                <?php if( $this->grant()->privilege(\Oscar\Provider\Privileges::MAINTENANCE_DOCUMENTTYPE_MANAGE) ): ?>
                    <a href="<?= $this->url('administration/typedocument') ?>" class="right"><i class="icon-cog"></i><?= _("Configurer") ?></a>
                <?php else: ?>
                    <em><i class="icon-lock"></i> Privilège insuffisant</em>
                <?php endif; ?>
            </h3>
            <p>Permet de gérer les types de document disponibles dans les activités de recherche lors du dépôt d'un document.</p>
        </article>

        <article class="card">
            <h3 class="card-title">
                <strong>
                    <i class="icon-building-filled"></i>
                    Type d'organisation
                </strong>
                <?php if( $this->grant()->privilege(\Oscar\Provider\Privileges::MAINTENANCE_ORGANIZATIONTYPE_MANAGE) ): ?>
                    <a href="<?= $this->url('administration/organizationtype') ?>" class="right"><i class="icon-cog"></i><?= _("Configurer") ?></a>
                <?php else: ?>
                    <em><i class="icon-lock"></i> Privilège insuffisant</em>
                <?php endif; ?>
            </h3>
            <p>Permet de gérer les types d'organisation proposés pour qualifier une organisation.</p>
        </article>

        <article class="card">
            <h3 class="card-title">
                <strong>
                    <i class="icon-tags"></i>
                    Disciplines
                </strong>
                <?php if( $this->grant()->privilege(\Oscar\Provider\Privileges::MAINTENANCE_DISCIPLINE_MANAGE) ): ?>
                    <a href="<?= $this->url('administration/discipline') ?>" class="right"><i class="icon-cog"></i><?= _("Configurer") ?></a>
                <?php else: ?>
                    <em><i class="icon-lock"></i> Privilège insuffisant</em>
                <?php endif; ?>
            </h3>
            <p>Permet de gérer les disciplines disponibles.</p>
        </article>

        <article class="card">
            <h3 class="card-title">
                <strong>
                    <i class="icon-tags"></i>
                    Numérotation
                </strong>
                <?php if( $this->grant()->privilege(\Oscar\Provider\Privileges::MAINTENANCE_NUMEROTATION_MANAGE) ): ?>
                    <a href="<?= $this->url('administration/numerotation') ?>" class="right"><i class="icon-cog"></i><?= _("Configurer") ?></a>
                <?php else: ?>
                    <em><i class="icon-lock"></i> Privilège insuffisant</em>
                <?php endif; ?>
            </h3>
            <p>Permet de gérer les numérotations disponibles dans l'écran d'édition des activités.</p>
        </article>

        <article class="card">
            <h3 class="card-title">
                <strong>
                    <i class="icon-euro"></i>
                    Type de dépense
                </strong>
                <?php if( $this->grant()->privilege(\Oscar\Provider\Privileges::MAINTENANCE_SPENDTYPEGROUP_MANAGE) ): ?>
                    <a href="<?= $this->url('depense/manage') ?>" class="right"><i class="icon-cog"></i><?= _("Configurer") ?></a>
                <?php else: ?>
                    <em><i class="icon-lock"></i> Privilège insuffisant</em>
                <?php endif; ?>
            </h3>
            <p>Gestion des types de dépense.</p>
        </article>

        <article class="card">
            <h3 class="card-title">
                <strong>
                    <i class="icon-flag"></i>
                    Pays (ISO 3166)
                </strong>
                <?php if( $this->grant()->privilege(\Oscar\Provider\Privileges::MAINTENANCE_ACTIVITYTYPE_MANAGE) ): ?>
                    <a href="<?= $this->url('administration/countries') ?>" class="right"><i class="icon-cog"></i><?= _("Voir") ?></a>
                <?php else: ?>
                    <em><i class="icon-lock"></i> Privilège insuffisant</em>
                <?php endif; ?>
            </h3>
            <div class="alert alert-info">
                Charger les informations depuis le référentiel :
                <form action="<?= $this->url('administration/countries') ?>" method="post">
                    <button type="submit" name="action" value="update-countries-3166" class="btn btn-default">Actualiser les pays</button>
                </form>
            </div>
            <p>Référenciel des pays proposés dans la fiche organisation</p>
        </article>

    </section>

    <section>
        <h2><i class="icon-stethoscope"></i>
            Maintenance</h2>

        <article class="card xs">
            <h3 class="card-title">
                <strong>
                    <i class="icon-signal"></i>
                    Status : OSCARWORKER</strong>
                <?php if( $this->grant()->privilege(\Oscar\Provider\Privileges::MAINTENANCE_MENU_ADMIN) ):?>
                    <a href="<?= $this->url('administration/oscarworker') ?>" class="right">
                        <i class="icon-cog"></i>
                        <?= $this->translate("Afficher") ?>
                    </a>
                <?php else: ?>
                    <small><i class="icon-lock"></i> Privilège insuffisant</small>
                <?php endif; ?>
            </h3>
            <p>Affichage des <strong>logs</strong> du <em>OscarWorker</em>.</p>
        </article>

        <article class="card xs">
            <h3 class="card-title">
                <strong>
                    <i class="icon-building-filled"></i>
                    Fusion des organisations</strong>
                <?php if( $this->grant()->privilege(\Oscar\Provider\Privileges::ORGANIZATION_EDIT) ):?>
                    <a href="<?= $this->url('organization/fusion') ?>" class="right">
                        <i class="icon-cog"></i>
                        <?= $this->translate("Afficher") ?>
                    </a>
                <?php else: ?>
                    <small><i class="icon-lock"></i> Privilège insuffisant</small>
                <?php endif; ?>
            </h3>
            <p>Procédure de fusion des organisations</p>
        </article>

        <article class="card xs">
            <h3 class="card-title">
                <strong>
                    <i class="icon-building-filled"></i>
                    Scission des organisations</strong>
                <?php if( $this->grant()->privilege(\Oscar\Provider\Privileges::ORGANIZATION_EDIT) ):?>
                    <a href="<?= $this->url('organization/scission') ?>" class="right">
                        <i class="icon-cog"></i>
                        <?= $this->translate("Afficher") ?>
                    </a>
                <?php else: ?>
                    <small><i class="icon-lock"></i> Privilège insuffisant</small>
                <?php endif; ?>
            </h3>
            <p>Procédure de scission des organisations</p>
        </article>

        <article class="card xs">
            <h3 class="card-title">
                <strong>
                    <i class="icon-cubes"></i>
                    Afficher les projets vides</strong>
                <?php if( $this->grant()->privilege(\Oscar\Provider\Privileges::PROJECT_INDEX) ):?>
                    <a href="<?= $this->url('project/empty') ?>" class="right">
                        <i class="icon-cog"></i>
                        <?= $this->translate("Afficher") ?>
                    </a>
                <?php else: ?>
                    <small><i class="icon-lock"></i> Privilège insuffisant</small>
                <?php endif; ?>
            </h3>
            <p>Permet des gérer les projets vides pour éventuellement les supprimer</p>
        </article>

        <article class="card xs">
            <h3 class="card-title">
                <strong>
                    <i class="icon-calendar"></i>
                    Gestion des déclarations</strong>
                <?php if( $this->grant()->privilege(\Oscar\Provider\Privileges::MAINTENANCE_VALIDATION_MANAGE) ):?>
                    <a href="<?= $this->url('timesheet/declarations') ?>" class="right">
                        <i class="icon-cog"></i>
                        <?= $this->translate("Afficher") ?>
                    </a>
                <?php else: ?>
                    <em class="right"><i class="icon-lock"></i> Privilège insuffisant</em>
                <?php endif; ?>
            </h3>
            <p>Cette interface permet de visualiser les déclarations et leur état. Elle permet également de <strong>gérer les validateurs</strong> et de <strong>modifier la répartition horaire du déclarant</strong> en cas de problème. Enfin, elle permet d'annuler un procédure de validation.</p>
        </article>

        <article class="card xs">
            <h3 class="card-title">
                <strong>
                    <i class="icon-docs"></i>
                    Gestion des documents téléversés</strong>
                <?php if( $this->grant()->privilege(\Oscar\Provider\Privileges::ACTIVITY_DOCUMENT_MANAGE) ):?>
                    <a href="<?= $this->url('contractdocument') ?>" class="right">
                        <i class="icon-cog"></i>
                        <?= $this->translate("Afficher") ?>
                    </a>
                <?php else: ?>
                    <em class="right"><i class="icon-lock"></i> Privilège insuffisant</em>
                <?php endif; ?>
            </h3>
            <p>Liste des documents téléversés dans les activités de recherche.</p>
        </article>

        <article class="card xs">
            <h3 class="card-title">
                <strong>
                    <i class="icon-plug"></i>
                    Synchronisation des données (connectors)</strong>
                <?php if( $this->grant()->privilege(\Oscar\Provider\Privileges::MAINTENANCE_CONNECTOR_ACCESS) ):?>
                    <a href="<?= $this->url('administration/connectors_home') ?>" class="right">
                        <i class="icon-cog"></i>
                        <?= $this->translate("Afficher") ?>
                    </a>
                <?php else: ?>
                    <em class="right"><i class="icon-lock"></i> Privilège insuffisant</em>
                <?php endif; ?>
            </h3>
            <p>
                Affiche la liste des connecteurs configurés dans <?= _('OScar') ?> pour vérifier s'ils sont bien configurés. Permet également de les éxécuter manuellement depuis l'interface.
            </p>
        </article>

        <article class="card">
            <h3 class="card-title">
                <strong>
                    <i class="icon-cw-outline"></i>
                    Reconstruire l'index de recherche des activités</strong>
                <?php if( $this->grant()->privilege(\Oscar\Provider\Privileges::MAINTENANCE_SEARCH_BUILD) ):?>
                    <a href="<?= $this->url('administration/activity_index') ?>" class="right">
                        <i class="icon-cog"></i>
                        <?= $this->translate("Exécuter") ?>
                    </a>
                <?php else: ?>
                    <em class="right"><i class="icon-lock"></i> Privilège insuffisant</em>
                <?php endif; ?>
            </h3>
            <p>
                Lance le reconstruction de l'index de recherche depuis l'interface
            </p>
            <p class="alert-warning alert">
                Cette opération est coûteuse en ressource et peut dépasser la durée d'execution autorisée. Il est préférable de réaliser cette opération de amintenance depuis l'utilitaire en ligne de commande :
                <br>$ <code>php bin/oscar.php activity:search-build</code>
            </p>
        </article>

        <h2>
            <i class="icon-puzzle"></i>
            Modules
        </h2>
        <article class="card">
            <h3 class="card-title">
                <strong>
                    <i class="icon-beaker"></i>
                    PCRU
                </strong>
                <?php if( $this->grant()->privilege(\Oscar\Provider\Privileges::MAINTENANCE_PARAMETERS_MANAGE) ): ?>
                    <a href="<?= $this->url('administration/pcru') ?>" class="right"><i class="icon-cog"></i><?= _("Configurer") ?></a>
                <?php else: ?>
                    <em><i class="icon-lock"></i> Privilège insuffisant</em>
                <?php endif; ?>
            </h3>
            <p>Le modules PCRU permet de configurer l'envois automatique des contrats signés au système <strong>PCRU du CNRS</strong></p>
            <hr>
            <h4 style="font-weight: bold">Référentiels PCRU</h4>
            <div class="alert alert-info">
            <p>Les référentiels ci-dessous sont <strong>obligatoires</strong> si vous utilisez PCRU, mais rien ne vous empèche de les utiliser dans la qualification des activités pour compléter les informations.</p>
            <p>Vous pouvez actualiser les référentiels en cliquant ici <a href="?action=pcru-referentiel-update" class="btn btn-success">Mettre à jour les référentiels</a></p>

            </div>
            <ul>
                <li>
                    <strong>
                        <i class="icon-tags"></i>
                        Correspondance des types de contrat
                    </strong>
                    <?php if( $this->grant()->privilege(\Oscar\Provider\Privileges::MAINTENANCE_PARAMETERS_MANAGE) ): ?>
                        <a href="<?= $this->url('administration/contrat-type-pcru') ?>" class="right"><i class="icon-cog"></i><?= _("Configurer") ?></a>
                    <?php else: ?>
                        <em><i class="icon-lock"></i> Privilège insuffisant</em>
                    <?php endif; ?>
                    <br><small>Correspondance entre les types d'activités Oscar et les types de contrat PCRU</small>
                </li>
                <li>
                    <strong>
                        <i class="icon-tags"></i>
                    Référenciel des pôles de compétitivité :
                    </strong>
                    <?php if( $this->grant()->privilege(\Oscar\Provider\Privileges::MAINTENANCE_SPENDTYPEGROUP_MANAGE) ): ?>
                        <a href="<?= $this->url('administration/poles-competitivite') ?>" class="right"><i class="icon-cog"></i><?= _("Voir") ?></a>
                    <?php else: ?>
                        <em><i class="icon-lock"></i> Privilège insuffisant</em>
                    <?php endif; ?>
                    <br>
                    <small>La liste des pôles de compétitivité est utilisée dans la fiche activité, elle est fournit par le CNRS.</small>
                </li>

                <li>
                    <strong>
                        <i class="icon-tags"></i>
                        Référenciel des sources de financement
                    </strong>
                    <?php if( $this->grant()->privilege(\Oscar\Provider\Privileges::MAINTENANCE_SPENDTYPEGROUP_MANAGE) ): ?>
                        <a href="<?= $this->url('administration/sources-financement') ?>" class="right"><i class="icon-cog"></i><?= _("Voir") ?></a>
                    <?php else: ?>
                        <em><i class="icon-lock"></i> Privilège insuffisant</em>
                    <?php endif; ?>
                    <br>
                    <small>La liste des sources de financement est utilisée dans la fiche activité, elle est fournit par le CNRS.</small>
                </li>
            </ul>
        </article>

        <h2>
            <i class="icon-lock"></i>
            Privilèges et droits d'accès
        </h2>

        <article class="card">
            <h3 class="card-title">
                <strong>
                    <i class="icon-group"></i>
                    Privilèges et rôles</strong>
                <?php if( $this->grant()->privilege(\Oscar\Provider\Privileges::DROIT_PRIVILEGE_VISUALISATION) ):?>
                    <a href="<?= $this->url('administration') ?>" class="right">
                        <i class="icon-cog"></i>
                        <?= $this->translate("Afficher") ?>
                    </a>
                <?php else: ?>
                    <em class="right"><i class="icon-lock"></i> Privilège insuffisant</em>
                <?php endif; ?>
            </h3>
            <p>
                Gestion des <strong>rôles</strong> des personnes et des <strong>privilèges</strong> accordés à ces rôles
            </p>
        </article>

        <article class="card">
            <h3 class="card-title">
                <strong>
                    <i class="icon-plug"></i>
                    Authentifications</strong>
                <?php if( $this->grant()->privilege(\Oscar\Provider\Privileges::DROIT_PRIVILEGE_VISUALISATION) ):?>
                    <a href="<?= $this->url('administration/users') ?>" class="right">
                        <i class="icon-cog"></i>
                        <?= $this->translate("Afficher") ?>
                    </a>
                <?php else: ?>
                    <em class="right"><i class="icon-lock"></i> Privilège insuffisant</em>
                <?php endif; ?>
            </h3>
            <p>
                Visualisation des authentifications actives. Permet également d'accorder des <strong>rôles applicatifs particulier</strong>
            </p>
        </article>

        <article class="card">
            <h3 class="card-title">
                <strong>
                    <i class="icon-building-filled"></i>
                    Rôles des organisations</strong>
                <?php if( $this->grant()->privilege(\Oscar\Provider\Privileges::DROIT_PRIVILEGE_VISUALISATION) ):?>
                    <a href="<?= $this->url('administration/organizationrole') ?>" class="right">
                        <i class="icon-cog"></i>
                        <?= $this->translate("Afficher") ?>
                    </a>
                <?php else: ?>
                    <em class="right"><i class="icon-lock"></i> Privilège insuffisant</em>
                <?php endif; ?>
            </h3>
            <p>
                Gestion des rôles disponibles lors de l'association d'un organisation à une activité de recherche.
            </p>
        </article>
        <article class="card">
            <h3 class="card-title">
                <strong>
                    <i class="icon-database"></i>
                    Accès à l'API</strong>
                <?php if( $this->grant()->privilege(\Oscar\Provider\Privileges::DROIT_API_ACCESS) ):?>
                    <a href="<?= $this->url('api/manage-acces') ?>" class="right">
                        <i class="icon-cog"></i>
                        <?= $this->translate("Afficher") ?>
                    </a>
                <?php else: ?>
                    <em class="right"><i class="icon-lock"></i> Privilège insuffisant</em>
                <?php endif; ?>
            </h3>
            <p>
                Vous permet de créer des accès distants aux donnnées (Personnes)
            </p>
        </article>
    </section>
</div>
