<section class="container">
    <nav>
        <a href="<?= $this->url('administration/connectors_home') ?>">Retour à la liste des connecteurs</a>
    </nav>
    <h1>Rapport d'exécution du connecteur : <strong><?= $connectorType ?>/<?= $connectorName ?></strong></h1>
    <?php foreach( $repport as $type=>$data ): ?>
    <section>
        <h1>
            <i class="icon-<?= $type ?>"></i>
            <?= $type ?> <sup>(<?= count($data) ?>)</sup>
        </h1>
        <?php foreach( $data as $message ): ?>
        <article class="card xsc repport repport-<?= $type ?>">
            <i class="icon-repport"></i> <?= $message ?>
        </article>
        <?php endforeach; ?>
    </section>
    <?php endforeach; ?>
</section>

