<div class="container">
    <div id="contrattypepcru"></div>
    <nav>
        <a class="btn btn-info" href="?action=update">
            <i class="icon-cw-outline"></i>
            Actualiser depuis le référenciel CNRS
        </a>
    </nav>
    <script>
        require(['vue', 'vue-resource', 'contrattypepcru'], function(Vue, VueResource,ContratTypePCRU){
            new Vue({
                render(h) {
                    return h(ContratTypePCRU, { "props": { "url": "<?php echo $this->url('administration/contrat-type-pcru') ?>?datas=1"}})
                }
            }).$mount('#contrattypepcru')
        })
    </script>
</div>