<link rel="stylesheet" href="<?= $this->basePath(). '/css/privileges.css' ?>">
<div class="container">
    <div class="col-md-8">
        <h1><i class="icon-shield"></i>Gestion des privilèges</h1>
        <div id="privileges"></div>
    </div>
    <div class="col-md-4">
        <h1><i class="icon-group"></i>Rôles</h1>
        <div id="roles"></div>
        <script>
            require(['vue', 'vue-resource', 'privileges', 'rolesadminui', 'bootbox'], function(Vue, VueResource, Privilege, RolesAdminUI, Bootbox){
                Vue.use(VueResource);

                var privileges = new Privilege.default({
                    http: {
                        root: '<?= $this->url('administration/privileges') ?>'
                    },
                    el: '#privileges'
                });

                var rolesView = new Vue({
                    el: "#roles",
                    render: function(h){
                        return h(RolesAdminUI.default, { props: {
                            Bootbox: Bootbox,
                            privilegesDatas: privileges.$data,
                            url: '<?= $this->url('administration/roles') ?>'
                            }});
                    }
                });
            })
        </script>
    </div>

</div>