<section class="container">
    <h1><i class="icon-user-md"></i>Logs</h1>

    <pre id="logs">

    </pre>

    <script>
        require(['vue', 'vue-resource'], function(Vue, VueResource){
            Vue.use(VueResource);
            var interval;
            new Vue({
                el: "#logs",
                data: {
                    logs: "Pas de logs...",
                    file: "Pas de fichier",
                    level: "INCONNU",
                    limits: 25,
                    refresh: 5,
                    loading: false
                },
                template: `
                  <div class="logger terminal" :class="{'loading': loading}">
                    <div class="terminal-header">
                      <em>Mise à jour toute les <strong>{{refresh}} secondes</strong>
                        des <strong>{{limits}} dernières entrées</strong><br>
                        <em>Fichier de log : <strong>{{file}}</strong>)</em><br>
                        <em>Niveau de log : <strong>{{level}}</strong></em>
                    </div>
                    <pre class="terminal-content">{{ logs }}</pre>
                  </div>`,
                methods: {
                    loadLastLogs(){
                        this.loading = true;
                        this.$http.get('').then(
                            ok => {
                                console.log(ok);
                                this.logs = ok.body.logs;
                                this.level = ok.body.log_level;
                                this.limits = ok.body.limits;
                                this.file = ok.body.file;
                            },
                            ko => {
                                this.logs = "Impossible de connaitre l'état de OscarWorker : " + ko.body;
                            }
                        ).then(()=>{
                            this.loading = false;
                        });
                    }
                },
                mounted(){
                    this.loadLastLogs();
                    var self = this;
                    interval = setInterval(()=> {
                        self.loadLastLogs()
                    }, this.refresh*1000);
                }
            })
        })
    </script>
</section>
