<div class="container">
    <h1>Messages de relance</h1>
    <div class="row">
        <div class="col-md-4">
            <form action="" method="post">
                <h3><i class="icon-calendar"></i> Déclarants, Première relance</h3>
                <input type="hidden" name="messageName" value="declarersRelance1" />
                <textarea name="messageValue" id="" cols="30" rows="10" class="form-control"><?= $declarersRelance1 ?></textarea>
                <button type="submit" class="btn btn-primary">
                    Enregistrer
                </button>
            </form>
        </div>
        <div class="col-md-4">
            <form action="" method="post">
                <h3><i class="icon-calendar"></i> Déclarant, Deuxième relance</h3>
                <input type="hidden" name="messageName" value="declarersRelance2" />
                <textarea name="messageValue" id="" cols="30" rows="10" class="form-control"><?= $declarersRelance2 ?></textarea>
                <button type="submit" class="btn btn-primary">
                    Enregistrer
                </button>
            </form>
        </div>
    </div>

</div>