<section class="container">
    <h1>
        <i class="icon-building-filled"></i>
        Gestion des types d'oganisation
    </h1>
    <div id="admintypeorganization"
         data-url="<?= $this->url('administration/organizationtype') ?>"
         data-manage="true"
    ></div>
    <?php echo $this->Vite()->addJs('src/AdminTypeOrganization.js') ?>
</section>
<script>
    /****
    require(["vue", "vue-resource", 'OrganizationType'], function(Vue, VueResource, OrganizationType){
        Vue.use(VueResource);
        Vue.http.options.emulateJSON = true;
        Vue.http.options.emulateHTTP = true;

        new Vue({
            render(h){
                return h(OrganizationType.default, {
                       props: {
                           creatable: true,
                           url: '<?= $this->url('administration/organizationtype') ?>'
                       }
                    }
                )
            }
       }).$mount('#app')
    });
    /****/
</script>