<?php
/**
 * Created by PhpStorm.
 * User: bouvry
 * Date: 12/12/18
 * Time: 11:02
 */

?>
<div class="container">
    <header>
        <h1>
            <i class="icon-cog"></i>
            Options et paramètres Oscar
        </h1>
    </header>

    <section class="row">
        <div class="col-md-6">
            <article class="card <?= $allow_numerotation_custom == true ? 'activated' : 'disabled' ?>">
                <h3><i class="icon-tags"></i>Numérotation des activités</h3>
                <p class="help-message">
                    <i class="icon-help-circled"></i>
                    En <strong>activant</strong> cette option, vous autorisez les personnes en charge de l'ajout/modification des activités d'ajouter des types de numérotation non-référencées dans la liste des numérotations disponibles.
                </p>
                <form action="" method="post" class="form">
                    <div class="row">
                        <div class="col-md-7 col-md-push-1">
                            <strong>type de numérotation personnalisable</strong>
                        </div>
                        <div class="col-md-4">
                            <div class="material-switch">
                                <input name="parameter_name" type="hidden" value="allow_numerotation_custom" />
                                <input id="allow_numerotation_custom" name="parameter_value" type="checkbox" <?= $allow_numerotation_custom ? "checked" : "" ?> />
                                <label for="allow_numerotation_custom" class="label-primary"></label>
                            </div>
                        </div>
                    </div>

                    <button class="btn btn-primary"><i class="icon-floppy"></i> Enregistrer</button>
                </form>
            </article>
        </div>

        <div class="col-md-6">
            <h2><i class="icon-cube"></i><?= $this->translate("Demande d'activité") ?></h2>
            <article class="card">
                <h3><i class="icon-calculator"></i> Limiter le nombre de demande</h3>
                <p class="help-message">La valeur <strong>-1</strong> permet de ne pas limiter le nombre de demande.</p>
                <form action="" method="post" class="form">
                    <div class="row">
                        <div class="col-md-7 col-md-push-1">
                            <strong>Nombre de demande maximum</strong>
                        </div>
                        <div class="col-md-4">
                            <div class="material-switch">
                                <input name="parameter_name" type="hidden" value="activity_request_limit" />
                                <input type="number" name="parameter_value" value="<?= $activity_request_limit ?>" id="" />
                            </div>
                        </div>
                    </div>

                    <button class="btn btn-primary"><i class="icon-floppy"></i> Enregistrer</button>
                </form>
            </article>


            <h2><i class="icon-tags"></i>Apparence</h2>
            <article class="card">
                <h3><i class="icon-pencil-1"></i>Thème</h3>
                <form action="" method="post" class="form">
                    <div class="row">
                        <div class="col-md-7 col-md-push-1">
                            <strong>Thème</strong>
                        </div>
                        <div class="col-md-4">
                            <div class="material-switch">
                                <input name="parameter_name" type="hidden" value="theme" />
                                <select name="parameter_value" id="">
                                    <?php foreach ($themes as $t): ?>
                                    <option value="<?= $t ?>" <?= $t == $theme ? 'selected' : '' ?>><?= $t ?></option>
                                    <?php endforeach; ?>
                                </select>
                            </div>
                        </div>
                    </div>

                    <button class="btn btn-primary"><i class="icon-floppy"></i> Enregistrer</button>
                </form>
            </article>
        </div>
    </section>

    <section class="row">
        <div class="col-md-6">
            <article class="card">
                <h3><i class="icon-upload"></i> Format d'exportation</h3>
                <p class="help-message">
                    <i class="icon-help-circled"></i>
                    Permet de configurer le format des données lors de l'exporation des activités de recherche.
                </p>
                <form action="" method="post" class="form">
                    <input name="parameter_name" type="hidden" value="export_options" />
                    <label for="separator">Séparateur de chaîne</label>
                    <input type="text" name="separator" id="separator" value="<?= $export['separator'] ?>" class="form-control input-lg" />

                    <label for="dateformat">Format des dates</label>
                    <input type="text" name="dateformat" id="dateformat" value="<?= $export['dateformat'] ?>" class="form-control input-lg" />
                    <hr>
                    <button class="btn btn-primary"><i class="icon-floppy"></i> Enregistrer</button>
                </form>
            </article>


            <article class="card">
                <h3><i class="icon-building-filled"></i> rôle des organisations</h3>

                <form action="" method="post">
                    <p>Lorsque une personne responsable de structure crée une activité, voici l'attribution des organisations en fonction des rôles.</p>
                    <?php foreach ($organization_leader_role['rolesInOrganization'] as $roleIn):?>
                    <div class="card cols" style="display: flex">
                        <div class="col-3">
                            Si elle est <strong class="cartouche primary"><?= $roleIn ?></strong>, l'organisation aura le rôle
                        </div>
                        <div class="col-1">
                            <select name="role_organization[<?= $roleIn ?>]" id="" class="select2">
                                <option value="">Laisser choisir le rôle</option>
                                <?php foreach ($organization_leader_role['roleOrganizationPrincipal'] as $roleOrganisation) :?>
                                <option value="<?= $roleOrganisation ?>" <?= (array_key_exists($roleIn, $organization_leader_role['config']) && $organization_leader_role['config'][$roleIn] == $roleOrganisation) ? " SELECTED" : "" ?>><?= $roleOrganisation ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                    <?php endforeach; ?>
                    <hr>
                    <input name="parameter_name" type="hidden" value="organization_leader_role" />
                    <button class="btn btn-primary"><i class="icon-floppy"></i> Enregistrer</button>
                </form>
                <pre>

    </pre>
            </article>
        </div>

        <div class="col-md-6">
            <h2><i class="icon-calendar"></i>Feuilles de temps</h2>

            &nbsp;<article class="card">
                <h3><i class="icon-eye"></i>Aperçu</h3>
                <p class="help-message">
                    <i class="icon-help-circled"></i>
                    En <strong>activant</strong> cette option, vous autorisez les personnes à télécharger des feuilles de temps avant qu'elles n'aient été validées numériquement.
                </p>
                <form action="" method="post" class="form">
                    <div class="row">
                        <div class="col-md-7 col-md-push-1">
                            <strong>Activer l'aperçu</strong><br>
                        </div>
                        <div class="col-md-4">
                            <div class="material-switch">
                                <input name="parameter_name" type="hidden" value="timesheet_preview" />
                                <input id="timesheet_preview_custom" name="parameter_value" type="checkbox" <?= $timesheet_preview ? "checked" : "" ?> />
                                <label for="timesheet_preview_custom" class="label-primary"></label>
                            </div>
                        </div>
                    </div>

                    <button class="btn btn-primary"><i class="icon-floppy"></i> Enregistrer</button>
                </form>
            </article>

            <article class="card">
                <h3><i class="icon-file-excel"></i>Format Excel</h3>
                <p class="help-message">
                    <i class="icon-help-circled"></i>
                    En <strong>activant</strong> cette option, vous donnez l'accès à une version excel des feuilles de temps.
                </p>
                <form action="" method="post" class="form">
                    <div class="row">
                        <div class="col-md-7 col-md-push-1">
                            <strong>Version excel</strong><br>
                        </div>
                        <div class="col-md-4">
                            <div class="material-switch">
                                <input name="parameter_name" type="hidden" value="timesheet_excel" />
                                <input id="timesheet_excel_custom" name="parameter_value" type="checkbox" <?= $timesheet_excel ? "checked" : "" ?> />
                                <label for="timesheet_excel_custom" class="label-primary"></label>
                            </div>
                        </div>
                    </div>

                    <button class="btn btn-primary"><i class="icon-floppy"></i> Enregistrer</button>
                </form>
            </article>

            <h2><i class="icon-sort"></i>Dépense : Comptes filtrés</h2>

            &nbsp;<article class="card">
                <h3><i class="icon-eye"></i>Aperçu</h3>
                <p class="help-message">
                    <i class="icon-help-circled"></i>
                    Cette option va exclure les <strong>dépenses</strong> appartenant à un des comptes renseigné (séparé les comptes par une virgule).
                </p>
                <form action="" method="post" class="form">
                    <label for="<?= \Oscar\Service\OscarConfigurationService::spents_account_filter  ?>">Comptes</label>
                    <input name="parameter_name" type="hidden" value="<?= \Oscar\Service\OscarConfigurationService::spents_account_filter ?>" />
                    <input type="text" name="<?= \Oscar\Service\OscarConfigurationService::spents_account_filter ?>"
                           name="<?= \Oscar\Service\OscarConfigurationService::spents_account_filter ?>"
                           id="<?= \Oscar\Service\OscarConfigurationService::spents_account_filter ?>"
                           value="<?= $spents_account_filter ?>" class="form-control input-lg" />
                    <button class="btn btn-primary"><i class="icon-floppy"></i> Enregistrer</button>
                </form>
            </article>
        </div>
    </section>
</div>
