<div class="container">
    <h1>
        <i class="icon-tags"></i>
        Référenciel des <strong>Pôles de compétitivité</strong>
    </h1>

    <div class="alert alert-danger">
        Le référenciel établissant la liste des pôles de compétitivité est fournit par le CNRS,
        en le modifiant, vous prenez le risque de voir vos soumissions de contrat à PCRU rejeté.
    </div>

    <div id="pc"></div>

    <script>
        require(['vue', 'administrationpcrupc'], function(Vue, AdministrationPcruPC){
            new Vue({
                el: "#pc",
                render(h){
                    return h(AdministrationPcruPC, {props:{
                        url: '<?= $this->url('api/referenciel-pcru-polecompetitivite') ?>',
                        urlManage: '<?= $this->url('administration/poles-competitivite') ?>'
                    }});
                }
            })
        })
    </script>
</div>