<link rel="stylesheet" href="<?= $this->basePath(). '/css/privileges.css' ?>">
<div class="container">
    <h1>
        <i class="icon-building-filled"></i>
        Liste des types de documents :
    </h1>
        <section>
            <div id="types"></div>
            <script>
                require(['vue', 'vue-resource', 'bootbox', 'TypeDocument'],function(Vue, VueRessource, Bootbox, TypeDocument){
                    Vue.use(VueRessource);
                    Vue.http.options.emulateJSON = true;
                    Vue.http.options.emulateHTTP = true;
                    new Vue({
                        el: '#types',
                        render(h){
                            return h(TypeDocument.default, { props: {url: '<?= $this->url('administration/typedocument/api') ?>', manage: true, bootbox: Bootbox}})
                        }
                    })
                })
            </script>
</section>
</div>
