<section class="container">
    <div id="app"></div>
</section>
<script>
    require(['vue', 'vue-resource', 'TimesheetDeclarationsList', 'bootbox', 'mm'], function (Vue, VueResource, TimesheetDeclarationsList, Bootbox, moment) {
        Vue.use(VueResource);
        Vue.filter('humandate', function(str){
           return moment(str).format('dddd D MMMM YYYY');
        });
        new Vue({
            render: function(h){
                return h(TimesheetDeclarationsList.default, { props: {
                        bootbox: Bootbox,
                        moment: moment,
                        editable: true
                    }});
            }
        }).$mount('#app')
    });
</script>