<section class="container">
    <div id="declarers"></div>
</section>

<script>
require(['vue', 'vue-resource', 'mm', 'DeclarersList'], function(Vue, VueResource, moment, DeclarersList) {
    Vue.use(VueResource);
    Vue.filter('month', function(v){
        return moment(v).format('MMMM YYYY');
    });
    new Vue({
        el: '#declarers',
        render(h){
            return h(DeclarersList.default, { props: {
                    urlRecallDeclarer: '<?= $this->url('timesheet/recall-declarer') ?>'
                } });
        }
    })

});
</script>