<div class="container">
    <div id="app"></div>
</div>
<script>
    require(['vue', 'vue-resource', 'TimesheetMonth', 'mm'], function(Vue, VueResource, TimesheetMonth, moment){
        Vue.use(VueResource);

        new Vue({
            render: function(h){
                return h(TimesheetMonth.default, { props: {
                  year: 2017,
                  month: 12,
                  moment: moment
                }});
            }
        }).$mount('#app');
    })
</script>