<link rel="stylesheet" href="/js/oscar/dist/timesheetmonth.css" type="text/css" />
<link rel="stylesheet" href="/js/oscar/dist/timesheetmonthday.css" type="text/css" />
<link rel="stylesheet" href="/js/oscar/dist/timesheetmonthdaydetails.css" type="text/css" />
<link rel="stylesheet" href="/js/oscar/dist/timesheetmonthworkpackageselector.css" type="text/css" />
<link rel="stylesheet" href="/js/oscar/dist/uitimechooser.css" type="text/css" />

<div class="flex-container">
    <div id="timesheet-declaration"
        data-declaration-in-hours="<?= $declarationInHours ? 'true' : 'false' ?>"
        data-default-year="<?= $year ?>"
        data-default-month="<?= $month ?>"
        data-url="<?= $this->url('timesheet/declarant2').($usurpation?"?person=$usurpation":"?") ?>"
        data-url-validation="<?= $this->url('timesheet/checkperiod')  ?>"
        data-url-import="<?= $this->options()->importEnable() ?
            $this->url('timesheet/import_ical'). ($usurpation?"?person=$usurpation":"?") : '' ?>"
    ></div>
</div>

<?php echo $this->Vite()->addJs('src/TimesheetDeclaration.js'); ?>