<link rel="stylesheet" href="<?= $this->basePath() . '/js/modules/unicaen/dist/css/calendar.css' ?>" />
<link rel="stylesheet" href="<?= $this->basePath() . '/js/modules/unicaen/dist/css/datepicker.css' ?>" />
<link rel="stylesheet" href="<?= $this->basePath() . '/css/icons/css/fontello.css' ?>" />
<div class="container">
    <?php
    $crenaux = [];
    $color = 0;
    $colorActivity = [];



    /** @var \Oscar\Entity\WorkPackage $wpd */
    foreach( $wpDeclarants as $wpd ){
        if( !array_key_exists($wpd->getActivity()->getId(), $colorActivity) ){
            $colorActivity[$wpd->getActivity()->getId()] = ++$color;
        }
        $crenaux[((string)$wpd)] = [
            'label'         => (string)$wpd,
            'acronym'       => $wpd->getActivity()->getAcronym(),
            'activity'      => (string)$wpd->getActivity(),
            'activity_code' => $wpd->getActivity()->getOscarNum(),
            'idactivity'    => $wpd->getActivity()->getId(),
            'active'        => $wpd->getActivity()->isActive(),
            'code' => $wpd->getCode(),
            'idworkpackage' => $wpd->getId(),
            'color' => $colorActivity[$wpd->getActivity()->getId()]
        ];
    }
    ?>
    <div id="app">
        <calendar :create-new="true" calendar-label="Déclaration de vos activités" :moment="moment"></calendar>
    </div>
</div>

<script>
    require(['underscore', 'vue', 'vue-resource',
        'mm', 'bootbox', 'calendar2',
        'CalendarModel', 'polyfill'], function(underscore, Vue, VueResource, moment, bootbox, Calendar, CalendarModel){

        Vue.use(VueResource);

        Vue.http.options.emulateJSON = true;
        Vue.http.options.emulateHTTP = true;

        window.moment = moment;
        window.bootbox = bootbox;
        window.CalendarModel = CalendarModel.default;

        var customDatas = <?= json_encode($crenaux) ?>;

        window.moment = moment;
        window.bootbox = bootbox;

        console.log('moment', window.moment);

        moment.locale('fr');

        var colorLabels = {};
        var colorIndex = 0;
        var colorpool = ['#fcdc80', '#a6cef8', '#9fd588', '#fb90bb', '#e5fbed', '#99a0ce', '#bca078', '#f3cafd', '#d9f4c1', '#60e3bb', '#f2c7f5', '#f64bc0', '#ffc1b2', '#fc9175', '#d7fc74', '#e3d7f8', '#9ffab3', '#d6cbac', '#4dd03c', '#f8f3be'];



        var mixins = {
            methods: {
                restUrl(){
                    return '<?= $this->url('timesheet/api') ?>'
                },
                customDatas(){
                    return customDatas;
                },
                formatDuration: function(milliseconde){
                        var h = Math.floor(milliseconde / 60 / 60);
                        var m = (milliseconde - (h * 60 * 60)) / 60;
                        return h + (m ? 'h' + m : '');

                },
                colorLabel: function(label) {
                    if (!colorLabels[label]) {
                        colorLabels[label] = colorpool[++colorIndex];
                        colorIndex = colorIndex % colorpool.length;
                    }
                    return colorLabels[label];
                }
            }
        };

        Vue.mixin(mixins);


        var vue = new Vue({
            el: "#app",
            components: {
                'calendar': Calendar.default
            }
        });
        /****/
    });

</script>