<link rel="stylesheet" href="<?= $this->basePath() . '/js/modules/unicaen/dist/css/calendar.css' ?>" />
<link rel="stylesheet" href="<?= $this->basePath() . '/js/modules/unicaen/dist/css/datepicker.css' ?>" />
<link rel="stylesheet" href="<?= $this->basePath() . '/css/icons/css/fontello.css' ?>" />
<div class="container">
    <?php
    $crenaux = [];
    $color = 0;
    $colorActivity = [];

    /** @var \Oscar\Entity\WorkPackage $wpd */
    foreach( $wpDeclarants as $wpd ){
        if( !array_key_exists($wpd->getActivity()->getId(), $colorActivity) ){
            $colorActivity[$wpd->getActivity()->getId()] = ++$color;
        }
        $crenaux[((string)$wpd)] = [
            'label'         => (string)$wpd,
            'acronym'       => $wpd->getActivity()->getAcronym(),
            'activity'      => (string)$wpd->getActivity(),
            'activity_code' => $wpd->getActivity()->getOscarNum(),
            'idactivity'    => $wpd->getActivity()->getId(),
            'active'        => $wpd->getActivity()->isActive(),
            'code' => $wpd->getCode(),
            'idworkpackage' => $wpd->getId(),
            'color' => $colorActivity[$wpd->getActivity()->getId()]
        ];
    }
    ?>
    <div id="app">
        <calendar :create-new="true" calendar-label="Déclaration de vos activités"></calendar>
    </div>
</div>

<script>
    require(['vue', 'vue-resource', 'calendar'], function(Vue, VueResource, Calendar){

        Vue.use(VueResource);

        Vue.http.options.emulateJSON = true;
        Vue.http.options.emulateHTTP = true

        var customDatas = <?= json_encode($crenaux) ?>;

        var mixins = {
            methods: {
                restUrl(){
                    return '<?= $this->url('timesheet/api') ?>'
                },
                customDatas(){
                    return customDatas;
                }
            }
        }

        Calendar.mixins = [
            mixins
        ];

        var vue = new Vue({
            el: "#app",
            components: {
                'calendar': Calendar
            }
        });
    })
</script>