<div class="container">
    <div id="app"></div>
</div>
<script>
    require(['vue', 'vue-resource', 'TimesheetMonth', 'mm'], function(Vue, VueResource, TimesheetMonth, moment){
        Vue.use(VueResource);

        new Vue({
            render: function(h){
                return h(TimesheetMonth.default, { props: {
                  year: <?= date('Y') ?>,
                  month: <?= date('m') ?>,
                  moment: moment
                }});
            }
        }).$mount('#app');
    })
</script>
<style>
    .wp {
        display: flex;
        align-items: stretch;
    }
    .wp > * {
        display: block;
        background: #efefef;
        flex: 1;
        padding: 4px;
        text-align: right;
    }

    .wp > *:nth-child(2n) {
        background: white;
    }
</style>