
<?php /** @var \Oscar\Entity\Activity $activity */

$startRef = $activity->getDateStart(true) ? $activity->getDateStart(true) : $activity->getDateCreated();
$endRef = $activity->getDateEnd() ? $activity->getDateEnd() : new DateTime();

$months = ['','Janvier', 'Février', 'Mars', 'Avril', 'Mai', 'Juin', 'Juillet', 'Aout', 'Septembre', 'Octobre','Novembre','Décembre'];

$monthStartLimit = (integer)$startRef->format('m');
$yearStart = (integer)$startRef->format('Y');

$monthEndLimit = (integer)$endRef->format('m');
$yearEnd = (integer)$endRef->format('Y');
?>

<?php
for( $year = $yearStart; $year<=$yearEnd; $year++ ){
    $monthStart = $year == $yearStart ? $monthStartLimit : 1;
    $monthEnd = $year == $yearEnd ? $monthEndLimit : 12;
    ?>
    <div class="card">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th><h3 class='card-title'><?= $year ?></h3></th>
                    <?php foreach( $activity->getWorkPackages() as $workPackage ): ?>
                    <th><h3><?= $workPackage->getCode() ?></h3><p class="text-light"><?= $workPackage->getLabel() ?></p></th>
                    <?php endforeach; ?>
                    <th>Sous-total</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
            <?php for( $month = $monthStart; $month<=$monthEnd; $month++ ){
        ?>
        <tr id="timesheet-<?= $month ?>-<?= $year ?>">
            <td>
                <strong><?= $months[$month] ?></strong> <?= $year ?>
            </td>
            <?php
            /** @var \Oscar\Entity\WorkPackage $workPackage */
            foreach( $activity->getWorkPackages() as $workPackage ): ?>
            <td>
                <input type="text" name="time[<?= $workPackage->getCode() ?>]" size="3" /> heure(s)
            </td>
            <?php endforeach; ?>
            <td>TOTAL</td>
            <td>
                <button class="btn btn-success btn-xs"><i class="icon-edit"></i> Enregistrer</button>
                <button class="btn btn-default btn-xs"><i class="icon-paper-plane"></i> Soumettre</button>
            </td>
        </tr>
        <?php
    }
    echo '</tbody>';

}?>
</table></div>