<?php
/* @var \Oscar\Entity\Activity $activity */
?>
<section class="container">
    <h1>
        <small>Déclarations pour</small><br>
        <i class="cubes"></i> <?= $activity->getProject() ?> /<br>
        <strong><i class="cube"></i> <?= $activity ?></strong>
    </h1>

    <pre>
<?= $activity->getTimesheetFormat() ?>
    </pre>

    <?php foreach( $activity->getPersonsDeep() as $person  ): ?>
    <article>
        <h2><?= $person->getPerson() ?></h2>
    </article>
    <?php endforeach; ?>
</section>