<div class="container">
    <div id="app">Chargement</div>
    <script>
        require(['vue', 'TimesheetPersonResume', 'mm'], function(Vue, TimesheetPersonResume, moment){

            // Affichage des périodes
            Vue.filter('period', function(value){
                return moment(value+"-01").format("MMMM YYYY");
            });

            new Vue({
                el: "#app",
                render: function(h){
                    return h(TimesheetPersonResume.default, { props: { datas: <?= json_encode($datas) ?>}});
                }
            })
        });
    </script>
</div>