<div class="container">
    <h1>
        Feuilles de temps
        <?php if( $person ): ?>
            pour <strong><?= $person ?></strong>
        <?php endif; ?>
    </h1>
    <div class="timesheet-resume" id="timesheet-resume"
        <?php if( DEBUG_OSCAR ) echo 'data-debug-enabled="true"' ?>
         data-url="<?= $url ?>"
    ></div>
    <?= $this->Vite()->addJs('src/TimesheetPersonResume.js'); ?>
</div>