<?php
/**
 * Created by PhpStorm.
 * User: bouvry
 * Date: 20/05/19
 * Time: 14:55
 */

$labels = [
    "abs" => "Absent",
    "education" => "Éducation",
    "other" => "Autre",
    "research" => "Recherche"
]
?>
<style>
    body {
        font-size: 12px;
        font-family: Helvetica, Arial, sans-serif;
    }
    table {
        width: 100%;
        max-width: 100%;
        border-collapse: collapse;
    }
    tr { border: thin solid #adb6bd}
    td {}
    thead h1 {
        font-weight: normal;
    }

    thead th {
        text-align: center;
    }

    tbody th:nth-child(odd) {
        background-color: #c0e1f1;
    }
    tbody th:nth-child(even) {
        background-color: #cde7f1;
    }

    .label { text-align: left }
    .subgroup {
        font-size: 9px;
    }
    .subgroup .label {
        font-weight: normal;
    }
    th {
        border: thin solid #adb6bd;
    }
    thead td {
        background: #e3e8e6;
    }
    thead td.value, tfoot td.value {
        /*background: #f1f6f4;*/
        text-align: left;
        font-weight: 900;
    }
    thead td.valueLabel, tfoot td.valueLabel {
        text-align: right;
    }

    tbody td {
        text-align: right;
        /*background: #f5faf8;*/
        padding: 4px;
        border: thin solid #e4edf4;
    }
    tbody td:nth-child(odd){
       /* background: #e3e8e6;*/
    }
    .feed {
        font-weight: bold;
    }
    .empty {
        font-size: 10px;
    }
    .lock {
        background: #fff !important;
    }
    .soustotal {
        font-weight: bold;
        font-size: 12px;
    }
    .total {
        font-weight: 700;
        font-size: 14px;
    }
</style>
<style>
    small {
        font-weight: 100;
        display: block;
        border-top: thin solid #777;
    }
    th {
        vertical-align: center;
        font-weight: normal;
    }
    .main {
        background: #97c6d6;
    }
    .research {
        background: #b1c6e5;
    }
    .education {
        background: #a6e3c7;
    }
    .abs {
        background: #d6e4b2;
    }
    .other {
        background: #d7b5e5;
    }
    .duration {
        text-align: right;
    }
    tr {
        border: none;
    }
    .table tr > th {
        border: none;
    }
    .table > thead > tr th {
        vertical-align: center;
    }
</style>

    <div class="container-fluid">

        <h1>
            <em style="font-weight: 100">Synthèse des déclarations </em> :
            <strong><?= $activity['projectacronym'] ?></strong> <?= $activity['project'] ?><br>
            <small>
            <i class="icon-calendar"></i> Du <strong><?= $period['startLabel'] ?></strong>
            au <strong><?= $period['endLabel'] ?></strong>
            </small>
        </h1>
        <?php if( $format != 'pdf' && $format != 'html'): ?>
        <p>
            <a class="btn btn-primary" href="/feuille-de-temps/synthesisactivity?activity_id=<?= $activity['id'] ?>&format=excel&period=<?= $period['year'] ?>-<?= $period['month'] ?>">
                <i class="icon-file-excel"></i>
            Télécharger la version Excel
            </a>
            <a class="btn btn-primary disabled" href="/feuille-de-temps/synthesisactivity?activity_id=<?= $activity['id'] ?>&format=pdf&period=<?= $period['year'] ?>-<?= $period['month'] ?>">
                <i class="icon-file-pdf"></i>
                Télécharger la version PDF (bientôt disponible)
            </a>
        </p>
        <?php endif; ?>
<table class="table table-condensed" style="border: 0">
    <thead>
        <tr>
            <th>&nbsp;</th>
            <?php
            // Nombre de colonne dans les groupe
            $colWP      = count($wps) + (count($wps)>1 ? 1 : 0);
            $colCE      = count($ces) + (count($ces)>1 ? 1 : 0);
            $colSEARCH  = count($othersGroups['research']) + (count($othersGroups['research'])>1 ? 1 : 0);

            $colEDU = count()
            ?>
            <th class="research" colspan="<?= $colWP + $colCE + $colSEARCH +1 ?>"><i class="icon-beaker"></i> Recherches</th>

            <?php foreach ($othersGroups as $k=>$othersGroup): if( $k == 'research') continue;?>
                <th class="<?= $k ?>" colspan="<?= count($othersGroup)+(count($othersGroup)>1 ? 1 : 0) ?>">
                    <i class="icon-<?= $k ?>"></i>
                    <?= $labels[$k] ?>
                </th>
            <?php endforeach; ?>
            <th rowspan="3">Total actif</th>
            <th rowspan="3">TOTAL</th>
        </tr>
        <tr>
            <th>&nbsp;</th>

            <th class="research" colspan="<?= $colWP ?>"><i class="icon-cubes"></i> <strong><?= $activity['projectacronym'] ?></strong> <?= $activity['label'] ?></th>
            <?php if( count($ces) > 0): ?>
            <th class="research" colspan="<?= $colCE ?>"><i class="icon-cubes"></i> Projets</th>
            <?php endif; ?>
            <th class="research" colspan="<?= $colSEARCH ?>"><i class="icon-cubes"></i> Autres</th>
            <th class="research" rowspan="2">TOTAL</th>

            <?php foreach ($othersGroups as $k=>$othersGroup): if( $k == 'research') continue;?>
                <?php foreach ($othersGroup as $other): ?>
                    <th class="<?= $k ?>" rowspan="2">
                        <?= $other['label'] ?>
                    </th>
                <?php endforeach; ?>
                <?php if( count($othersGroup) > 1): ?>
                    <th class="<?= $k ?>" rowspan="2">
                        <strong>Total</strong>
                    </th>
                <?php endif; ?>
            <?php endforeach; ?>
        </tr>
        <tr>
            <th>&nbsp;</th>

            <?php foreach ($wps as $code=>$wp): ?>
                <th class="research activity">
                    <strong><i class="icon-archive"></i><?= $wp['code'] ?></strong>
                </th>
            <?php endforeach; ?>
            <?php if( count($wps) > 1): ?>
                <th class="research activity">
                    <strong>Total</strong>
                </th>
            <?php endif; ?>

            <?php foreach ($ces as $acronym): ?>
                <th class="research ce" rowspan="2">
                    <strong><i class="icon-cube"></i><?= $acronym ?></strong>
                </th>
            <?php endforeach; ?>
            <?php if( count($ces) > 1): ?>
                <th class="research activity">
                    <strong>Total</strong>
                </th>
            <?php endif; ?>

            <?php foreach ($othersGroups as $k=>$othersGroup): if( $k != 'research') continue;?>
                <th class="<?= $k ?>" colspan="<?= count($othersGroup)+(count($othersGroup)>1 ? 1 : 0) ?>">
                    <i class="icon-<?= $k ?>"></i>
                    <?= $labels[$k] ?>
                </th>
            <?php endforeach; ?>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($foo as $person=>$line): ?>
        <tr>
            <th style="background: #fff"><i class="icon-user"></i><?= $person ?></th>
            <?php foreach ($line['main'] as $wp=>$duration): ?>
                <td class="main duration">
                    <?= $this->duration($duration) ?>
                </td>
            <?php endforeach; ?>
            <td class="main duration">
                <strong><?= $this->duration($line['totalMain']) ?></strong>
            </td>

            <?php foreach ($line['ce'] as $acronym=>$duration): ?>
                <td class="ce research duration">
                    <?= $this->duration($duration) ?>
                </td>
            <?php endforeach; ?>


            <?php if( count($ces) > 1): ?>
                <th class="research duration">
                    <strong><?= $this->duration($line['totalProjects']) ?></strong>
                </th>
            <?php endif; ?>

            <?php if( array_key_exists('research', $line['othersGroups'] ) ): ?>
                <?php foreach ($line['othersGroups']['research']['others'] as $duration): ?>
                    <td class="ce research duration">
                        <?= $this->duration($duration) ?>
                    </td>
                <?php endforeach; ?>


            <?php endif; ?>

            <td class="ce research duration">
                <strong>
                <?= $this->duration($line['totalResearch']) ?>
                </strong>
            </td>

            <?php foreach ($line['othersGroups']['research'] as $dt): ?>
                <?php foreach ($dt['others'] as $other=>$duration): ?>
                <td class="ce research duration">
                    d<?= $this->duration($duration) ?>
                </td>
                <?php endforeach; ?>
                <?php if( count($dt['others']) > 1): ?>
                <td class="ce research duration">
                    <strong><?= $this->duration($dt['total']) ?></strong>
                </td>
                <?php endif; ?>
            <?php endforeach; ?>

            <?php foreach ($line['othersGroups'] as $group=>$dt): if($group == 'research') continue;?>
                <?php foreach ($dt['others'] as $other=>$duration): ?>
                    <td class="ce <?= $group ?> duration">
                        <?= $this->duration($duration) ?>
                    </td>
                <?php endforeach; ?>
                <?php if( count($dt['others']) > 1): ?>
                    <td class="ce <?= $group ?> duration">
                        <strong><?= $this->duration($dt['total']) ?></strong>
                    </td>
                <?php endif; ?>
            <?php endforeach; ?>

            <td class="duration">
                <strong><?= $this->duration($line['totaux']['totalWork']) ?></strong>
            </td>

            <td style="background: #fff" class="duration">
                <strong><?= $this->duration($line['totaux']['total']) ?></strong>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>

    <tfoot>
    <tr style="border-top: 4px solid #000">
        <th>Total période</th>
        <?php foreach( $totaux['wps'] as $wp=>$duration ): ?>
            <th class="duration">
                <strong><?= $this->duration($duration) ?></strong>
            </th>
        <?php endforeach; ?>

        <?php if( count($wps) > 1 ): ?>
            <th class="duration">
                <strong><?= $this->duration($totaux['totalMain']) ?></strong>
            </th>
        <?php endif; ?>


        <?php foreach( $totaux['ce'] as $acronym=>$duration ): ?>
            <th class="duration">
                <strong><?= $this->duration($duration) ?></strong>
            </th>
        <?php endforeach; ?>
        <?php if( count($ces) > 1 ): ?>
            <th class="duration">
                <strong><?= $this->duration($totaux['totalCe']) ?></strong>
            </th>
        <?php endif; ?>

        <?php foreach ($othersGroups as $group=>$dt): if($group != 'research') continue;?>

            <?php foreach ($dt as $code=>$other): ?>
                <td class="duration">
                    <strong><?= $this->duration($totaux['others'][$code]) ?></strong>
                </td>
            <?php endforeach; ?>
            <?php if( count($dt['others']) > 1): ?>
                <td class="duration">
                    <strong><?= $this->duration($totaux['groups']['research']) ?></strong>
                </td>
            <?php endif; ?>
        <?php endforeach; ?>
        <td class="duration">
            <strong><?= $this->duration($totaux['totalResearch']) ?></strong>
        </td>

        <?php foreach ($othersGroups as $group=>$dt): if($group == 'research') continue;?>

            <?php foreach ($dt as $code=>$other): ?>
                <td class="duration">
                    <strong><?= $this->duration($totaux['others'][$code]) ?></strong>
                </td>
            <?php endforeach; ?>
            <?php if( count($dt) > 1): ?>
                <td class="duration">
                    <strong><?= $this->duration($totaux['groups'][$group]) ?></strong>
                </td>
            <?php endif; ?>
        <?php endforeach; ?>
        <td class="duration">
            <strong><?= $this->duration($totaux['totalWork']) ?></strong>
        </td>
        <td class="duration">
            <em><?= $this->duration($totaux['total']) ?></em>
        </td>


        <th>&nbsp;</th>
    </tr>
    </tfoot>
</table>
        </div>