<?php
/**
 * Created by PhpStorm.
 * User: bouvry
 * Date: 20/08/18
 * Time: 15:49
 */

// compilation du CSS (phase de développement)
// poi watch --format umd --moduleName  ValidationActivityVue --filename.css ValidationActivityVue.css --filename.js ValidationActivityVue.js --dist public/js/oscar/dist public/js/oscar/src/ValidationActivityVue.vue
?>
<link rel="stylesheet" href="/js/oscar/dist/validationactivityvue.css" />
<section class="container-fluid">
    <h1>
        Validation pour l'activité <br>
        <strong>
            <i class="icon-cube"></i>
            <?= $activity ?></strong>
    </h1>

    <div id="app"></div>
    <script>
            require(['vue', 'vue-resource', 'ValidationActivityVue', 'bootbox', 'mm'], function(Vue, VueResource, ValidationActivityVue, Bootbox, moment){
                Vue.use(VueResource);



                let mode = "POURCENT";

                Vue.filter('duration2', function(duree, total){
                    if( duree == 0 ) return 0.0;
                    return Math.round( 100 / total * duree) + "%";
                });

                Vue.filter('duration', function(v){
                    if( v == 0 ){
                        return '0';
                    }
                    let h = Math.floor(v);
                    let m = Math.round((v - h)*60);
                    if( m < 10 ) m = '0'+m;
                    return h +':' +m;
                });

                Vue.filter('monthyear', function(v){
                    var m = moment(v);
                    return m.format('MMMM YYYY');
                });

                console.log(<?= json_encode($periods) ?>);

                new Vue({
                    render: function(h){
                        return h(ValidationActivityVue.default, {
                            props: {
                                periods: <?= json_encode($periods) ?>,
                                bootbox: Bootbox
                            }
                        });
                    }
                }).$mount('#app');
            })
    </script>
</section>
