<?php
/**
 * @author Stéphane Bouvry<stephane.bouvry@unicaen.fr>
 * @date: 27/01/16 14:59
 * @copyright Certic (c) 2016
 */

$facet;
?>
<div class="container">
    <h1><i class="icon-calendar"></i>Type de jalon</h1>
    <p class="info">
        <?= count($entities) ?> type(s)
    </p>

    <?php foreach( $entities as $entity ):
        if( $facet != $entity['facet'] ){
            $text = $facet = $entity['facet'];
            if( !$text ) $text = '<i>Non défini</i>';

            echo "<h3>$text</h3>";
        }

        ?>
    <article class="card xs">
        <h2 class="card-title">

            <span>
                <small><?= $entity['facet'] ?> /</small>
                <strong><?= $entity['label'] ?></strong>

            </span>
            <nav class="text-right">
                <small>
                    <a href="<?= $this->url('datetype/delete', ['id' => $entity['id']]) ?>" class="link">
                        <i class="icon-trash"></i>
                        Supprimer</a>
                    <a href="<?= $this->url('datetype/edit', ['id' => $entity['id']]) ?>" class="link">
                        <i class="icon-pencil"></i>
                        Modifier</a>
                </small>
            </nav>
        </h2>
        <div class="card-content">
            <?php if( $entity['description']): ?>
                <span class="description"><?= $entity['description'] ?></span><br>
            <?php endif; ?>
            <i class="icon-cube"></i>
            Usage :  <?php if( $entity['used'] ): ?>
                <span class="label label-primary"><?= $entity['used'] ?></span>
            <?php else: ?>
                <span class="label label-default">Inutilisé</span>
            <?php endif; ?>

            <span class="recursivity">
                    <i class="icon-history"></i>  Rappel avant échéance :
                    <?php if( $entity['recursivity'] ): ?>
                        <?php foreach( explode(',', $entity['recursivity']) as $days ): ?>
                            <span class="cartouche"><?= $days ?> jours</span>
                        <?php endforeach; ?>
                    <?php else: ?>
                        <i>Aucun</i>
                    <?php endif; ?>
            </span>

            <div class="roles">
                <i class="icon-user"></i> Roles :
                <?php foreach( $entity['roles'] as $r ): ?>
                    <span class="cartouche primary"><?= $r ?></span>
                <?php endforeach; ?>
            </div>

            <span>
                <?php if( $entity['finishable'] ): ?>
                    <i class="icon-ok-circled" title="Gestion de la complétude"></i>
                    Ce type doit être marqué comme terminé
                <?php endif; ?>
            </span>
        </div>
    </article>
    <?php endforeach; ?>

    <footer>
        <a href="<?= $this->url('datetype/new') ?>" class="btn btn-primary">créer</a>
    </footer>
</div>
