<section class="container-fluid">
    <h1>Nouveau Jalon</h1>
    <div class="form">
        <?= $this->form()->openTag($form->prepare()); ?>
        <?= $this->formControlGroup($form->get('type')); ?>
        <?= $this->formControlGroup($form->get('dateStart')); ?>
        <?= $this->formControlGroup($form->get('comment')); ?>

        <?= $this->formHidden($form->get('id')); ?>
        <?= $this->formHidden($form->get('secure')); ?>
        <hr>
        <div class="text-center">
            <nav class="btn-group">
                <a class="btn btn-default button-back" href="<?= $this->url('contract/show', ['id' => $activity->getId()]) ?>">Retour à la liste</a>
                <button class="btn btn-primary" type="submit">Enregistrer</button>
            </nav>
        </div>
        <?= $this->form()->closeTag() ?>
    </div>
    <script>
        Initer.ready(function(){
            require(['datepicker'], function () {
                $('.datepicker').datepicker({
                    format: "yyyy-mm-dd",
                    todayBtn: "linked",
                    clearBtn: true,
                    language: "fr",
                    autoclose: true,
                    toggleActive: true
                });
            });
        });
    </script>
</section>