<?php
if(
    $this->grant()->privilege(\Oscar\Provider\Privileges::ORGANIZATION_INDEX) ||
    $this->grant()->privilege(\Oscar\Provider\Privileges::PERSON_INDEX) ||
    $this->grant()->privilege(\Oscar\Provider\Privileges::DROIT_PRIVILEGE_VISUALISATION) ||
    $this->grant()->privilege(\Oscar\Provider\Privileges::MAINTENANCE_ACTIVITYTYPE_MANAGE) ||
    $this->grant()->privilege(\Oscar\Provider\Privileges::MAINTENANCE_MILESTONETYPE_MANAGE) ||
    $this->grant()->privilege(\Oscar\Provider\Privileges::MAINTENANCE_ORGANIZATIONTYPE_MANAGE) ||
    $this->grant()->privilege(\Oscar\Provider\Privileges::ACTIVITY_TIMESHEET_USURPATION) ||
    $this->grant()->privilege(\Oscar\Provider\Privileges::MAINTENANCE_ACTIVITYTYPE_MANAGE) ||
    $this->grant()->privilege(\Oscar\Provider\Privileges::MAINTENANCE_ACTIVITYTYPE_MANAGE) ||
    $this->grant()->privilege(\Oscar\Provider\Privileges::MAINTENANCE_VALIDATION_MANAGE)
):
?>

<li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Administration <span class="caret"></span></a>
    <ul class="dropdown-menu" role="menu">

        <?php if($this->grant()->privilege(\Oscar\Provider\Privileges::ORGANIZATION_SHOW)): ?>
            <li role="presentation" class="dropdown-header"><i class="icon-building-filled"></i> Organisations</li>
            <li><a href="<?= $this->url('organization') ?>">Liste des organisations</a></li>
            <?php if($this->grant()->privilege(\Oscar\Provider\Privileges::ORGANIZATION_EDIT)): ?>
                <li><a href="<?= $this->url('organization/new') ?>">Nouvelle organisation</a></li>
            <?php endif; ?>
        <?php endif; ?>

        <?php if($this->grant()->privilege(\Oscar\Provider\Privileges::PERSON_INDEX)): ?>
            <li role="presentation" class="dropdown-header"><i class="icon-group"></i> Personnes</li>
            <li><a href="<?= $this->url('person') ?>">Liste des personnes</a></li>
            <?php if($this->grant()->privilege(\Oscar\Provider\Privileges::PERSON_EDIT)): ?>
                <li><a href="<?= $this->url('person/new') ?>">Ajouter une personne</a></li>
            <?php endif; ?>
        <?php endif; ?>

        <?php if($this->grant()->privilege(\Oscar\Provider\Privileges::ACTIVITY_TIMESHEET_VIEW)): ?>
            <li role="presentation" class="dropdown-header"><i class="icon-group"></i> Déclarants</li>
            <li><a href="<?= $this->url('person/declarers') ?>">Liste des déclarants</a></li>
        <?php endif; ?>





        <li role="presentation" class="dropdown-header"><i class="icon-stethoscope"></i> Maintenance des données</li>

        <li>
            <a href="<?= $this->url('contract/pcru-list') ?>">
                <?= $this->translate("Processus PCRU") ?></a>
            </a>
        </li>

        <?php if( $this->grant()->privilege(\Oscar\Provider\Privileges::ACTIVITY_INDEX) ):?>
        <li><a href="<?= $this->url('contract/advancedsearch') ?>?criteria[]=pp%3Bnull%3Bnull"><?= $this->translate("Activités sans projet") ?></a></li>
        <?php endif; ?>

        <?php if( $this->grant()->privilege(\Oscar\Provider\Privileges::PROJECT_INDEX) ):?>
        <li><a href="<?= $this->url('project/empty') ?>"><?= $this->translate("Projets sans activité") ?></a></li>
        <?php endif; ?>

        <li role="presentation" class="dropdown-header"><i class="icon-cog"></i> Configuration</li>

        <li><a href="<?= $this->url('administration/accueil') ?>"><?= $this->translate("Configuration et maintenance") ?></a></li>
    </ul>
</li>
<?php endif; ?>