<?php
/**
 *
 * @author Stéphane Bouvry<stephane.bouvry@unicaen.fr>
 * @date: 18-04-26 10:17
 * @copyright Certic (c) 2018
 */
if(
    $this->grant()->privilege(\Oscar\Provider\Privileges::PROJECT_INDEX) ||
    $this->grant()->privilege(\Oscar\Provider\Privileges::ACTIVITY_INDEX) ||
    $this->grant()->privilege(\Oscar\Provider\Privileges::ACTIVITY_PAYMENT_SHOW) ||
    $this->grant()->privilege(\Oscar\Provider\Privileges::ACTIVITY_MILESTONE_SHOW)
):
?>

<li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
        <i class="icon-cube"></i> Activités <span class="caret"></span>
    </a>
    <ul class="dropdown-menu" role="menu">

        <?php if($this->grant()->privilege(\Oscar\Provider\Privileges::PROJECT_INDEX)): ?>
            <li role="presentation" class="dropdown-header"><i class="icon-cubes"></i> Projets</li>
            <li><a href="<?= $this->url('contract/advancedsearch') ?>?projectview=on">Liste des projets</a></li>
            <?php if($this->grant()->privilege(\Oscar\Provider\Privileges::PROJECT_CREATE)): ?>
                <li><a href="<?= $this->url('project/new') ?>?projectview=on">Créer un projet</a></li>
            <?php endif; ?>
        <?php endif; ?>

        <?php if($this->grant()->privilege(\Oscar\Provider\Privileges::ACTIVITY_INDEX)): ?>
        <li role="presentation" class="dropdown-header"><i class="icon-cube"></i> Activités</li>
        <li><a href="<?= $this->url('contract/advancedsearch') ?>">Liste des activités</a></li>

        <?php if($this->grant()->privilege(\Oscar\Provider\Privileges::ACTIVITY_DOCUMENT_SHOW)): ?>
        <li><a href="<?= $this->url('contractdocument') ?>">Documents téléversés</a></li>
        <?php endif; ?>

        <?php if( $this->grant()->privilege(\Oscar\Provider\Privileges::ACTIVITY_EDIT) ):?>
        <li><a href="<?= $this->url('contract/new') ?>">Nouvelle activité</a></li>
        <?php endif; ?>
        <li><a href="<?= $this->url('contract/almostdone') ?>">Bientôt terminés</a></li>
        <li><a href="<?= $this->url('contract/almoststart') ?>">Débutant prochainement</a></li>
        <?php endif; ?>

        <?php if ($this->grant()->privilege(\Oscar\Provider\Privileges::ACTIVITY_PAYMENT_SHOW)): ?>
            <li role="presentation" class="dropdown-header"><i class="icon-bank"></i> Versements</li>
            <li><a href="<?= $this->url('payment/income') ?>">Prochains versements</a></li>
            <li><a href="<?= $this->url('payment/late') ?>">Versements en retard</a></li>
            <li><a href="<?= $this->url('payment/difference') ?>">Écarts de paiement</a></li>
            <li><a href="<?= $this->url('payment') ?>">Tous les versements</a></li>
        <?php endif; ?>

        <?php if ($this->grant()->privilege(\Oscar\Provider\Privileges::ACTIVITY_MILESTONE_SHOW)): ?>
            <li role="presentation" class="dropdown-header"><i class="icon-calendar"></i> Jalons</li>
            <li><a href="<?= $this->url('milestones') ?>">Tous les jalons</a></li>
        <?php endif; ?>

    </ul>
</li>
<?php endif; ?>