<?php
/**
 * @author Stéphane Bouvry<stephane.bouvry@unicaen.fr>
 * @date: 16-04-27 11:46
 * @copyright Certic (c) 2016
 */
/** @var Person $person */
$person = $enroll->getPerson();
?>
<article class="card person-card" style="<?= $enroll->isOutOfDate() ? 'opacity: .5' : '' ?>">
    <span class="intitule">
        <?php if($person->getEmail()): ?>
            <img class="portrait"
                 src="//www.gravatar.com/avatar/<?= md5($person->getEmail()) ?>?s=75"
                 alt="">
        <?php endif; ?>
        <span class="fullname">
            <?php if( $enroll->isOutOfDate() ): ?>
            <i class="icon-block"></i>
            <?php endif; ?>
            <i></i>
            <span class="firstname"><?= $person->getFirstname() ?></span>
            <span class="lastname"><?= $person->getLastname() ?></span>
            <span class="affectation">(<?= $person->getLdapAffectation() ?>)</span>

            <?php if( $enroll->getDateEnd() ): ?>
                <div class="role">
                    <?= $enroll->getRole() ?>
                    <small> ( <?= ($enroll->isPast() ? 'fini depuis le ' : 'prendra effet le' ) . $this->moment($enroll->getDateEnd()) ?>)</small>
                </div>
            <?php else: ?>
                <div class="role"><?= $enroll->getRole() ?></div>
            <?php endif; ?>


            <?php if( $enroll->getDateStart() ): ?>
            <small>Depuis le <?= $this->moment($enroll->getDateStart()) ?></small>
            <?php endif; ?>


        </span>

    </span>
    <span class="email"><?= $person->getEmail() ?></span>
    <nav>
        <a href="<?= $this->url('person/show', ['id' => $person->getId()]) ?>" class="link-show"><i class="icon-zoom-in-outline"></i> Fiche</a>
        <a href="<?= $urlDelete ?>" class="link-show"><i class="icon-trash"></i> Supprimer ce rôle</a>
        <?php if( isset($urlClose) ):?>
            <button data-enrollid="<?= $enroll->getId() ?>">Résilier</button>
        <?php endif; ?>
    </nav>
</article>
