<style>
    div.multicheckbox {
        display: flex;
        flex-wrap: wrap;
    }

    div.multicheckbox label {
        flex: 0 0 19%;
        vertical-align: baseline;
        display: flex;
        align-items: center;
        background: rgba(255, 255, 255, .3);
        padding: 4px;
        margin: 4px;
        border-radius: 1%;
    }

    div.multicheckbox label:hover {
        background: rgba(255, 255, 255, .5);
    }

    div.multicheckbox label input {
        display: inline-block;
        width: 34px;
        margin-right: .5em;
    }
</style>

<section class="container">


    <h1>
        <?= ($entity->getId(
        )) ? "<small>Modification de</small><br><i class=\"icon-calendar\"></i> <strong>" . $entity . "</strong>" : "Nouvel onglet de document" ?>
    </h1>
    <div class="form">
        <?= $this->form()->openTag($form->prepare()); ?>
        <?= $this->formControlGroup($form->get('label')); ?>
        <?= $this->formElementErrors($form->get('label'), array('class' => 'help-inline')); ?>

        <?= $this->formControlGroup($form->get('default')); ?>
        <?= $this->formElementErrors($form->get('default'), array('class' => 'help-inline')); ?>

        <div class="row">
            <div class="form-group">
                <div class="col-md-12">
                    <label for="">Roles</label>
                    <p class="help">Affectation des roles aux onglets</p>
                    <table class="table-condensed">
                        <?php
                        foreach ($roles as $role): ?>
                            <tr>
                                <td><?= $role->getRoleId(); ?></td>
                                <td><?= $this->formRow($form->get('roleId_' . $role->getId())); ?></td>
                            </tr>
                        <?php
                        endforeach; ?>
                    </table>

                </div>
            </div>
        </div>

        <?= $this->formControlGroup($form->get('description')); ?>
        <?= $this->formElementErrors($form->get('description'), array('class' => 'help-inline')); ?>
        <?= $this->formHidden($form->get('id')); ?>
        <?= $this->formHidden($form->get('secure')); ?>
        <?= $this->formElementErrors($form->get('secure'), array('class' => 'help-inline')); ?>
        <hr>
        <div class="text-center">
            <nav class="btn-group">
                <a class="btn btn-default" href="<?= $this->url('tabdocument') ?>">Retour à la liste</a>
                <button class="btn btn-primary" type="submit">Enregistrer</button>
            </nav>
        </div>
        <?= $this->form()->closeTag() ?>
    </div>
    </div>
</section>
