access:
    information:
        view: ''
        manage: ''
    person:
        view: 'Consulter les informations utilisateur'
        manage: 'Modifier les informations utilisateurs'
        search: 'Recherche'
        sync: 'Synchronisation des données LDAP'
        
    project:
        view: 'Consulter les informations sur un projet'
        manage: 'Modifier les informations d''un projet'
        
    organization:
        view: 'desc'
        manage: 'desc'
        search: 'Recherche organisation'

    contract:
        view: 'Contract View'
        manage: 'Contract Manage'
        
roles:
    'Chargé de valorisation': ['information/*','person/*', 'project/*', 'contract/*', 'organization/*']
    'Responsable': ['information/*','person/*', 'project/*', 'contract/*', 'organization/*']
    'Corresponsable': ['information/*','person/*', 'project/*', 'contract/*', 'organization/*']
    'Ingénieur': ['information/view','person/view', 'organization/view']