<div class="container">
    <h1>
        <i class="icon-book"></i> Documents pratiques
    </h1>

    <?php
    $downloadable =  $this->grant()->connected();
    foreach( $documents as $section=>$docs ): ?>
    <h2><?= $section ?: '<em>Général</em>' ?> <small><?= count($docs) ?> document(s)</small></h2>
    <?php foreach ($docs as $document): ?>
    <article class="card">
        <h3 class="card-title">
            <i class="picto icon-doc doc-<?= $document['main']->getExtension() ?>"></i>
            <?= $document['main']->getFileName() ?>
            <small>
                version <?= $document['main']->getVersion() ?>,
                <?= $this->fileSize($document['main']->getFileSize()) ?>
            </small>
        </h3>
        <nav class="text-right show-over">

            <?php if( $moveable): ?>
                <form action="" method="post" class="form-inline">
                    <input type="hidden" name="id" value="<?= $document['main']->getId() ?>" />
                    <select name="section_id" id="">
                        <option value="">Hors section (générale)</option>
                        <?php foreach ($sections as $section): ?>
                            <option value="<?= $section->getId() ?>"><?= $section ?></option>
                        <?php endforeach; ?>
                    </select>
                    <button type="submit">Enregistrer</button>
                </form>
            <?php endif; ?>

            <?php if($downloadable): ?>
                <a class="btn btn-default btn-xs" href="<?= $this->url('administrativedocument/download', ['id' => $document['main']->getId()]) ?>">
                    <i class="icon-download-outline"></i>
                    Télécharger le fichier
                </a>
            <?php endif; ?>

            <?php if($this->grant()->privilege(\Oscar\Provider\Privileges::ADMINISTRATIVE_DOCUMENT_NEW)): ?>
                <a class="btn btn-default btn-xs" href="<?= $this->url('administrativedocument/upload', ['id' => $document['main']->getId()]) ?>?id=<?= $document['main']->getId() ?>">
                    <i class="icon-attach-1"></i>
                    Téléverser une nouvelle version
                </a>
            <?php endif; ?>

            <?php if($this->grant()->privilege(\Oscar\Provider\Privileges::ADMINISTRATIVE_DOCUMENT_DELETE)): ?>
                <a class="btn btn-default btn-xs" href="<?= $this->url('administrativedocument/delete', ['id' => $document['main']->getId()]) ?>?id=<?= $document['main']->getId() ?>">
                    <i class="icon-trash"></i>
                    Supprimer
                </a>
            <?php endif; ?>
        </nav>
        <p class="text-highlight">
            Téléversé le <time><?= $this->moment($document['main']->getDateUpdoad())->full() ?></time>
            par
            <?php if($document['main']->getPerson()): ?>
                <strong>
                    <i class="icon-user"></i>
                    <?= $document['main']->getPerson() ?>
                </strong>
            <?php else: ?>
                <span class="no-data">Inconnu</span>
            <?php endif; ?>
        </p>
        <div class="card-content versions">
            <?php if( count($document['older']) > 0 ):?>
                <h4 class="opener"><i class="icon-opener"></i> Versions précédentes</h4>
                <div class="details" style="display: none">
                    <?php foreach( $document['older'] as $subdoc ): ?>
                        <article class="subdoc text-highlight">
                            <?php if($downloadable): ?>
                            <a href="<?= $this->url('administrativedocument/download', ['id' => $subdoc->getId()]) ?>" download="true" >
                                <?php endif; ?>
                                <i class="picto icon-doc doc-<?= $subdoc->getExtension() ?>"></i>
                                <strong>
                                    <?= $subdoc->getFileName() ?>,
                                    version <?= $subdoc->getVersion() ?></small></strong>,
                                téléversé <time><?= $this->moment($subdoc->getDateUpdoad())->since() ?></time>
                                par <span class="owner"><?= $subdoc->getPerson() ? $this->person($subdoc->getPerson()) : 'Anonymous' ?></span>
                                <?php if($downloadable): ?>
                            </a>
                        <?php endif; ?>

                        </article>
                    <?php endforeach; ?>
                </div>
            <?php endif; ?>
        </div>
    </article>

    <?php /*<article class="card">
        <h3 class="card-title">
            <i class="picto icon-doc doc-<?= $document['main']->getExtension() ?>"></i>
            <?= $document['main']->getFileName() ?>
            <small>
                version <?= $document['main']->getVersion() ?>,
                <?= $this->fileSize($document['main']->getFileSize()) ?>
            </small>
        </h3>
        <nav class="text-right show-over">

            <?php if( $moveable): ?>
                <form action="" method="post" class="form-inline">
                    <input type="hidden" name="id" value="<?= $document['main']->getId() ?>" />
                    <select name="section_id" id="">
                        <option value="">Hors section (générale)</option>
                        <?php foreach ($sections as $section): ?>
                        <option value="<?= $section->getId() ?>"><?= $section ?></option>
                        <?php endforeach; ?>
                    </select>
                    <button type="submit">Enregistrer</button>
                </form>
            <?php endif; ?>

            <?php if($downloadable): ?>
            <a class="btn btn-default btn-xs" href="<?= $this->url('administrativedocument/download', ['id' => $document['main']->getId()]) ?>">
                <i class="icon-download-outline"></i>
                Télécharger le fichier
            </a>
            <?php endif; ?>
            <?php if($this->grant()->privilege(\Oscar\Provider\Privileges::ADMINISTRATIVE_DOCUMENT_NEW)): ?>
            <a class="btn btn-default btn-xs" href="<?= $this->url('administrativedocument/upload', ['id' => $document['main']->getId()]) ?>?id=<?= $document['main']->getId() ?>">
                <i class="icon-attach-1"></i>
                Téléverser une nouvelle version
            </a>
            <?php endif; ?>
            <?php if($this->grant()->privilege(\Oscar\Provider\Privileges::ADMINISTRATIVE_DOCUMENT_DELETE)): ?>
                <a class="btn btn-default btn-xs" href="<?= $this->url('administrativedocument/delete', ['id' => $document['main']->getId()]) ?>?id=<?= $document['main']->getId() ?>">
                    <i class="icon-trash"></i>
                    Supprimer
                </a>
            <?php endif; ?>
        </nav>
        <p class="text-highlight">
            Téléversé le <time><?= $this->moment($document['main']->getDateUpdoad())->full() ?></time>
            par <?= $document['main']->getPerson() ? $this->person($document['main']->getPerson()) : '<span class="no-data">Inconnu</span>' ?>
        </p>
        <p>
            <?= $document['main']->getSection() ?: "-" ?>
        </p>

        <div class="card-content versions">
            <?php if( count($document['older']) > 0 ):?>
                <h4 class="opener"><i class="icon-opener"></i> Versions précédentes</h4>
                <div class="details" style="display: none">
                <?php foreach( $document['older'] as $subdoc ): ?>
                <article class="subdoc text-highlight">
                    <?php if($downloadable): ?>
                    <a href="<?= $this->url('administrativedocument/download', ['id' => $subdoc->getId()]) ?>" download="true" >
                    <?php endif; ?>
                    <i class="picto icon-doc doc-<?= $subdoc->getExtension() ?>"></i>
                    <strong>
                        <?= $subdoc->getFileName() ?>,
                        version <?= $subdoc->getVersion() ?></small></strong>,
                        téléversé <time><?= $this->moment($subdoc->getDateUpdoad())->since() ?></time>
                        par <span class="owner"><?= $subdoc->getPerson() ? $this->person($subdoc->getPerson()) : 'Anonymous' ?></span>
                    <?php if($downloadable): ?>
                    </a>
                    <?php endif; ?>

                </article>
                <?php endforeach; ?>
                </div>
            <?php endif; ?>
        </div>
*/ ?>

    <?php endforeach; ?>
    <?php endforeach; ?>
    <hr>
    <?php if($this->grant()->privilege(\Oscar\Provider\Privileges::ADMINISTRATIVE_DOCUMENT_NEW)): ?>
    <nav>
        <a href="<?= $this->url('administrativedocument/upload') ?>" class="btn btn-primary">Téléverser un document</a>
    </nav>
    <?php endif; ?>
</div>
<script>
    require(['jquery'], function($){
        console.log('toto');
        $('.versions').on('click', '.opener', function(e){
            $(this).parent().toggleClass('open').find('.details').toggle();
        });
    });
</script>