<div class="container">
    <h1>Téléversement d'un document administratif</h1>
    <?php if( isset($data) && $data['error'] ):?>
        <div class="alert alert-danger">
            <?= $data['error'] ?>
        </div>
    <?php endif; ?>
    <form action="" method="post" enctype="multipart/form-data">
        <div class="row">

            <div class="col-md-6">
                <label for="file">Fichier</label>
                <input type="file" class="form-control" name="file" id="file" />
            </div>

            <div class="col-md-6">
                <label for="section">Section</label>
                <select name="section_id" id="section">
                    <option value="">Général</option>
                    <?php foreach ($sections as $section): ?>
                        <option value="<?= $section->getId() ?>" <?= $defaultSection == $section->getId() ? ' selected' : '' ?>><?= $section->getLabel() ?></option>
                    <?php endforeach; ?>
                </select>

            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <label for="informations">Note</label>
                <textarea name="informations" id="informations" class="form-control" id="" cols="30" rows="10"></textarea>
            </div>
        </div>
        <div class="row">
            <div class="col-md-8 col-md-push-4">
                <div class="btn-group">
                    <a href="javascript: history.back()" class="btn btn-default">Retour à l'activité</a>
                    <button type="submit" class="btn btn-primary">Envoyer</button>

                </div>
            </div>
        </div>
    </form>
</div>

