<section class="card connector <?= $config['type'] ?>">
    <form action="" method="post" id="organization_ldap">
        <input type="hidden" name="organization_ldap">
        <h2 class="card-title">Configuration du Ldap Organization</h2>
        <class="card-content">
        <h3>Informations</h3>
        <p class="text-highlight">
            Association : <strong><?= $config['association_array'] ?></strong><br>
            Collectivité territoriale : <strong><?= $config['collectivite_array'] ?></strong><br>
            Composante : <strong><?= $config['composante_array'] ?></strong><br>
            Etablissement publique : <strong><?= $config['etablissement_array'] ?></strong><br>
            Groupement d'intérêt économique : <strong><?= $config['groupement_array'] ?></strong><br>
            Institution : <strong><?= $config['institution_array'] ?></strong><br>
            Laboratoire : <strong><?= $config['laboratoire_array'] ?></strong><br>
            Plateau technique : <strong><?= $config['plateau_array'] ?></strong><br>
            Société : <strong><?= $config['societe_array'] ?></strong><br>
        </p>
        <?php if( $config['warnings'] ): ?>
            <?php foreach( $config['warnings'] as $warning ): ?>
                <div class="alert alert-danger">
                    <?= $warning ?>
                </div>
            <?php endforeach; ?>
        <?php endif; ?>

        <h3>Paramètres</h3>

        Filtrage :
        <textarea name="ldap_filter" rows="10" cols="80"><?php
                foreach($config['ldap_filter'] as $value){
                    echo $value;
                }

            ?></textarea>

        <!--<nav>
            <button type="submit" class="btn btn-primary">Enregistrer</button>
        </nav>-->
        </div>
    </form>
</section>