<section class="card connector <?= $config['type'] ?>">
    <form action="" method="post">
    <input type="hidden" type="<?= $config['type'] ?>">
    <h2 class="card-title"><?= $config['label'] ?></h2>
    <div class="card-content">
    <h3>Informations</h3>
    <p class="text-highlight">
        Type : <strong><?= $config['type'] ?></strong><br>
        Classe : <strong><?= $config['class'] ?></strong>
    </p>
    <?php if( $config['warnings'] ): ?>
        <?php foreach( $config['warnings'] as $warning ): ?>
            <div class="alert alert-danger">
                <?= $warning ?>
            </div>
        <?php endforeach; ?>
    <?php endif; ?>
    <h3>Paramètres</h3>
    <p>Fichier : <strong><?= $config['file'] ?></strong></p>
    <?php foreach( $config['params'] as $param => $data ): ?>
        <h4><?= $param ?></h4>
        <p><?= $data['description'] ?></p>

        <section>
            <?php $composantId = uniqid('relations_person_organisation_') ?>
            <div id="<?= $composantId ?>">
                <keyselecteditor :values="values" :datas="datas" :autocomplete="autocomplete" :name="'<?= $config['type'] ?>[<?= $param ?>]'"></keyselecteditor>
            </div>
        </section>
        <script>
            require(['vue', 'KeySelectEditor'], function(Vue, KeySelectEditor){
                new Vue({
                    el: '#<?= $composantId ?>',
                    data: {
                      values: <?= json_encode($data['value']) ?>,
                        autocomplete: <?= json_encode($config['rolesRemote']) ?>,
                        datas: <?= json_encode($config['rolesOscar']) ?>
                    },
                    components: {
                        'keyselecteditor': KeySelectEditor.default
                    }
                })
            })
        </script>
    <?php endforeach; ?>
        <nav>
            <button type="submit" class="btn btn-primary">Enregistrer</button>
        </nav>
    </div>
    </form>
</section>