<section class="card connector <?= $config['type'] ?>">
    <form action="" method="post" id="<?= $config['type'] ?>">
        <input type="hidden" name="<?= $config['type'] ?>">
        <h2 class="card-title"><?= $config['label'] ?></h2>
        <class="card-content">
            <?php if( $config['warnings'] ): ?>
                <?php foreach( $config['warnings'] as $warning ): ?>
                    <div class="alert alert-danger">
                        <?= $warning ?>
                    </div>
                <?php endforeach; ?>
            <?php endif; ?>
            <h3>Paramètres</h3>
            <style>
                .inputLdapPerson{width:800px;}
            </style>
            <?php
            foreach($config['ldap_filter'] as $value){
                echo "Filtre : <input class='inputLdapPerson' type='text' value='".$value."'</input><br/>";
            }

            ?>

            <!--<nav>
                <button type="submit" class="btn btn-primary">Enregistrer</button>
            </nav>-->
        </div>
    </form>
</section>