; Niveau de log
log_errors = On

; Log envoyés dans la sortie standard (s'affiche dans les logs docker)
error_log = /dev/stderr
error_reporting = E_ALL
display_errors = On
display_startup_errors = On
log_errors_max_len = 1024
error_prepend_string = "<div style='font-family: monospaced; color: red; font-weight: bold; white-space: pre'>"
error_append_string = "</div>"

; SENDMAIL est remplacé
sendmail_path = /usr/local/bin/mhsendmail

[xdebug]
zend_extension=xdebug

; Mode debug et trace
xdebug.mode=debug
xdebug.start_with_request=yes

; IP de PHPStorm
xdebug.client_host=host.docker.internal
xdebug.client_port=9003
xdebug.idekey=PHPSTORM
xdebug.discover_client_host=true

; Afficher les logs (optionnel)
xdebug.log=/tmp/xdebug.log
xdebug.log_level=0