<div class="container">
    <section class="alert alert-danger">
    <h1>
        <i class="icon-bug"></i>
        Hum, c'est embarassant
    </h1>
    <p>Oscar a rencontré une erreur et a répondu</p>

<?php
/** @var Exception $exception */
if( $exception && $exception instanceof Oscar\Exception\OscarException ): ?>
    <div class="card card-danger"><?= $exception->getMessage() ?></div>
    <p>Si ce message ne vous aide pas, contactez l'administrateur en lui indiquant ce message.</p>
<?php else: ?>
    <pre>
        <h3 style="margin: 0"><small>Erreur : <strong><?= get_class($exception) ?></strong></small></h3>
<?php echo "EXCEPTION : $exception" ?>
> <strong><?= $exception->getMessage() ?></strong>
---
    <?php if($this->grant()->privilege(\Oscar\Provider\Privileges::MAINTENANCE_MENU_ADMIN)): ?>
<strong>Stack : </strong>
<?= $exception->getTraceAsString() ?>

    <?php endif; ?>
    </pre>
<?php endif; ?>
    </section>
</div>

