<?php

echo $this->doctype();

/*
Offsets de 1 à 10 pour la lib Unicaen.
Pour les applications de 11 à l'infini...
 */

$this->headScript();
?>

<html lang="fr">
    <head>
        <!-- Meta -->
        <meta charset="utf-8">
        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0')
                                    ->appendName('description', '')
                                    ->appendHttpEquiv("X-UA-Compatible", "IE=edge,chrome=1") ?>

        <!-- Title -->
        <?php echo $this->headTitle($this->appInfos()->nom)->setSeparator(' - ')->setAutoEscape(false) ?>

        <!-- Links -->
        <link rel="icon" type="image/png" href="<?= $this->basePath() ?>/favicon.png" />
        <link rel="stylesheet" href="<?= $this->basePath() . '/css/unicaen.css' ?>">
        <link rel="stylesheet" href="<?= $this->basePath() . '/css/fontello/css/fontello.css' ?>">
        <link rel="stylesheet" href="<?= $this->basePath() . '/css/fontello/css/animation.css' ?>">
        <?php /*if (getenv('APPLICATION_ENV') && (getenv('APPLICATION_ENV') != 'production' && getenv('APPLICATION_ENV') != 'development') ): ?>
            <link rel="stylesheet"
                  href="<?= $this->basePath() . '/css/app-beta.css' ?>">
        <?php else: ?>
        <link rel="stylesheet" href="<?= $this->basePath() . '/css/app.css' ?>">
        <?php endif;*/ ?>
        <link rel="stylesheet" href="<?= $this->basePath() . '/css/app.css' ?>">
        <link rel="stylesheet" href="<?= $this->basePath() . '/custom/custom.css' ?>">
        <?php /* echo $this->headLink(array(
            'rel'  => 'shortcut icon',
            'type' => 'image/vnd.microsoft.icon',
            'href' => '//www.unicaen.fr/images/favicon.ico')) */?>

        <!-- Scripts -->
        <script src="<?= $this->basePath() . '/js/initer.js' ?>"></script>
        <script src="<?= $this->basePath() . '/js/vendor/requirejs/require.js' ?>"></script>
        <script src="<?= $this->basePath() . '/js/oscar-config.js' ?>"></script>


        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
          <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->

        <?php if( getenv('APPLICATION_ENV') != 'production' ): ?>
            <style>/*#navbar{background-color: #330000 !important; }body {background-color: #eedddd;}*/</style>
        <?php endif; ?>
    </head>

    <body class="<?php echo getenv('APPLICATION_ENV') ?: 'development' ?>">

        <!--[if lt IE 7]>
            <p class="chromeframe">Vous utilisez un navigateur internet hors d'âge. Veuillez le mettre à jour, svp.</p>
        <![endif]-->
        <div id="navbar" class="navbar navbar-primary navbar-fixed-top" role="navigation">
            <div class="container">

                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".bs-navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <?php echo $this->appLink('<img src="/images/oscar-white.png" alt="" style="height: 32px; margin-right: 4px; position: relative; top: -3px; opacity: .5" />'.$this->appInfos()->nom) ?>
                    <?php if (getenv('APPLICATION_ENV') && getenv('APPLICATION_ENV') != 'production'): ?>
                        <span
                            class="beta-stick"><?= getenv('APPLICATION_ENV') ?></span>
                    <?php endif; ?>
                </div>

                <?php /* if( $this->isAllowed('search')): ?>
                <form action="<?= $this->url('project_search') ?>" method="get" class="navbar-form navbar-left" role="search">
                    <div class="input-group">
                        <input placeholder="Rechercher dans les projets&hellip;" type="search"
                               class="form-control"  name="q"
                               value="<?= isset($search) ? htmlentities($search) : '' ?>"/>
                        <span class="input-group-btn">
                            <button type="submit" class="btn btn-primary">Rechercher</button>
                        </span>
                    </div>
                </form>
                <?php endif; */ ?>


                <div class="navbar-collapse bs-navbar-collapse collapse">

                    <ul class="nav navbar-nav">
                    <?php if( $this->grant()->connected() ): ?>
                        <?php if( $this->grant()->isBoss() ): ?>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle"
                               data-toggle="dropdown" role="button"
                               aria-expanded="false">
                                <i class="icon-wristwatch"></i> Projets<span
                                    class="caret"></span>
                            </a>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="<?= $this->url('project/mine') ?>"><i class="icon-cubes"></i> Projets</a></li>
                                <li><a href="<?= $this->url('project/structure') ?>"><i class="icon-building-filled"></i> Par structure</a></li>
                            </ul>
                        </li>
                        <?php else: ?>
                        <li>
                            <a href="<?= $this->url('project/mine') ?>"><iclass="icon-cubes"></i> Projets</a>
                        </li>
                        <?php endif; ?>
                        <li>
                            <a href="<?= $this->url('administrativedocument') ?>"><i class="icon-book"></i> Documents</a>
                        </li>
                    <?php endif; ?>


                    <?php if ($this->grant()->privilege(\Oscar\Provider\Privileges::MAINTENANCE_MENU_ADMIN)): ?>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle"
                                   data-toggle="dropdown" role="button"
                                   aria-expanded="false">
                                    <i class="icon-wristwatch"></i> Suivi<span
                                        class="caret"></span>
                                </a>
                                <ul class="dropdown-menu" role="menu">
                                    <?php if ($this->grant()->privilege(\Oscar\Provider\Privileges::ACTIVITY_PAYMENT_SHOW)): ?>
                                    <li role="presentation" class="dropdown-header"><i class="icon-bank"></i> Versements</li>
                                    <?php /* <li><a href="<?= $this->url('contract') ?>">Tous les versements</a></li> */ ?>
                                    <li><a href="<?= $this->url('payment/income') ?>">Prochains versements</a></li>
                                    <li><a href="<?= $this->url('payment/late') ?>">Versements en retard</a></li>
                                    <li><a href="<?= $this->url('payment/difference') ?>">Écarts de paiement</a></li>
                                    <li><a href="<?= $this->url('payment') ?>">Tous les versements</a></li>
                                    <?php endif; ?>

                                    <?php if ($this->grant()->privilege(\Oscar\Provider\Privileges::ACTIVITY_MILESTONE_SHOW)): ?>
                                    <li role="presentation" class="dropdown-header"><i class="icon-calendar"></i> Jalons</li>
                                    <li><a href="<?= $this->url('milestones') ?>">Tous les jalons</a></li>
                                    <?php endif; ?>

                                    <?php if ($this->grant()->privilege(\Oscar\Provider\Privileges::ACTIVITY_INDEX)): ?>
                                    <li role="presentation" class="dropdown-header"><i class="icon-cube"></i> Activités</li>
                                    <li><a href="<?= $this->url('contract/almostdone') ?>">Bientôt terminés</a></li>
                                    <li><a href="<?= $this->url('contract/almoststart') ?>">Débutant prochainement</a></li>
                                    <?php endif; ?>
                                </ul>
                            </li>



                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                <i class="icon-cube"></i> Activités <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu" role="menu">
                                <?php if($this->grant()->privilege(\Oscar\Provider\Privileges::PROJECT_INDEX)): ?>
                                    <li role="presentation" class="dropdown-header"><i class="icon-cubes"></i> Projets</li>
                                    <li><a href="<?= $this->url('project') ?>">Liste des projets</a></li>
                                    <?php if($this->grant()->privilege(\Oscar\Provider\Privileges::PROJECT_CREATE)): ?>
                                        <li><a href="<?= $this->url('project/new') ?>">Créer un projet</a></li>
                                    <?php endif; ?>
                                <?php endif; ?>

                                <li role="presentation" class="dropdown-header"><i class="icon-cube"></i> Activités</li>
                                <li><a href="<?= $this->url('contract/advancedsearch') ?>">Liste des activités<i class="icon-asterisk"></i></a></li>
                                <li><a href="<?= $this->url('contract/new') ?>">Nouvelle activité</a></li>
                                <li><a href="<?= $this->url('contract/almostdone') ?>">Bientôt terminés</a></li>
                                <li><a href="<?= $this->url('contract/almoststart') ?>">Débutant prochainement</a></li>

                            </ul>
                        </li>
                        <?php endif; ?>

                        <?php if ($this->grant()->privilege(\Oscar\Provider\Privileges::MAINTENANCE_MENU_ADMIN)): ?><!-- Menu admin -->
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Administration <span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">

                                <?php if($this->grant()->privilege(\Oscar\Provider\Privileges::ORGANIZATION_SHOW)): ?>
                                <li role="presentation" class="dropdown-header"><i class="icon-building-filled"></i> Organisations</li>
                                <li><a href="<?= $this->url('organization') ?>">Liste des organisations</a></li>
                                <?php if($this->grant()->privileges(\Oscar\Provider\Privileges::ORGANIZATION_EDIT)): ?>
                                <li><a href="<?= $this->url('organization/new') ?>">Nouvelle organisation</a></li>
                                <li><a href="<?= $this->url('organization/fusion') ?>">Fusion d'organisations</a></li>
                                <li><a href="<?= $this->url('organization/scission') ?>">Scission d'organisations</a></li>
                                <?php endif; ?>
                                <?php endif; ?>

                                <?php if($this->grant()->privilege(\Oscar\Provider\Privileges::PERSON_INDEX)): ?>
                                <li role="presentation" class="dropdown-header"><i class="icon-group"></i> Personnes</li>
                                <li><a href="<?= $this->url('person') ?>">Liste des personnes</a></li>
                                <li><a href="<?= $this->url('person/boss') ?>">Liste des responsables</a></li>
                                    <?php if($this->grant()->privilege(\Oscar\Provider\Privileges::PERSON_EDIT)): ?>
                                    <li><a href="<?= $this->url('person/new') ?>">Ajouter une personne</a></li>
                                    <?php endif; ?>
                                <?php endif; ?>


                                <li role="presentation" class="dropdown-header"><i class="icon-cube"></i> Activités</li>
                                <li><a href="<?= $this->url('contractdocument') ?>">Liste des documents téléversé</a></li>
                                <li><a href="<?= $this->url('activitytype') ?>">Gérer les types d'activités</a></li>
                                <li><a href="<?= $this->url('datetype') ?>">Gérer les types de date</a></li>



                                <li role="presentation" class="dropdown-header"><i class="icon-stethoscope"></i> Maintenance des données</li>
                                <li><a href="<?= $this->url('contract/advancedsearch') ?>?criteria[]=pp%3Bnull%3Bnull">Activités sans projet</a></li>
                                <li><a href="<?= $this->url('project/empty') ?>">Projets sans activité</a></li>
                                <?php if( $this->grant()->privilege(\Oscar\Provider\Privileges::MAINTENANCE_CONNECTOR_ACCESS) ):?>
                                <li><a href="<?= $this->url('administration/connectors_home') ?>">Connecteurs disponibles</a></li>
                                <?php endif; ?>

                                <?php if( $this->grant()->privilege(\Oscar\Provider\Privileges::DROIT_PRIVILEGE_VISUALISATION) ): ?>
                                <li role="presentation" class="dropdown-header"><i class="icon-lock"></i> Droits et sécurités</li>
                                <li><a href="<?php echo $this->url('administration') ?>">Gestion des droits</a></li>
                                <li><a href="<?php echo $this->url('administration/users') ?>">Authentifications actives</a></li>
                                <li><a href="<?php echo $this->url('administration/organizationrole') ?>">Affectation des structures</a></li>
                                <?php endif; ?>

                                <li role="presentation" class="dropdown-header"><i class="icon-lightbulb-1"></i> A propos</li>
                                <li><a href="<?= $this->url('changelog') ?>">Quoi de neuf ?</a></li>
                            </ul>
                        </li>
                        <?php endif; ?><!-- /Menu admin -->
                    </ul>
                    <?php if( $this->grant()->connected() ): ?>
                    <p class="navbar-text navbar-right" id="notifications-area" ></p>
                    <?php endif; ?>
                    <p class="navbar-text navbar-right">
                    <?php echo $this->appConnection(); ?>
                    </p>
                </div><!--/.nav-collapse -->
            </div>
        </div>


        <div class="container flash-messages" id="flash-messages" style="opacity: 0"><?php
            $types = ['error', 'info', 'default', 'success', 'warning'];
            foreach( $types as $type ): ?>
                <?php if( $this->flashMessenger()->hasMessages($type) ): ?>
                <div class="flashmsg flashmsg-<?= $type ?>">
                    <i class="icon-<?= $type ?>"></i>
                    <i class=" icon-cancel-outline"></i>
                    <?= $this->flashMessenger()->render($type, []) ?>
                </div>
                <?php endif; ?>
            <?php endforeach; ?></div>


        <div id="contenu-principal" class="">

            <?php if (($menuSecondaire = $this->navigation()->menuSecondaire('navigation')->render())): ?>
                <div class="row">
                    <div id="sidebar" class="col-xs-6 col-md-2" role="navigation">
                        <?php echo $menuSecondaire; ?>
                    </div>
                    <div id="content" class="col-xs-12 col-md-10">
                        <?php echo $this->content; ?>
                    </div>
                </div>
            <?php else: ?>
                <?php echo $this->content; ?>
            <?php endif; ?>
        </div>

        <hr />
        <footer class="site-footer bg-primary">
            <div class="container">
                <div class="col-md-6">
                    <a href="https://www.unicaen.fr">
                        <img src="/images/logo-ucbn.png" alt="" class="footer-logo" height="20" style="display: inline"/>
                        Université de Caen Normandie (c) 2015-<?= date('Y') ?>
                    </a>
                </div>
                <div class="col-md-6">
                    <?php if( $this->grant()->privilege(\Oscar\Provider\Privileges::PERSON_INDEX) ): ?>
                    <span id="connected"></span>
                    <?php endif; ?>
                    <strong>oscar<sup>&copy</sup></strong> - <em><?= $this->appInfos()->desc ?></em>
                </div>
            </div>
        </footer>
        <a href="#" class="scrollup" title="Remonter en haut de cette page"><img alt="Remonter" src="<?php echo $this->basePath('/css/icon-top.png') ?>"/></a>
	<script>
        window.flashMessage = function(type, content){
            var message = $('<div class="flashmsg flashmsg-'+type+'">'
                +'<i class="icon-'+type+'"></i>'
                +'<i class=" icon-cancel-outline"></i>'
                +content
                +'</div>');
          $('#flash-messages').append(message.fadeIn(500));
            if( type == "success" ){
                message.delay(3000).fadeOut();
            }
        };
	(function(){
		require(['jquery'], function($){

			var reloadUi = function(){
				document.location.reload();
			};

			$('body').on('click','.user-profile-select-input', function(){
				setTimeout(reloadUi, 900);
			});

            $('#flash-messages').on('click', '.icon-cancel-outline', function(){
                $(this).parent().fadeOut();
            });


            if( !$('#flash-messages').is(':empty') ){
                $('#flash-messages .flashmsg').delay(5000).fadeOut();
                $('#flash-messages').css({'top':250, 'opacity':0}).animate({top: 60, opacity: 1});
            }
		});
	})();
	</script>

        <?php if( $this->grant()->dbUser() ): ?>
        <div id="notifications">

        </div>
        <script>
		    var socket, notifications;
	
            require(['notifications'], (notifications) => {
                notifications = new notifications.default({
                    el: '#notifications-area',
                    data: {
                        urlHistory: '<?= $this->url('notification/history') ?>'
                    },
                    http: {
                        root: '/notification'
                    },
                });
                notifications.fetch();
		<?php if( $this->grant()->hasSocket() ): ?>

            requirejs.config({ paths: {
                "io":  "/js/socket.io"
            }});
            require(['io', 'vue'], (io, Vue) => {
                socket = io('<?= $this->grant()->getSocketUrl() ?>', {
                    query: {
                        token: '<?= $this->grant()->dbUser()->getSecret() ?>'
                    }
                });
                socket.on('connect', function(){
                    console.log('Connect');
                });
                socket.on('notification', function(datas){
                    notifications.fetch();
                });
                <?php if( $this->grant()->privilege(\Oscar\Provider\Privileges::PERSON_INDEX) ): ?>
                var connected = new Vue({
                    el: "#connected",
                    data: {
                        users: []
                    },
                    template: `<section class="connected">
                        Personnes connectées :
                        <span class="cartouche xs" v-for="u in users">
                            {{ u }}
                        </span>
                    </section>`
                })
                socket.on('users', function(datas){
                    console.log('USERS', datas);
                    connected.users = datas;
                });
                <?php endif; ?>
                socket.on('disconnect', function(){
                    console.log('disconnect');
                });
            });
            <?php endif; ?>
            });
        </script>
        <?php endif; ?>
    </body>
</html>
