<?php
/**
 * Created by PhpStorm.
 * User: bouvry
 * Date: 04/10/19
 * Time: 11:49
 */

namespace Oscar\Command;


use Oscar\Formatter\OscarFormatterConst;
use Oscar\Service\OscarConfigurationService;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Zend\ServiceManager\ServiceManager;

class OscarCommandDevTestCommand extends OscarAdvancedCommandAbstract
{
    protected static $defaultName = 'dev:test';

    protected function configure()
    {
        $this
            ->setDescription("Test pour le développement")
        ;
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        parent::execute($input, $output); // TODO: Change the autogenerated stub
        foreach ($this->getPersonService()->getAvailableRolesPersonActivity(OscarFormatterConst::FORMAT_ARRAY_ID_OBJECT) as $key=> $value){
            echo "$key => " . $value->getRoleId() . "\n";
        }
        return 0;
    }

}