<div class="container">

    <?php if( !$person ): ?>
        <h1>&nbsp;</h1>
        <div class="alert alert-warning">
            Vous n'êtes pas référencé dans Oscar. Contactez l'administrateur si le problème persiste.
        </div>
    <?php else: ?>
    <link rel="stylesheet" href="/js/oscar/dist/personautocompleter.css" />
    <div class="container">
        <div id="app"></div>
    </div>
    <script>
        requirejs(['vue', 'vue-resource', 'ActivitySearchUi', 'VueFilters', 'mm'], function(Vue, VueResource, ActivitySearchUi, VueFilters, moment){

            Vue.use(VueResource);

            Vue.filter('slugify', VueFilters.default.slugify);
            Vue.filter('money', function(dbl){
                return dbl.toFixed(2);
            });

            Vue.filter('fullDate', function(text){
                var d = moment(text);
                return d.format("dddd, D MMMM YYYY") + " (" + d.fromNow() + ")";
            });

            new Vue({
                render: function (h) {
                    return h(ActivitySearchUi.default, {
                        props: {
                            url: '<?= $this->url('contract/api') ?>',
                            first: true,
                            title: '<?= $this->translate("Mes activités de recherche") ?>'
                        }
                    })
                }
            }).$mount('#app');
        });
    </script>
    <?php endif; ?>
</div>
