<?php
/**
 * @author Stéphane Bouvry<stephane.bouvry@unicaen.fr>
 * @date: 17-12-12 08:27
 * @copyright Certic (c) 2017
 */
?>
<style>
    .line {
        background: white;
        margin-bottom: 4px;
        padding: 2px 4px;
        display: flex;
        align-content: flex-start;
        align-items: flex-start;
    }
    .line > * {
        font-size: .8em;
        padding: .25em;
        flex: 2;
    }
    .hash {
        flex: 1;
        text-align: center;
        font-family: Courier Consolas monospace;
        background: #0b58a2; color: white; border-radius: 4px; text-shadow: -1px 1px 1px rgba(0,0,0,.3);
    }
    .author {
        color: #0b58a2;
        font-weight: bold;
    }
    .line time {
        color: #3d4e56;
        font-weight: 100;
    }
    .author:before {
        content: "Auteur : ";
        color: #3c3c3c;
        font-weight: 100;
    }
    .message {
        flex: 15;
        font-size: 1em;
    }
</style>
<div class="container">
    <h1>Historique des builds et des changements</h1>
    <?php foreach ($log as $line): ?>
        <div class="line"><?= $line ?></div>
    <?php endforeach; ?>

</div>
