<?php
/**
 * @author Stéphane Bouvry<stephane.bouvry@unicaen.fr>
 * @date: 17-12-12 08:27
 * @copyright Certic (c) 2017
 */
?>
<style>
    .line {
        background: white;
        margin-bottom: 4px;
        padding: 2px 4px;
        display: flex;
        align-content: flex-start;
        align-items: flex-start;
    }
    .line > * {
        font-size: .8em;
        padding: .25em;
        flex: 2;
    }
    .hash {
        flex: 1;
        text-align: center;
        font-family: Courier Consolas monospace;
        background: #0b58a2; color: white; border-radius: 4px; text-shadow: -1px 1px 1px rgba(0,0,0,.3);
    }
    .author {
        color: #0b58a2;
        font-weight: bold;
    }
    .line time {
        color: #3d4e56;
        font-weight: 100;
    }
    .author:before {
        content: "Auteur : ";
        color: #3c3c3c;
        font-weight: 100;
    }
    .message {
        flex: 15;
        font-size: 1em;
    }
</style>
<div class="container">
    <?php if($error): ?>
        <?= $error ?>
    <?php else: ?>
    <h1>
        <strong><?php echo $log['app'] ?></strong>
        <em>"<?php echo $log['name'] ?>" (v<?php echo $log['version'] ?>)</em>
    </h1>
    <h2>
        Branch: <code><?php echo $log['branch'] ?></code>,<br>
        Hash: <code><?php echo $log['commitHash'] ?></code>,<br>
        Update: <code><?php echo $log['dateUpdate'] ?></code>
    </h2>
    <h3>Historique des builds et des changements</h3>
    <?php foreach ($log['logs'] as $l) : ?>
    <div class="line">
        <code class="hash" title="<?= $l['commit'] ?>"><?= $l['commit_short'] ?></code>
        <span class="author"><?= $l['author'] ?></span>
        <time class="date"><?= $l['date'] ?></time>
        <span class="message"><?= $l['message'] ?></span>
    </div>
    <?php endforeach; ?>
    <?php endif; ?>

</div>
