<div class="container">
    <header>
        <h1><i class="icon-cube"></i> Activités
            <strong><?= $filterLabel ?></strong></h1>
    </header>
    <form action="?" method="get">
        <span class="input-group">
            <?= $this->partial('partials/filter-persons.phtml', ['selectedPersons' => $persons]) ?>
            <span class="input-group-btn">
                <button type="submit" class="btn btn-primary">
                    <i class="icon-cw-outline"></i> Actualiser
                </button>
            </span>
        </span>
    </form>
    <section>
        <?php
        $currentDate = null;
        /** @var \Oscar\Entity\Activity $contract */
        foreach( $entities as $entity):
            $date = $this->moment($entity->$getDateGroup())->since() . ' <small>(' . $this->moment($entity->$getDateGroup()) .')</small>';
            if( $date !== $currentDate ){
                $currentDate = $date;
                echo "<h3>$datePrefix $currentDate</h3>";
            }
            echo $this->partial('/oscar/project-grant/item-list.phtml', ['activity' => $entity])
            ?>
        <?php endforeach;?>
    </section>
</div>