<?php
/**
 * @author Stéphane Bouvry<stephane.bouvry@unicaen.fr>
 * @date: 16/10/15 13:41
 * @copyright Certic (c) 2015
 */
?>
<link rel="stylesheet" type="text/css"
      href="<?= $this->basePath() . '/js/vendor/bootstrap-datepicker/dist/css/bootstrap-datepicker3.min.css' ?>" />
<div class="container">
    <h1>
        <?php if($activity->getProject()): ?>
            <small class="text-light">
                <i class="icon-cubes"></i>
                <?= $activity->getProject() ?>
            </small><br/>
        <?php endif; ?>
        <?php if( $activity->getId() ): ?>
            <strong><i class="icon-cube"></i> <?= $activity->getLabel() ?></strong> (Modification)
        <?php else: ?>
            <strong><i class="icon-cube"></i> <?= $this->translate("Nouvelle activité") ?></strong>
        <?php endif; ?>
    </h1>

    <pre>
        <?php var_dump($headers) ?>
    </pre>
    <div class="form">
        <h3>
            <i class="icon-info-circled"></i>
            <?= $this->translate("Informations") ?>
        </h3>
        <?= $this->form()->openTag($form->prepare()); ?>

        <table class="table table-bordered card xs">
            <thead>
            <tr>
                <th title="Numéro de colonne de le fichier d'export">N°</th>
                <th>Champ PCRU</th>
                <th>Géré</th>
                <th>Valide</th>
                <th>Valeur envoyée</th>
                <th>Informations</th>
            </tr>
            </thead>

            <tbody>
                <tr>
                    <th>1</th>
                    <td>Objet</td>
                    <td><i class="icon-ok-circled"></td>
                    <td>VALID ?</td>
                    <td><?= $this->formInput($form->get('objet')); ?></td>
                    <td><?= $headers['Objet'] == 'off' ? 'Non géré' : $headers['Objet']  ?></td>
                </tr>

                <tr>
                    <th>2</th>
                    <td>CodeUniteLabintel</td>
                    <td><i class="icon-ok-circled"></td>
                    <td>VALID ?</td>
                    <td><?= $this->formInput($form->get('codeunitelabintel')); ?></td>
                    <td><?= $headers['CodeUniteLabintel'] == 'off' ? 'Non géré' : $headers['CodeUniteLabintel']  ?></td>
                </tr>

                <tr>
                    <th>3</th>
                    <td>SigleUnite</td>
                    <td><i class="icon-ok-circled"></td>
                    <td>VALID ?</td>
                    <td><?= $this->formInput($form->get('sigleunite')); ?></td>
                    <td><?= $headers['SigleUnite'] == 'off' ? 'Non géré' : $headers['SigleUnite']  ?></td>
                </tr>

                <tr>
                    <th>4</th>
                    <td>NumContratTutelleGestionnaire</td>
                    <td><i class="icon-ok-circled"></td>
                    <td>VALID ?</td>
                    <td><?= $this->formInput($form->get('numcontrattutellegestionnaire')); ?></td>
                    <td><?= $headers['NumContratTutelleGestionnaire'] == 'off' ? 'Non géré' : $headers['NumContratTutelleGestionnaire']  ?></td>
                </tr>

                <tr>
                    <th>5</th>
                    <td>Equipe</td>
                    <td><i class="icon-ok-circled"></td>
                    <td>VALID ?</td>
                    <td><?= $this->formInput($form->get('equipe')); ?></td>
                    <td><?= $headers['Equipe'] == 'off' ? 'Non géré' : $headers['Equipe']  ?></td>
                </tr>

                <tr>
                    <th>6</th>
                    <td>TypeContrat</td>
                    <td><i class="icon-ok-circled"></td>
                    <td>VALID ?</td>
                    <td><?= $this->formSelect($form->get('typecontrat')); ?></td>
                    <td><?= $headers['TypeContrat'] == 'off' ? 'Non géré' : $headers['TypeContrat']  ?></td>
                </tr>

                 <tr>
                    <th>7</th>
                    <td>Acronyme</td>
                    <td><i class="icon-ok-circled"></td>
                    <td>VALID ?</td>
                    <td><?= $this->formInput($form->get('acronyme')); ?></td>
                     <td><?= $headers['Acronyme'] == 'off' ? 'Non géré' : $headers['Acronyme']  ?></td>
                </tr>

                <tr>
                    <th>8</th>
                    <td>ContratsAssocies</td>
                    <td><i class="icon-ok-circled"></td>
                    <td>VALID ?</td>
                    <td><?= $this->formInput($form->get('contratsassocies')); ?></td>
                    <td><?= $headers['ContratsAssocies'] == 'off' ? 'Non géré' : $headers['ContratsAssocies']  ?></td>
                </tr>
                <tr>
                    <th>9</th>
                    <td>ResponsableScientifique</td>
                    <td><i class="icon-ok-circled"></td>
                    <td>VALID ?</td>
                    <td><?= $this->formSelect($form->get('responsablescientifique')); ?></td>
                    <td><?= $headers['ResponsableScientifique'] == 'off' ? 'Non géré' : $headers['ResponsableScientifique']  ?></td>
                </tr>
                <tr>
                    <th>10</th>
                    <td>EmployeurResponsableScientifique</td>
                    <td><i class="icon-ok-circled"></td>
                    <td>VALID ?</td>
                    <td><?= $this->formInput($form->get('employeurresponsablescientifique')); ?></td>
                    <td><?= $headers['EmployeurResponsableScientifique'] == 'off' ? 'Non géré' : $headers['EmployeurResponsableScientifique']  ?></td>
                </tr>
                <tr>
                    <th>11</th>
                    <td>CoordinateurConsortium</td>
                    <td><i class="icon-ok-circled"></td>
                    <td>VALID ?</td>
                    <td><?= $this->formInput($form->get('coordinateurconsortium')); ?></td>
                    <td><?= $headers['CoordinateurConsortium'] == 'off' ? 'Non géré' : $headers['CoordinateurConsortium']  ?></td>
                </tr>
                <tr>
                    <th>12</th>
                    <td>Partenaires</td>
                    <td><i class="icon-ok-circled"></td>
                    <td>VALID ?</td>
                    <td><?= $this->formInput($form->get('partenaires')); ?></td>
                    <td><?= $headers['Partenaires'] == 'off' ? 'Non géré' : $headers['Partenaires']  ?></td>
                </tr>
                <tr>
                    <th>13</th>
                    <td>PartenairePrincipal</td>
                    <td><i class="icon-ok-circled"></td>
                    <td>VALID ?</td>
                    <td><?= $this->formSelect($form->get('partenaireprincipal')); ?></td>
                    <td><?= $headers['PartenairePrincipal'] == 'off' ? 'Non géré' : $headers['PartenairePrincipal']  ?></td>
                </tr>
                <tr>
                    <th>14</th>
                    <td>IdPartenairePrincipal</td>
                    <td><i class="icon-ok-circled"></td>
                    <td>VALID ?</td>
                    <td><?= $this->formInput($form->get('idpartenaireprincipal')); ?></td>
                    <td><?= $headers['IdPartenairePrincipal'] == 'off' ? 'Non géré' : $headers['IdPartenairePrincipal']  ?></td>
                </tr>
                <tr>
                    <th>15</th>
                    <td>SourceFinancement</td>
                    <td><i class="icon-ok-circled"></td>
                    <td>VALID ?</td>
                    <td>
                        <?= $this->formSelect($form->get('sourcefinancement')); ?>
                    </td>
                    <td><?= $headers['SourceFinancement'] == 'off' ? 'Non géré' : $headers['SourceFinancement']  ?></td>
                </tr>
                <tr>
                    <th>16</th>
                    <td>LieuExecution</td>
                    <td><i class="icon-ok-circled"></td>
                    <td>VALID ?</td>
                    <td><?= $this->formInput($form->get('lieuexecution')); ?></td>
                    <td><?= $headers['LieuExecution'] == 'off' ? 'Non géré' : $headers['LieuExecution']  ?></td>
                </tr>

                <tr>
                    <th>17</th>
                    <td>DateDerniereSignature</td>
                    <td><i class="icon-ok-circled"></td>
                    <td>VALID ?</td>
                    <td><?= $this->formInput($form->get('datedernieresignature')); ?></td>
                    <td><?= $headers['DateDerniereSignature'] == 'off' ? 'Non géré' : $headers['DateDerniereSignature']  ?></td>
                </tr>

                <tr>
                    <th>18</th>
                    <td>Duree</td>
                    <td><i class="icon-ok-circled"></td>
                    <td>VALID ?</td>
                    <td><?= $this->formInput($form->get('duree')); ?></td>
                    <td><?= $headers['Duree'] == 'off' ? 'Non géré' : $headers['Duree']  ?></td>
                </tr>

                <tr>
                    <th>19</th>
                    <td>DateDebut</td>
                    <td><i class="icon-ok-circled"></td>
                    <td>VALID ?</td>
                    <td><?= $this->formInput($form->get('datedebut')); ?></td>
                    <td><?= $headers['DateDebut'] == 'off' ? 'Non géré' : $headers['DateDebut']  ?></td>
                </tr>

                <tr>
                    <th>20</th>
                    <td>DateFin</td>
                    <td><i class="icon-ok-circled"></td>
                    <td>VALID ?</td>
                    <td><?= $this->formInput($form->get('datefin')); ?></td>
                    <td><?= $headers['DateFin'] == 'off' ? 'Non géré' : $headers['DateFin']  ?></td>
                </tr>

                <tr>
                    <th>21</th>
                    <td>MontantPercuUnite</td>
                    <td><i class="icon-ok-circled"></td>
                    <td>VALID ?</td>
                    <td><?= $this->formInput($form->get('montantpercuunite')); ?></td>
                    <td><?= $headers['MontantPercuUnite'] == 'off' ? 'Non géré' : $headers['MontantPercuUnite']  ?></td>
                </tr>

                <tr>
                    <th>22</th>
                    <td>CoutTotalEtude</td>
                    <td><i class="icon-ok-circled"></td>
                    <td>VALID ?</td>
                    <td><?= $this->formInput($form->get('couttotaletude')); ?></td>
                    <td><?= $headers['CoutTotalEtude'] == 'off' ? 'Non géré' : $headers['CoutTotalEtude']  ?></td>
                </tr>

                <tr>
                    <th>23</th>
                    <td>MontantTotal</td>
                    <td><i class="icon-ok-circled"></td>
                    <td>VALID ?</td>
                    <td><?= $this->formInput($form->get('montanttotal')); ?></td>
                    <td><?= $headers['MontantTotal'] == 'off' ? 'Non géré' : $headers['MontantTotal']  ?></td>
                </tr>
                <tr>
                    <th>24</th>
                    <td>DateDebut</td>
                    <td><i class="icon-ok-circled"></td>
                    <td>VALID ?</td>
                    <td><?= $this->formInput($form->get('datedebut')); ?></td>
                    <td><?= $headers['DateDebut'] == 'off' ? 'Non géré' : $headers['DateDebut']  ?></td>
                </tr>
                <tr>
                    <th>25</th>
                    <td>PoleCompetivite</td>
                    <td><i class="icon-ok-circled"></td>
                    <td>VALID ?</td>
                    <td><?= $this->formSelect($form->get('polecompetivite')); ?></td>
                    <td><?= $headers['PoleCompetivite'] == 'off' ? 'Non géré' : $headers['PoleCompetivite']  ?></td>
                </tr>
                <tr>
                    <th>25</th>
                    <td>ValidePoleCompetivite</td>
                    <td><i class="icon-ok-circled"></td>
                    <td>VALID ?</td>
                    <td><?= $this->formCheckbox($form->get('validepolecompetivite')); ?></td>
                    <td><?= $headers['ValidePoleCompetivite'] == 'off' ? 'Non géré' : $headers['ValidePoleCompetivite']  ?></td>
                </tr>
                <tr>
                    <th>26</th>
                    <td>Commentaires</td>
                    <td><i class="icon-ok-circled"></td>
                    <td>VALID ?</td>
                    <td><?= $this->formTextarea($form->get('commentaires')); ?></td>
                    <td><?= $headers['Commentaires'] == 'off' ? 'Non géré' : $headers['Commentaires']  ?></td>
                </tr>
                <tr>
                    <th>27</th>
                    <td>Pia</td>
                    <td><i class="icon-ok-circled"></td>
                    <td>VALID ?</td>
                    <td><?= $this->formCheckbox($form->get('pia')); ?></td>
                    <td><small>Est PIA ?</small></td>
                </tr>
                <tr>
                    <th>28</th>
                    <td>Reference</td>
                    <td><i class="icon-ok-circled"></td>
                    <td>VALID ?</td>
                    <td><?= $this->formInput($form->get('reference')); ?></td>
                    <td><?= $headers['Reference'] == 'off' ? 'Non géré' : $headers['Reference']  ?></td>
                </tr>
                <tr>
                    <th>29</th>
                    <td>AccordCadre</td>
                    <td><i class="icon-ok-circled"></td>
                    <td>VALID ?</td>
                    <td><?= $this->formCheckbox($form->get('accordcadre')); ?></td>
                    <td><?= $headers['AccordCadre'] == 'off' ? 'Non géré' : $headers['AccordCadre']  ?></td>
                </tr>

                <tr>
                    <th>30</th>
                    <td>Cifre</td>
                    <td><i class="icon-ok-circled"></td>
                    <td>VALID ?</td>
                    <td><?= $this->formCheckbox($form->get('cifre')); ?></td>
                    <td><?= $headers['Cifre'] == 'off' ? 'Non géré' : $headers['Cifre']  ?></td>
                </tr>
                <tr>
                    <th>31</th>
                    <td>ChaireIndustrielle</td>
                    <td><i class="icon-ok-circled"></td>
                    <td>VALID ?</td>
                    <td><?= $this->formInput($form->get('chaireindustrielle')); ?></td>
                    <td><?= $headers['ChaireIndustrielle'] == 'off' ? 'Non géré' : $headers['ChaireIndustrielle']  ?></td>
                </tr>
                <tr>
                    <th>32</th>
                    <td>PresencePartenaireIndustriel</td>
                    <td><i class="icon-ok-circled"></td>
                    <td>VALID ?</td>
                    <td><?= $this->formCheckbox($form->get('presencepartenaireindustriel')); ?></td>
                    <td><?= $headers['PresencePartenaireIndustriel'] == 'off' ? 'Non géré' : $headers['PresencePartenaireIndustriel']  ?></td>
                </tr>
            </tbody>

        </table>




        <?= $this->form()->closeTag() ?>
    </div>
    <hr>
</div>
<script>
    Initer.ready(function(){
        require(['select2'], function(){
            $('[name="activityType"], .select2').select2();
        });

        require(['Keyvalue'], function(KeyValue){
            console.log(KeyValue);
        });
    })
</script>
