<div class="container">
    <h2>
        <i class="icon-leaf"></i> Activité
    </h2>

    <ul class="activity">
        <li>
            <time datetime="2015-06-29">29 juillet 2015</time>
            <strong class="user">Christophe Turbout</strong>
            a validé la feuille de temps de
            <strong class="user">Stéphane Bouvry</strong></li>
        <li><strong class="user">Stéphane Bouvry</strong> a soumis sa feuille de temps pour juillet</li>
    </ul>

</div>

<style>

</style>

<script src="<?= $this->basePath('/js/vendor/jquery/dist/js/jquery.min.js') ?>"></script>
<script src="<?= $this->basePath('/js/vendor/select2/dist/js/select2.full.min.js') ?>"></script>
<script src="<?= $this->basePath('/js/vendor/handlebars/handlebars.min.js') ?>"></script>



<link href="<?= $this->basePath('/js/vendor/select2/dist/css/select2.min.css') ?>" rel="stylesheet"/>
<link href="<?= $this->basePath('/css/select2-bootstrap.css') ?>" rel="stylesheet"/>
<link href="<?= $this->basePath('/css/fontello/css/fontello.css') ?>" rel="stylesheet"/>
