<?php
/**
 * Created by PhpStorm.
 * User: bouvry
 * Date: 07/01/19
 * Time: 17:34
 */
?>
<link rel="stylesheet" href="<?= $this->basePath().'/js/oscar/dist/datepicker.css' ?>">
<link rel="stylesheet" href="<?= $this->basePath().'/js/oscar/dist/datepicker.css' ?>">

<section class="container">
    <div id="app"></div>
</section>

<script>
    require(['vue', 'vue-resource', 'Datepicker2', 'mm', 'ActivityRequestAdmin'], function( Vue, VueResource, Datepicker2, moment, ActivityRequestAdmin) {
        Vue.use(VueResource);
        Vue.component('datepicker', Datepicker2.default);
        Vue.filter('renderStatus', function(s){
           switch(s){
               case 1 : return "Brouillon";
               case 2 : return "Envoyé";
               case 5 : return "Validée";
               case 7 : return "Refusé";
               default: return 'Statut ' + s + ' inconnue';
           }
        });
        Vue.filter('date', function(s){
            return moment(s).format('dddd D MMMM YYYY')
        });
        Vue.filter('montant', function(d){
            return d.toFixed(2);
        });
        new Vue({
            el: '#app',
            render: function(h){
                return h(ActivityRequestAdmin.default, { props: {
                    moment: moment,
                    rolesPerson: <?= json_encode($rolesPerson) ?>,
                    rolesOrganisation: <?= json_encode($rolesOrganisation) ?>,
                    asAdmin: <?= $asAdmin ?>,
                    title: "<?= $this->translate("Gérer les demandes d'activité") ?>"
                }})
            }
        })
    })
</script>
