<link rel="stylesheet" href="/js/oscar/dist/personautocompleter.css" />
<div class="container">
    <div id="app"></div>
</div>
<script>
    requirejs(['vue', 'vue-resource', 'ActivitySearchUi', 'VueFilters', 'mm'], function(Vue, VueResource, ActivitySearchUi, VueFilters, moment){

        Vue.use(VueResource);

        Vue.filter('slugify', VueFilters.default.slugify);
        Vue.filter('money', function(dbl){
            return dbl.toFixed(2);
        });

        Vue.filter('fullDate', function(text){
            if( text ) {
                var d = moment(text);
                return d.format("dddd, D MMMM YYYY") + " (" + d.fromNow() + ")";
            } else {
                return "Pas de date";
            }
        });

        new Vue({
            render: function (h) {
                return h(ActivitySearchUi, {
                    props: {
                        url: '<?= $this->url('contract/api') ?>',
                        sortters: <?= json_encode($sorts) ?>,
                        filters: <?= json_encode($filters) ?>,
                        directions: <?= json_encode($directions) ?>,
                        direction: <?= json_encode($direction) ?>,
                        sorter: <?= json_encode($sorter) ?>,
                        status: <?= json_encode($status) ?>,
                        roles_person: <?= json_encode($roles_person) ?>,
                        roles_organizations: <?= json_encode($roles_organizations) ?>,
                        options_pays: <?= json_encode($options_pays) ?>,
                        used_filters: <?= json_encode($used_filters) ?>,
                        used_status: <?= json_encode($used_status) ?>,
                        search: <?= json_encode($search) ?>
                    }
                })
            }
        }).$mount('#app');
    });
</script>
