<?php
/**
 * Created by PhpStorm.
 * User: bouvry
 * Date: 11/06/19
 * Time: 11:48
 */


function renderLine( $line, $years, $level = 1 ){
    $id = $line['id'];
    if( count($line['children']) > 0 ){
        $out = "<tr class='level-$level'>";
        $out .= "<th class='heading'>";
        $out .= $line['label'];
        $out .= "</th>";
        foreach ($years as $year) {
            $out .= "<th> &nbsp;</th>";
        }
        $out .= "<th>TOTAL</th>";
        $out .= "</tr>";

        foreach ($line['children'] as $l) {
            $out .= renderLine($l, $years, $level+1);
        }


    } else {
        $out = "<tr class='computed'>";
        $out .= "<th class='heading'>";
        $out .= $line['label'];
        $out .= "</th>";
        foreach ($years as $year) {
            $name = "spent[$year][$id]";
            $out .= "<td><input type='text' name='$name' placeholder='0.0' /></td>";
        }
        $out .= "<td>0.0</td>";
        $out .= "</tr>";

    }

    return $out;

}
?>
<style>
    .level-1 {
        font-size: 2em;
    }
    .level-2 {
        padding-left: 1em;
        font-size: 1.6em;
    }
    .computed .heading {
        padding-left: 2em;
    }
</style>
<div class="container-fluid">
    <h1>Dépenses prévisionnelles</h1>
    <div id="app">APP</div>
    <script>
        require(['vue', 'vue-resource', 'EstimatedSpentActivity', 'EstimatedSpentActivityItem'], function(Vue, VueResource,EstimatedSpentActivity, EstimatedSpentActivityItem){
            Vue.component('estimatedspentactivityitem', EstimatedSpentActivityItem.default);
            var v = new Vue({
                'render': function(h){
                    return h(EstimatedSpentActivity.default, { props: { years: <?= json_encode($years) ?>, types: <?= json_encode($types) ?>}});
                }
            });

            v.$on('*', function(){
                console.log('bar !');
            });

            v.$mount('#app');

        })
    </script>

</div>
