<?php
/**
 * @author Stéphane Bouvry<stephane.bouvry@unicaen.fr>
 * @date: 16/10/15 13:41
 * @copyright Certic (c) 2015
 */
?>
<link rel="stylesheet" type="text/css"
      href="<?= $this->basePath() . '/js/vendor/bootstrap-datepicker/dist/css/bootstrap-datepicker3.min.css' ?>" />
<div class="container">
    <h1>
        <?php if($activity->getProject()): ?>
            <small class="text-light">
                <i class="icon-cubes"></i>
                <?= $activity->getProject() ?>
            </small><br/>
        <?php endif; ?>
        <?php if( $activity->getId() ): ?>
            <strong><i class="icon-cube"></i> <?= $activity->getLabel() ?></strong> (Modification)
        <?php else: ?>
        <strong><i class="icon-cube"></i> <?= $this->translate("Nouvelle activité") ?></strong>
        <?php endif; ?>
    </h1>
    <div class="form">
        <h3>
            <i class="icon-info-circled"></i>
            <?= $this->translate("Informations") ?>
        </h3>
        <?= $this->form()->openTag($form->prepare()); ?>
        <?= $this->formControlGroup($form->get('label')); ?>
        <?= $this->formControlGroup($form->get('description')); ?>


        <?php if( $withOrganization ): ?>
            <h3><?= $this->translate("Rôle de votre structure") ?></h3>
            <?php if($errorRoles): ?>
            <p class="alert alert-danger"><?= $errorRoles ?></p>
            <?php endif; ?>
            <p class="alert alert-info">
                <?= ngettext("Choisissez un rôle pour votre structure.", "Choisisser au moins un rôle pour une de vos structures", count($organizations)) ?><br>
            </p>
            <?php foreach ($withOrganization as $org): ?>
                <label for="organization[<?= $org->getId() ?>]"><?= $org ?></label>
                <select name="roles[<?= $org->getId() ?>]" >
                    <option value=""></option>
                    <?php foreach ($organizationRoles as $id=>$roleOrganization): ?>
                        <option value="<?= $id ?>"><?= $roleOrganization ?></option>
                    <?php endforeach; ?>
                </select>
            <?php endforeach; ?>
        <?php endif; ?>

        <h3><?= $this->translate("Données administratives") ?></h3>

        <div class="row">
            <div class="col-md-3">
                <?php echo $this->formLabel($form->get('codeEOTP'));?>
                <?php echo $this->formInput($form->get('codeEOTP'));?>
                <?php echo $this->formElementErrors($form->get('codeEOTP'), ["class" => "alert alert-danger"]); ?>
            </div>
            <div class="col-md-3">
                <?php echo $this->formLabel($form->get('status'));?>
                <?php echo $this->formSelect($form->get('status'));?>
                <?php echo $this->formElementErrors($form->get('status')); ?>
            </div>
            <div class="col-md-3">
                <?php echo $this->formLabel($form->get('activityType'));?>
                <?php /* echo $this->formSelect($form->get('activityType')); */?>
                <div id="activityType"></div>
                <script>
                    require(["vue", "vue-resource", "activitytypeselector", "activitytypeitem"], function(Vue, VueResource, ActivityTypeSelector, ActivityTypeItem){
                        Vue.use(VueResource);
                        Vue.component('activity-type-item', ActivityTypeItem);

                        new Vue({
                            el: "#activityType",
                            render: function(e) {
                                return e(ActivityTypeSelector, { props: {
                                        initialSelected: "<?= $activity && $activity->getActivityType() ? $activity->getActivityType()->getId() : '' ?>",
                                        allowNodeSelection: <?= $allowNodeSelection ? 'true' : 'false' ?>,
                                        inputName: "activityType",
                                        typesAvailable: <?= json_encode($tree) ?>
                                    } });
                            }
                        });
                    })
                </script>
                <?php echo $this->formElementErrors($form->get('activityType')); ?>
            </div>
            <div class="col-md-3">
                <?php if( !in_array('disciplines', $hidden)): ?>
                <?php echo $this->formLabel($form->get('disciplines'));?>
                <?php echo $this->formSelect($form->get('disciplines'));?>
                <?php echo $this->formElementErrors($form->get('disciplines')); ?>
                <?php endif; ?>
            </div>
        </div>

        <h3><?= $this->translate("Informations financières") ?></h3>
        <div class="row">
                <div class="col-md-4">
                    <?= $this->formControlGroup($form->get('financialImpact')); ?>
                </div>
                <div class="col-md-4">
                    <?= $this->formControlGroup($form->get('amount')); ?>
                </div>
                <div class="col-md-4">
                    <?= $this->formControlGroup($form->get('currency')); ?>
                </div>

            </div>
        <div class="row">
            <div class="col-md-4">
                <?= $this->formControlGroup($form->get('tva')); ?>

                <?= $this->formControlGroup($form->get('pcruPoleCompetitivite')); ?>
                <?= $this->formControlGroup($form->get('pcruValidPoleCompetitivite')); ?>

                <?= $this->formControlGroup($form->get('pcruSourceFinancement')); ?>
            </div>
            <div class="col-md-4">
                <?php if( !in_array('fraisDeGestion', $hidden)): ?>

                    <div><?php echo $this->formLabel($form->get('fraisDeGestion'));?></div>
                    <div class="help-message">
                        <i class="icon-help-circled"></i>
                        Vous pouvez saisir un montant (ex 237.25) ou un pourcentage en ajoutant le symbole <strong>%</strong> (ex: 3.75%)
                    </div>
                    <?php echo $this->formInput($form->get('fraisDeGestion'));?>
                    <?php echo $this->formElementErrors($form->get('fraisDeGestion')); ?>

                    <?= $this->formControlGroup($form->get('fraisDeGestionPartHebergeur')); ?>
                <?php endif; ?>
            </div>
            <div class="col-md-4">
                <?= $this->formControlGroup($form->get('assietteSubventionnable')); ?>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <?= $this->formControlGroup($form->get('noteFinanciere')); ?>
            </div>
        </div>



        <div class="row">
            <div class="col-md-6">
                <h3>Dates clefs</h3>
                <div><?php echo $this->formLabel($form->get('dateStart'));?></div>
                <?php echo $this->formInput($form->get('dateStart'));?>
                <?php echo $this->formElementErrors($form->get('dateStart')); ?>

                <div><?php echo $this->formLabel($form->get('dateEnd'));?></div>
                <?php echo $this->formInput($form->get('dateEnd')); ?>
                <?php echo $this->formElementErrors($form->get('dateEnd')); ?>
                <div><?php echo $this->formLabel($form->get('dateSigned'));?></div>
                <?php echo $this->formInput($form->get('dateSigned')); ?>
                <?php echo $this->formElementErrors($form->get('dateSigned')); ?>
                <div><?php echo $this->formLabel($form->get('dateOpened'));?></div>
                <?php echo $this->formInput($form->get('dateOpened'));?>
                <?php echo $this->formElementErrors($form->get('dateOpened')); ?>
            </div>
            <div class="col-md-6">
                <h3><?= $this->translate("Numérotation") ?></h3>
                <?php echo $this->keyvalue($form->get('numbers'));?>
                <?php echo $this->formElementErrors($form->get('numbers')); ?>
            </div>
        </div>

        <?= $this->formHidden($form->get('id')); ?>
        <div class="text-center">
            <nav class="btn-group">
                <a class="btn btn-default" href="javascript:history.back()">
                    <i class="icon-angle-left"></i>
                    Retour
                </a>
                <button class="btn btn-primary" type="submit">
                    <i class="icon-floppy"></i>
                    <?= $this->translate("Enregistrer") ?></button>
            </nav>
        </div>
        </datalist>
        <?= $this->form()->closeTag() ?>
    </div>
    <hr>
</div>
<script>
    Initer.ready(function(){
        require(['select2'], function(){
            $('.select2').select2();
        });

        require(['Keyvalue'], function(KeyValue){
            console.log(KeyValue);
        });
    })
</script>