<?php
/**
 * @author Stéphane Bouvry<stephane.bouvry@unicaen.fr>
 * @date: 14/09/15 10:45
 * @copyright Certic (c) 2015
 */
?>
<section class="container">

    <h1><i class="icon-cube"></i>Activités de recherche</h1>

    <form action="<?= $this->url() ?>" method="get" class="form" id="search">
        <div class="input-group input-group-lg">
            <input placeholder="Rechercher dans l'intitulé, code PFI...&hellip;"
                   type="search"
                   class="form-control input-lg"
                   name="q"
                   value="<?= htmlentities($search) ?>"/>

                <span class="input-group-btn">
                    <button type="button" class="btn btn-default"
                            id="filters-btn"><i class="icon-cog"></i></button>
                    <button type="submit" class="btn btn-primary">Rechercher</button>
                </span>
        </div>

        <div id="filters">
            <h4><i class="icon-sliders"></i>Filtres</h4>
            <div class="row">
                <div class="col-md-3">
                    <h5>Personne</h5>
                    <select name="persons[]"
                            id="persons"
                            data-url="<?= $this->url('person/search') ?>"
                            multiple>
                        <?php foreach ($filterPersons as $person): ?>
                            <option value="<?= $person->getId() ?>"
                                    selected><?= $person ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
                <div class="col-md-3">
                    <h5>Statut des activités</h5>
                    <select placeholder="Choississez un status"
                            name="filter_status[]" class="select2 form-control"
                            id="filter_status" multiple="multiple">
                        <?php foreach (\Oscar\Entity\Activity::getStatusSelect() as $value => $label): ?>
                            <option
                                value="<?= $value ?>"<?= (in_array($value, $filterStatus) ? ' selected="selected"' : '') ?>><?= $label ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
                <div class="col-md-3">
                    <h5>Type d'activités</h5>
                    <select placeholder="Choississez un status"
                            name="filter_type[]"
                            class="select2 form-control" id="filter_status"
                            multiple="multiple">
                        <?php foreach ($types as $id => $label): ?>
                            <option
                                value="<?= $id ?>"<?= (in_array($id, $filterType) ? ' selected="selected"' : '') ?>><?= $label ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
                <div class="col-md-3">
                    <h5>Année(s)</h5>
                    <select placeholder="Année(s)" name="filter_year[]"
                            class="form-control" id="filter_year" multiple="">
                        <?php foreach ($filterYear as $year) : ?>
                            <option value="<?= $year ?>"
                                    selected="selected"><?= $year ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
            </div>

            <div class="row">

                <div class="col-md-3">
                    <h5>Date</h5>
                    <select name="datefilter_type" class="select2 form-control">
                        <option value="">&hellip;</option>
                    <?php foreach ($sorts as $k => $v) : ?>
                        <option
                            value="<?= $k ?>" <?= $datefilter_type == $k ? 'selected="selected"' : '' ?>><?= $v ?>
                        </option>
                    <?php endforeach; ?>
                    </select>
                </div>
                <div class="col-md-3">
                    <h5>Entre le</h5>
                    <input type="text" class="datepicker" name="datefilter_from" value="<?= $datefilter_from ?>" />
                </div>
                <div class="col-md-3">
                    <h5>et le</h5>
                    <input type="text" class="datepicker" name="datefilter_to" value="<?= $datefilter_to ?>" />
                </div>
                <div class="col-md-3">
                    ---
                </div>
            </div>


            <div class="row">
                <div class="col-md-6">
                    <h4><i class="icon-sort-numeric-outline"></i>Trie</h4>
                    <div class="input-group input-group-sm">
                        <select placeholder="Année(s)" name="sort"
                                class="form-control" id="sort">
                            <?php foreach ($sorts as $k => $v) : ?>
                                <option
                                    value="<?= $k ?>" <?= $sort == $k ? 'selected="selected"' : '' ?>><?= $v ?></option>
                            <?php endforeach; ?>
                        </select>


                            <span class="input-group-btn">

                                <a href="#"
                                   class="btn btn-default direction-<?= $sortDirection ?>"
                                   id="direction">
                                    <i class="icon-angle-down">Croissant</i>
                                    <i class="icon-angle-up">Décroissant</i>
                                </a>

                                <input type="hidden" name="sortDirection"
                                       value="<?= $sortDirection ?>"
                                       id="directionInput"/>
                            </span>
                    </div><!-- /input-group -->
                </div>

                <div class="col-md-6">
                    <h4><i class="icon-pin-outline"></i>Critères mémorisés</h4>
                    <span class="input-group input-group-sm">
                        <select id="criteria" class="form-control"></select>
                        <span class="input-group-btn">
                            <button type="button"
                                    class="btn btn-default disabled"
                                    title="Supprimer ces critères"
                                    id="delete-current">
                                <i class="icon-trash"></i>
                            </button>
                            <button type="button" class="btn btn-default"
                                    id="save-search">
                                <i class="icon-cw-outline"></i>
                                Enregistrer les critères
                            </button>
                        </span>
                    </span>
                </div>
            </div>
            <div class="row" style="text-align: right; padding-top: 1em">
                <a href="<?= $this->url() ?>" class="btn btn-default">
                    <i class="icon-cancel-outline"></i>
                    Remettre à zéro
                </a>
                <button type="submit" class="btn btn-primary">
                    <i class="icon-cw-outline"></i>
                    Appliquer
                </button>
            </div>
        </div>
    </form>

    <?php
    if ($contracts->size() > 0): ?>
    <h3 class="text-center"><?= count($contracts) ?> résultat(s)</h3>

    <?php /** @var \Oscar\Entity\Activity $contract */
    foreach( $contracts as $contract):
        echo $this->partial('/oscar/project-grant/item-list.phtml', ['activity' => $contract])
        ?>
    <?php endforeach;?>


    <?= $this->pager($contracts, preg_replace("/\\??&page=[0-9]*/", '', $_SERVER['REQUEST_URI']) . '?&page=%s') ?>

        <?php if ($this->grant(\Oscar\Provider\Privileges::ACTIVITY_EXPORT)): ?>
            <nav class="btn-group">
                <a href="<?= $this->url('contract/csv') ?>?ids=<?= $exportIds ?>"
                   class="btn btn-primary">
                    <i class="icon icon-export-outline"></i>
                    Exporter en CSV
                </a>
                <a href="#" class="btn btn-primaru">
                    Exporter la selection
                </a>
            </nav>
        <?php endif; ?>
    <?php else: ?>
        <hr/>
        <div class="alert-info alert">

            <?php if ($search == 'Pourquoi la vie, l\'univers et le reste ?'): ?>
                <h1 style="text-align: center; font-size: 72px">42</h1>
            <?php elseif ($search == '42'): ?>
                <small>Vous avez trouvé la réponse à la grande question sur la
                    vie, l'univers et le reste... Peut-être que votre question
                    est mal posée...
                </small>
            <?php else: ?>
                <p>Aucun résultat</p>
            <?php endif; ?>
        </div>
    <?php endif; ?>
    <script>
        /**
         * Fonction de mise en forme du choix proposé dans l'auto-compléteur.
         *
         * @param repo
         * @returns {*}
         */
        formatRepo = function (repo) {
            if (repo.loading) return repo.text;

            var markup = '<div class="clearfix">';
            markup += repo.label || repo.text;
            markup += '</div>';

            return markup;
        };

        /**
         * Fonction de mise en forme de la donnée choisie.
         *
         * @param repo
         * @returns {*}
         */
        formatRepoSelection = function (repo) {
            return repo.label || repo.text;
        };

        Initer.ready(function(){
            require(['select2', 'bootbox'], function (select2, bootbox) {

                $('#direction').on('click', function(e){
                    e.preventDefault();
                    if($(this).hasClass('direction-desc')){
                        $(this).addClass('direction-asc').removeClass('direction-desc');
                        $('#directionInput').val('asc');
                    } else {
                        $(this).addClass('direction-desc').removeClass('direction-asc');
                        $('#directionInput').val('desc');
                    }
                });
                $('.select2').select2();
                $('#filter_year').select2({
                    tags: true
                })

                // Compéteur de person
                $('#persons').select2({
                    placeholder: 'Rechercher...',
                    width: '100%',
                    allowClear: true,
                    ajax: {
                        url: $('#persons').data('url'),
                        dataType: 'json',
                        delay: 250,
                        data: function (params) {
                            return {
                                q: params.term, // search term
                                page: params.page
                            };
                        },
                        processResults: function (data, page) {
                            console.log(data);
                            return {results: data.datas};
                        },
                        cache: true
                    },
                    escapeMarkup: function (markup) {
                        return markup;
                    },
                    minimumInputLength: 3,
                    id: function (dt) {
                        return dt.uid;
                    },
                    templateResult: formatRepo, // omitted for brevity, see the source of this page
                    templateSelection: formatRepoSelection // omitted for brevity, see the source of this page
                });

                //$('#persons').val([{'id': '3059', label: 'James Bond'}]).trigger("change")
                <?php if( !$displayFilters ): ?>
                $('#filters').hide();
                <?php endif; ?>

                $('#filters-btn').on('click', function () {
                    $('#filters').slideToggle();
                });

                if (!window.localStorage) {
                    $('#save-search').hide();
                }
                else {
                    var saved = localStorage.getItem('activity_criteria'),
                        criteria = $('#criteria'),
                        btnDelete = $('#delete-current'),
                        form = $('#search');

                    if (!saved) {
                        saved = [];
                    } else {
                        saved = JSON.parse(saved);
                    }

                    criteria.on('change', function () {
                        if (criteria.val()) {
                            document.location = form.attr('action') + criteria.val();
                        }
                    });

                    /**
                     * Affiche les critères de recherche mémorisés dans la
                     * combobox.
                     */
                    var drawCriteria = function () {
                        // La recherche en cours
                        var current = document.location.search,
                            selected;
                        criteria.empty();
                        criteria.append('<option></option>');
                        saved.forEach(function (item) {
                            selected = '';
                            if (current == item.url) {
                                selected = " selected";
                                btnDelete.removeClass('disabled')
                            }
                            criteria.append('<option value="' + item.url + '"' + selected + '>' + item.label + '</option>');
                        });
                    };

                    btnDelete.on('click', function () {
                        var newItems = [];
                        saved.forEach(function (item) {
                            if (item.url != criteria.val()) {
                                newItems.push(item);
                            }
                        });
                        saved = newItems;
                        localStorage.setItem('activity_criteria', JSON.stringify(saved));
                        drawCriteria();
                    });

                    // Sauvegarde des critères de recherche
                    $('#save-search').on('click', function () {
                        var url = '?' + form.serialize();

                        bootbox.prompt({
                            title: "Nom pour le filtre",
                            value: criteria.find('option[selected]').text(),
                            callback: function (result) {
                                if (result === null) {
                                    console.log('Canceled');
                                } else {
                                    var override = false;
                                    saved.forEach(function (item) {
                                        if (item.label == result) {
                                            item.url = url;
                                            override = true;
                                        }
                                    });
                                    if (!override) {
                                        saved.push({
                                            label: result,
                                            url: url
                                        });
                                    }
                                    localStorage.setItem('activity_criteria', JSON.stringify(saved));
                                    drawCriteria();
                                }
                            }
                        });
                    });
                    drawCriteria();
                }
            });
        });
    </script>
    <script>
        (function () {
            Initer.ready(function () {
                require(['datepicker', 'select2'], function () {
                    $.fn.modal.Constructor.prototype.enforceFocus = function () {
                    };
                    $('.datepicker').datepicker({
                        format: "yyyy-mm-dd",
                        todayBtn: "linked",
                        clearBtn: true,
                        language: "fr",
                        autoclose: true,
                        toggleActive: true
                    });

                    if ($('.select2').length === 0) {
                        return;
                    }
                })
            });
        })('<?= $id ?>')

    </script>
</section>