<?php
/**
 * @author Stéphane Bouvry<stephane.bouvry@unicaen.fr>
 * @date: 14/09/15 10:45
 * @copyright Certic (c) 2015
 */
?>
<section class="container">
    <h1><i class="icon-cube"></i> Activités de recherche <strong>sans
            projet</strong></h1>

    <form action="?" method="get">
        <span class="input-group">
            <?= $this->partial('partials/filter-persons.phtml', ['selectedPersons' => $persons]) ?>
            <span class="input-group-btn">
                <button type="submit" class="btn btn-primary">
                    <i class="icon-cw-outline"></i> Actualiser
                </button>
            </span>
        </span>
    </form>

    <h3 class="text-center"><?= count($contracts) ?> résultat(s)</h3>

    <?php /** @var \Oscar\Entity\Activity $contract */
    foreach( $contracts as $contract):
        echo $this->partial('/oscar/project-grant/item-list.phtml', ['activity' => $contract])
        ?>
    <?php endforeach;?>


    <?= $this->pager($contracts, preg_replace("/\\??&page=[0-9]*/", '', $_SERVER['REQUEST_URI']) . '&page=%s') ?>

</section>