<div class="container">
    <h1>Activités PCRU</h1>
    <p class="alert alert-info">
        Les activités présentes dans cet écran sont soumises à un processus PCRU.<br>
        Pour activer le processus PCRU d'un activité, rendez-vous sur la fiche activité, puis dans l'encart PCRU, cliquez sur <strong>informations PCRU</strong>, une fois dans le récapitulatif des informations, cliquez sur <strong>Activer PCRU</strong>
    </p>
    <?php if(count($pcruInfos) == null): ?>
    <div class="alert alert-warning">
        Aucun processus PCRU en cours
    </div>
    <?php endif; ?>
</div>