<div class="container">
    <h1>
        Activités PCRU
    </h1>
    <!-- <div id="recherche"></div> -->
    <p class="alert alert-info">
        Les activités présentes dans cet écran sont soumises à un processus PCRU.<br>
        Pour activer le processus PCRU d'un activité, rendez-vous sur la fiche activité, puis dans l'encart PCRU, cliquez sur <strong>informations PCRU</strong>, une fois dans le récapitulatif des informations, cliquez sur <strong>Activer PCRU</strong>
    </p>
    <?php if(count($pcruInfos) == null): ?>
    <div class="alert alert-warning">
        Aucun processus PCRU en cours
    </div>
    <?php else: ?>
    <section>
        <?php
        /** @var \Oscar\Entity\ActivityPcruInfos $pcruInfo */
        foreach ($pcruInfos as $pcruInfo): ?>
        <article class="card xs">
            <h3>
                <strong><?= $pcruInfo->getAcronyme() ?></strong>
                <em><?= $pcruInfo->getObjet() ?></em>
                <span class="cartouche">
                    <?= $pcruInfo->getStatus() ?>
                    <?= $pcruInfo->getStatusStr() ?>
                </span>
                <a href="<?= $this->url('contract/show', ['id' => $pcruInfo->getActivity()->getId()]) ?>">Voir la fiche activité</a>
        </article>
        <?php endforeach; ?>
    </section>

    <nav>

        <?php if( $downloadable == true): ?>
            <a href="?a=download" class="btn btn-primary">
                <i class="icon-download"></i>
                Télécharger les fichiers pour PCRU
            </a>
        <?php else: ?>
            <div class="alert alert-info">Il n'y a aucun documents PCRU en attente</div>
        <?php endif; ?>

        <?php if( $uploadable == true): ?>
        <form action="" method="post">
            <button value="upload" name="action" class="btn btn-primary">
                <i class="icon-upload"></i>
                Uploader les fichiers vers PCRU
            </button>
        </form>
        <?php else: ?>
            <div class="alert alert-info">Un processus PCRU est déjà en cours</div>
        <?php endif; ?>

        <?php if( $hasready == true): ?>
        <form action="" method="post">
            <button value="activate" name="action" class="btn btn-primary">
                <i class="icon-upload"></i>
                Ajouter au prochain upload les infos prêtes
            </button>
        </form>
        <?php endif; ?>

    </nav>


    <?php endif; ?>
    <?php /* <script>
        require(['vue', 'vue-resource', 'createprocessuspcru'], function(Vue,VueResource,CreateProcessusPCRU){
            new Vue({
                render(h){
                    return h(CreateProcessusPCRU, { props: {
                        urlSearchActivities: '?a=search',
                        urlActivityPCRUCreate: '?a=create',
                        urlPreviewPCRU: '?a=preview'
                        }})
                }
            }).$mount('#recherche')
        })
    </script>
    /****/ ?>

</div>