<?php /****/ ?>
<link rel="stylesheet" href="/js/certic-ui-components/build/DatepickerField.css">
<div class="container">
    <header>
        <h1>Informations PCRU</h1>
        <h3><?= $activity ?></h3>
    </header>

    <div id="app" style="visibility: hidden">
        <div class="">

            <?= $this->form()->openTag($form->prepare()); ?>
            <?= $this->formControlGroup($form->get('id')); ?>

            <section class="">
                <h2>
                    <i class="icon-info-circled"></i>
                    Informations générales
                </h2>

                <fieldset>
                    <div class="row">
                        <div class="col-md-2">
                            <?= $this->formControlGroup($form->get('acronyme')); ?>
                        </div>
                        <div class="col-md-10">
                            <?= $this->formControlGroup($form->get('objet')); ?>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-3">
                            <label for="dateDerniereSignature">Date de signature</label>
                            <datepicker-field :name="'dateDerniereSignature'" />
                        </div>
                        <div class="col-md-3">
                            <?= $this->formControlGroup($form->get('dateDebut')); ?>
                        </div>
                        <div class="col-md-3">
                            <?= $this->formControlGroup($form->get('dateFin')); ?>
                        </div>
                        <div class="col-md-3">
                            <?= $this->formControlGroup($form->get('duree')); ?>
                        </div>
                    </div>
                </fieldset>



            </section>

            <label for="datestart">Date de début</label>
            <datepicker-field :name="'datestart'" />
        </div>
    </div>
<?php /*



    <section class="">
        <h2>
            <i class="icon-info-circled"></i>
            Informations générales
        </h2>
        <fieldset disabled>
            <div class="row">
                <div class="col-md-2">
                    <?= $this->formControlGroup($form->get('acronyme')); ?>
                </div>
                <div class="col-md-10">
                    <?= $this->formControlGroup($form->get('objet')); ?>
                </div>
            </div>
            <div class="row">
                <div class="col-md-3">
                    <?= $this->formControlGroup($form->get('dateDerniereSignature')); ?>
                </div>
                <div class="col-md-3">
                    <?= $this->formControlGroup($form->get('dateDebut')); ?>
                </div>
                <div class="col-md-3">
                    <?= $this->formControlGroup($form->get('dateFin')); ?>
                </div>
                <div class="col-md-3">
                    <?= $this->formControlGroup($form->get('duree')); ?>
                </div>
            </div>
        </fieldset>
    </section>

    <section>
        <h2>
            <i class="icon-building-filled"></i>
            Unité/structure référente
        </h2>
        <div class="row">
            <div class="col-md-6">
                <?= $this->formControlGroup($form->get('codeUniteLabintel')); ?>
            </div>
            <div class="col-md-6">
                <?= $this->formControlGroup($form->get('sigleUnite')); ?>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <?= $this->formControlGroup($form->get('equipe')); ?>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <?= $this->formControlGroup($form->get('numContratTutelleGestionnaire')); ?>
                <p class="help">N° du suivi pour l'unité référente</p>
            </div>
        </div>
    </section>

    <section>
        <h2>
            <i class="icon-user"></i>
            Responsables
        </h2>
        <div class="row">
            <div class="col-md-8">
                <?= $this->formControlGroup($form->get('responsableScientifique')); ?>
            </div>
            <div class="col-md-4">
                <?= $this->formControlGroup($form->get('coordinateurConsortium')); ?>
            </div>
        </div>
    </section>

    <section>
        <h2>
            <i class="icon-calculator"></i>
            Financements
        </h2>

        <div class="row">
            <div class="col-md-4">
                <?= $this->formControlGroup($form->get('montantPercuUnite')); ?>
            </div>
            <div class="col-md-4">
                <?= $this->formControlGroup($form->get('coutTotalEtude')); ?>
            </div>
            <div class="col-md-4">
                <?= $this->formControlGroup($form->get('montantTotal')); ?>
            </div>
        </div>

        <div class="row">
            <div class="col-md-8">
                <?= $this->formControlGroup($form->get('poleCompetivite')); ?>
            </div>
            <div class="col-md-4">
                <?= $this->formControlGroup($form->get('validePoleCompetivite')); ?>
            </div>
        </div>

    </section>








    <?= $this->formControlGroup($form->get('typeContrat')); ?>
    <?= $this->formControlGroup($form->get('contratsAssocies')); ?>



    <?= $this->formControlGroup($form->get('employeurResponsableScientifique')); ?>
    <?= $this->formControlGroup($form->get('partenaires')); ?>
    <?= $this->formControlGroup($form->get('partenairePrincipal')); ?>
    <?= $this->formControlGroup($form->get('idPartenairePrincipal')); ?>
    <?= $this->formControlGroup($form->get('sourceFinancement')); ?>
    <?= $this->formControlGroup($form->get('lieuExecution')); ?>






    <?= $this->formControlGroup($form->get('commentaires')); ?>
    <?= $this->formControlGroup($form->get('pia')); ?>
    <?= $this->formControlGroup($form->get('reference')); ?>
    <?= $this->formControlGroup($form->get('accordCadre')); ?>
    <?= $this->formControlGroup($form->get('cifre')); ?>
    <?= $this->formControlGroup($form->get('chaireIndustrielle')); ?>
    <?= $this->formControlGroup($form->get('presencePartenaireIndustriel')); ?>


    <div>
        <a class="btn btn-default" href="<?= $this->url('contract/show', ['id' => $activity->getId()]) ?>">
            <i class="icon-cancel-circled"></i>
            Revenir à la fiche activité
        </a>
        <button class="btn btn-primary">
            <i class="icon-floppy"></i>
            Enregistrer les informations
        </button>
    </div>
    <?= $this->form()->closeTag(); ?>
****/ ?>


    <script>
        require(["vue"
                , '../js/certic-ui-components/build/PasswordField.umd'
                , '../js/certic-ui-components/build/TextareaField.umd'
                , '../js/certic-ui-components/build/DatepickerField.umd'
            ],

            function(Vue, PasswordField, TextareaField, DatepickerField){

                Vue.component('passwordfield', PasswordField);
                Vue.component('textarea-field', TextareaField);
                Vue.component('datepicker-field', DatepickerField);

                new Vue({
                    el: "#app",
                    data:{
                        foo: "Bar",
                        passvalue: "mon mot de passe",
                        datestart: ""
                    }
                })

                document.querySelector('#app').style.visibility = 'visible';
            })

    </script>

</div>
