<?php
/**
 * Created by PhpStorm.
 * User: bouvry
 * Date: 10/12/18
 * Time: 16:08
 */


/*
?>
<div class="container">

    <?php if( $success): ?>
    <p class="alert alert-success"><?= $success ?></p>
    <?php else: ?>

    <form action="" method="post" class="form" enctype="multipart/form-data">
        <h1>
            <i class="icon-cube"></i>
            <?= _("Demande d'activité") ?>
        </h1>


        <div class="">
            <label for="label"><?= _('Intitilé') ?></label>
            <input type="text" name="label" placeholder="<?= _('Intitulé') ?>" id="label" class="form-control input-lg">
        </div>

        <div class="">
            <label for="description"><?= _('Description') ?></label>
            <textarea name="description" id="description" class="form-control" placeholder="<?= _('description') ?>"></textarea>
        </div>




        <div class="row">
            <div class="col-md-4">
                <label for="">Demandeur</label>
                <br>
                <span class="cartouche">
                <?= $demandeur ?>
                    <span class="addon">
                    Demandeur
                </span>
            </span>
            </div>
            <div class="col-md-4">
                <label for="">Organisme</label>
                <?php if( count($organizations) == 1): ?>
                    <?php foreach ($organizations as $id=>$label): ?>
                        <span class="cartouche">
                    <?= $label ?>
                        <span class="addon">
                        Organisme référent
                    </span>
                        <input type="hidden" name="organisation_id" value="<?= $id ?>" />
                    <?php endforeach; ?>
                    </span>
                <?php elseif ( count($organizations) == 0 ): ?>
                    <p class="alert-info alert">Aucune organisation identifiée</p>
                <?php else: ?>
                    <p class="form-help help">
                        Spécifier l'organisme impliqué
                    </p>
                    <select name="organisation_id" class="form-control">
                        <?php foreach ($organizations as $id=>$label): ?>
                            <option value="<?= $id ?>"><?= $label ?></option>
                        <?php endforeach; ?>
                    </select>
                <?php endif; ?>
            </div>
            <div class="col-md-4">
                <label for="">Montant</label>
                <p class="form-help help">
                    Spécifier le montant attendu/prévu
                </p>
                <input type="text" name="amount" value="" class="form-control" />

            </div>
        </div>

        <div>
            <label for="">Fichiers</label>
            <div id="fichiers"></div>
        </div>

        <nav>
            <button type="submit" class="btn btn-primary">Soumettre</button>
        </nav>


    </form>
    <style>
        .dropzone {
            border-radius: 4px;
            background: white;
            padding: 8px;
            text-align: center;
            min-height: 150px;
            border: #9da4ab solid 4px;
            color: #9da4ab;
            display: flex;
            align-items: center;
            justify-content: center;
            position: relative;
        }
        .dropzone .message {
            font-size: 1em;
            font-weight: 400;
            pointer-events: none;
            position: absolute;
        }
        .dropzone .message > [class*="icon-"] {
            font-size: 4em;
            display: block;
        }

        .dropzone.hover {
            border-color: #0b93d5;
            color: #0b93d5;
        }

        .dropzone section {
            position: relative;
            z-index: 5;
        }

        .dropzone section article {
            text-align: left;
            border: #9da4ab solid 1px;
            background: rgba(255,255,255,.5);
            padding: .3em .5em;
            margin: .5em;
        }
    </style>
    <script>
        require(['vue'], function(Vue){
            new Vue({
                el: "#fichiers",
                data: {
                    fichiers: [],
                    hover: false
                },
                methods: {
                    handlerDrop(e){
                        console.log(e);
                        if (e.dataTransfer.items) {
                            // Use DataTransferItemList interface to access the file(s)
                            for (var i = 0; i < e.dataTransfer.items.length; i++) {
                                // If dropped items aren't files, reject them
                                if (e.dataTransfer.items[i].kind === 'file') {
                                    var file = e.dataTransfer.items[i].getAsFile();
                                    console.log(file);
                                    this.fichiers.push({
                                        name: file.name,
                                        type: file.type,
                                        size: file.size
                                    });
                                }
                            }
                        } else {
                            // Use DataTransfer interface to access the file(s)
                            for (var i = 0; i < e.dataTransfer.files.length; i++) {
                                var file = e.dataTransfer.files[i];
                                console.log(file);
                                this.fichiers.push(file);
                            }
                        }
                        this.hover = false;
                        e.preventDefault();
                    },
                    handlerDragOver(e){
                        console.log(e);
                        this.hover = true;
                        e.preventDefault();
                    },
                    handlerDragLeave(e){
                        console.log(e);
                        this.hover = false;
                        e.preventDefault();
                    },

                    handlerRemove(file){
                        console.log(file.name);
                        this.fichiers.splice(this.fichiers.indexOf(file), 1);
                    },

                    handlerFileChange(e){
                        console.log(e);
                        this.fichiers = [];

                        for( let i=0; i<e.target.files.length; i++ ){
                            console.log(e.target.files[i]);
                            this.fichiers.push(e.target.files[i]);
                        }
//                        this.fichiers.push(e.target.files);
                    }
                },

                filters: {
                    ext(s){
                        return s.replace(/(.*)\.(.*)/g, '$2')
                    }
                },

                template: `<!--<div @drop="handlerDrop" @dragover="handlerDragOver" @dragleave="handlerDragLeave" class="dropzone" :class="{'hover': hover}">-->
                <div class="dropzone">
                    <div class="box__input">
                        <input class="box__file" type="file" name="files[]" id="file" data-multiple-caption="{count} files selected" multiple @change="handlerFileChange"/>
                        <label for="file"><strong>Choose a file</strong><span class="box__dragndrop"> or drag it here</span>.</label>
                    </div>
<!--
                    <section>
                        <article v-for="f in fichiers" class="doc" :class="f.name.replace(/(.*)\\.(.*)/g, 'doc-$2')">
                            <strong> {{ f.name }}</strong>
                            <em>{{ f.size }}</em> ~
                            <a href="" @click.prevent="handlerRemove(f)">
                                <i class="icon-cancel-alt"></i>
                            </a>

                        </article>
                    </section>-->
                    <span class="message" style="display: none">
                        <i class="icon-down-outline"></i>
                        Fichiers joins</span>
                </div>`
            })
        });
    </script>
    <?php endif; ?>
</div>
*/ ?>
<section class="container">
    <div id="app"></div>
</section>
<script>
    require(['vue', 'vue-resource','mm', 'ActivityRequest'], function( Vue, VueResource, moment, ActivityRequest) {
        Vue.use(VueResource);
        Vue.filter('date', function(s){
           return moment(s).format('dddd D MMMM YYYY')
        });
        new Vue({
            el: '#app',
            render: function(h){
                return h(ActivityRequest.default)
            }
        })
    })
</script>
