<?php
/**
 * Created by PhpStorm.
 * User: bouvry
 * Date: 10/12/18
 * Time: 16:08
 */
?>
<link rel="stylesheet" href="<?= $this->basePath().'/js/oscar/dist/datepicker.css' ?>">
<section class="container">
    <div id="app"></div>
</section>
<script>
    require(['vue', 'vue-resource', 'Datepicker2', 'mm', 'ActivityRequest'], function( Vue, VueResource, Datepicker2, moment, ActivityRequest) {
        Vue.use(VueResource);
        Vue.component('datepicker', Datepicker2.default);
        Vue.filter('date', function(s){
           return moment(s).format('dddd D MMMM YYYY')
        });
        Vue.filter('montant', function(d){
            return d.toFixed(2);
        });
        new Vue({
            el: '#app',
            render: function(h){
                return h(ActivityRequest.default, { props: { moment: moment }})
            }
        })
    })
</script>
