<div class="container">
    <h1>membres</h1>
    <article class="activity" id="activityPersons"></article>
</div>

<script>
    require(['vue', 'vue-resource', 'ActivityPersons'], function(Vue, VueResource, ActivityPersons){
        Vue.use(VueResource);
        new Vue({
            el: "#activityPersons",
            render(h){
                return h(ActivityPersons.default, {props: { url: '/activites-de-recherche/persons/2' }})
            }
        })

    })
</script>


