<section class="container">
    <h1>Envoi d'un contrat à signer</h1>
    <?php $form->prepare(); ?>
    <?= $this->form()->openTag($form); ?>

    <h3>Signataires</h3>
    <section>
        <?php foreach ($defaultPersons as $p): ?>
        <label for="person_<?= $p['id'] ?>" class="form-control">
            <input type="checkbox" name="persons[]" value="<?= $p['id'] ?>" id="person_<?= $p['id'] ?>"/>
            <?= $p['label'] ?>
            <small>
                (<?= implode(', ', $p['roles_ids']) ?>)
            </small>
        </label>

        <?php endforeach; ?>
    </section>

    <?= $this->formControlGroup($form->get('file')); ?>
    <pre>
        <?php var_dump($defaultPersons); ?>
    </pre>
    <nav class="text-center">
        <div class="btn-group">

                <a class="btn btn-danger" href="<?= $this->url('contract/show', ['id' => $activity->getId()]) ?>">
                    <i class="icon-cancel-alt"></i>
                    Retour à la fiche
                </a>
            <button type="submit" class="btn btn-success">
                Enregistrer
            </button>
        </div>
    </nav>
    <?= $this->form()->closeTag(); ?>
</section>