
<section class="container-fluid">
    <h1>Dépenses pour <strong><?= $activity->getCodeEOTP() ?></strong> (<?= $activity ?>)</h1>
    <?php if( count($spents) ): ?>
        <div id="spentlines"></div>
        <script>
            require(['vue', 'vue-resource', 'SpentLinePFI'], function(Vue, VueResource, SpentLinePFI){
                console.log("DONE");
                Vue.use(VueResource);
                new Vue({
                    el: "#spentlines",
                    render(h){
                        return h(SpentLinePFI.default, { props: {
                                url: "<?= $this->url('spent/activity-api', ['id' => $activity->getId()]) ?>"
                            }});
                    }

                });
            })
        </script>

    <?php if($msg): ?>
        <div class="alert alert-info"><?= $msg ?></div>
    <?php endif; ?>
    <?php if($error): ?>
        <div class="alert alert-danger"><?= $error ?></div>
    <?php endif; ?>
    <?php else: ?>
        <form action="" method="post">
            <button type="submit" name="action" value="update">Synchroniser</button>
        </form>
    <?php endif; ?>

</section>