<style>
    .personcard {
        border: thin #dddddd solid;
        padding: 2px;
    }
    .personcard .personcard-header{
        display: flex;
        margin: 0;
    }
    .personcard .personcard-gravatar{
        display: block;
        max-width: 40px;
        float: left;
    }
    .personcard .personcard-infos{
        padding-left: .33em;
    }
    .personcard .personcard-infos .icon-mail{
        opacity: .5;
    }

    .personcard.button {
        background: #eee;
        vertical-align: center;
        text-align: center;
        padding: 1em;
        cursor: pointer;
        margin: 1em 0;
    }
    .personcard.button:hover {
        background: #0b97c4;
        vertical-align: center;
        text-align: center;
    }

    .validators-todo span:after {
        content: ', ';
    }
    .validators-todo span:last-child:after {
        content: '';
    }


    .synthesis {
        border-bottom: thin solid #333;
        display: flex;
        font-weight: 100;
    }

    .synthesis > * {
        flex: 1;
        text-align: right;
        vertical-align: center;
    }

    .synthesis .label-line {
        flex: 2;
    }

    synthesis .group {
        display: flex;
    }
    synthesis .group > * {
        flex: 1;
    }

    .synthesis .research {
        background: #b5dae0;
    }

    .synthesis .abs {
        background: #d5e3b1;
    }

    .synthesis .other {
        background: #d6b4e4;
    }

    .synthesis .education {
        background: #a5e2c6;
    }

    .synthesis .total {
        font-weight: 500;
    }

    .synthesis.heading .total {
        font-weight: 500;
    }

    .synthesis .value {
        padding: .25em;
        display: block;
        border-left: thin solid rgba(255,255,255,.5);
    }

    .heading.sum .value, .heading.sum .total{
        font-weight: bold;
    }

</style>
<div class="container">
    <h1>
        Feuille de temps pour
        <strong><?= $activity ?></strong>
        <a href="<?= $this->url('contract/show', ['id' => $activity->getId()]) ?>" class="btn btn-default">
            <i class="icon-cube"></i>
            Revenir sur la fiche
        </a>
    </h1>
    <div>
        <small>
            du <strong><?= $this->moment($activity->getDateStart()) ?></strong>
            au <strong><?= $this->moment($activity->getDateEnd()) ?></strong>
        </small>
    </div>

    <?php if($activity->isTimesheetAllowed()): ?>
    <section>
        <h2>
            <i class="icon-calendar"></i>
            Synthèse
        </h2>

        <div id="synthesis"></div>

        <script>
            require(['vue', 'vue-resource', 'timesheetactivitysynthesis'], function(Vue, VueResource, TimesheetActivitySynthesis){
                Vue.use(VueResource);
                new Vue({
                    el: '#synthesis',
                    render(h){
                        return h(TimesheetActivitySynthesis, { props: {
                            url: '<?= $this->url('timesheet/synthesisactivitybounds', ['id' => $activity->getId()]) ?>'
                        }})
                    }
                })
            })
        </script>
    </section>

    <section>
        <h2>
            <i class="icon-archive"></i>
            Lots de travail
        </h2>
        <div id="workpackages"></div>
        <?php
        if ($this->grant()->privilege(\Oscar\Provider\Privileges::ACTIVITY_WORKPACKAGE_SHOW, $activity)): ?>
            <script>
                require(['vue', 'vue-resource', 'bootbox', 'workpackageui'], function (Vue, VueResource, Bootbox, Workpackage) {

                    Vue.use(VueResource);

                    Vue.http.options.emulateJSON = true;
                    Vue.http.options.emulateHTTP = true;

                    Vue.filter('heures', function (v) {
                        var heures = parseInt(v);
                        var minutes = Math.round((parseFloat(v) - heures) * 60);
                        if (minutes == 0) minutes = '';
                        else if (minutes < 10) minutes = ':0' + minutes;
                        else minutes = ':' + minutes
                        return heures + minutes;
                    });

                    new Vue({
                        render: function (h) {
                            return h(Workpackage, {
                                props: {
                                    url: '<?= $this->url(
                                        'workpackage/rest',
                                        ['idactivity' => $activity->getId()]
                                    ) ?>',
                                    isValidateur: true,
                                    editable: true,
                                    Bootbox: Bootbox,
                                }
                            })
                        },
                        el: '#workpackages'
                    }).$mount()
                });
            </script>
        <?php endif; ?>
        <div id="validators"></div>
        <script>
            require(['vue', 'vue-resource', 'activityvalidator'], function(Vue, VueResource, ActivityValidator){
                Vue.use(VueResource);
                new Vue({
                    el: '#validators',
                    render: function(h){
                        return h(ActivityValidator);
                    }
                });
            })
        </script>
    </section>
    <?php else: ?>
    <section>
        <div class="alert alert-danger">
            <p>Vous ne pouvez pas gérer les feuilles de temps de cette activité : </p>
            <ul>
                <?php foreach ($activity->getNoTimesheetReason() as $message): ?>
                <li><?= $message ?></li>
                <?php endforeach; ?>
            </ul>
        </div>
    </section>

    <?php endif; ?>
</div>